### ISSUE TITLE
Mouse wheel 

### ISSUE THREAD

**Issue by vasiltabakov** [MurhafSousli/ngx-scrollbar#102]
There seems to be an issue with the scroll event frequency when scrolling with the mouse wheel. Check this:

![2018-12-09_18-36-31](https://user-images.githubusercontent.com/1178309/49700018-b5234100-fbe1-11e8-82e3-e97d51569d77.gif)

the right 'column' top offset is synchronized with the scrollTop of the event.target object in the elementScrolled() subscription.

Is the library handling the mouse-wheel scroll or is it handled by CDK?

**Comment by MurhafSousli** [comment]
It is handled by the CDK, please add reproduction!

**Comment by vasiltabakov** [comment]
Here you go:
https://stackblitz.com/edit/angular-ywog1v

When there are 10k elements the issue is very apparent. With 1k not so much. 

The CDK scrollable has something called auditTimeInMs, maybe this could be exposed as an option in your lib?

**Comment by MurhafSousli** [comment]
Obviously, when you try to render large amount of items, it is normal to experience a bad performance, you issue can be solved using virtual scroll on your 1k or 10k elements

**Comment by vasiltabakov** [comment]
In my actual app the number of lines are less than 500, but OK will fork and adjust to my needs.

**Comment by MurhafSousli** [comment]
@vasiltabakov Each scrollbar subscribes to the CDK scrolling event (auditTime is not used) https://github.com/MurhafSousli/ngx-scrollbar/blob/master/projects/ngx-scrollbar/src/scrollbar/ng-scrollbar-thumb.ts#L50 

But maybe it is caused by the `animationFrameScheduler.schedule()`, try to remove it and check if it fixes the issue https://github.com/MurhafSousli/ngx-scrollbar/blob/master/projects/ngx-scrollbar/src/scrollbar/ng-scrollbar-vertical.ts#L59-L64

**Comment by vasiltabakov** [comment]
Check this:
https://stackblitz.com/edit/angular-jwsfnd?file=src%2Fapp%2Fapp.component.ts

Plain old browser scroller using (scroll) even if it's not efficient it's delivering the events fast enough.

As for your suggestion, isn't the `updateScrollbar` function also used when scrolling with the scrollbar thumb? The only issue is when scrolling with the mouse wheel. But you're correct since you're listening to the same underlying CDK event the thumb in your scrollbar also is kind of jumpy.

Check the source of the CDK scrollabe thing:
https://github.com/angular/material2/blob/20f89245f4273c9ed8d3ac0b20e33aac1f42b3de/src/cdk/scrolling/scroll-dispatcher.ts

```
const subscription = auditTimeInMs > 0 ?
        this._scrolled.pipe(auditTime(auditTimeInMs)).subscribe(observer) :
```
where auditTime is the rxjs operator auditTime:
https://www.learnrxjs.io/operators/filtering/audittime.html

Maybe it's a matter of having:
```
<div cdkScrollable auditTimeInMs="0" ... >
</div>
```

Pretty sure this is the culprit. Anyway will solve it on my own, not many users will have such an edge case.

**Comment by MurhafSousli** [comment]
@vasiltabakov the auditTime in the CDK is just an option, but where we subscribe to it, the auditTime is not used, it should emit as a normal scroll event.

The `animationFrameScheduler` on the other hand delays updating the UI until the browser allows it, (which is supposed to improve the UX), try removing it maybe it is the one blocking the UI from updating and causing this behavior

**Comment by vasiltabakov** [comment]
Exactly, if not provided the CDK dispatcher uses the default auditTime of 20 or more ms. I still think this has nothing to do with your lib but only CDK, anyway, great work!

**Comment by MurhafSousli** [comment]
@vasiltabakov I can assure you, there is no auditTime when you call `scrollable.elementScrolled()`

Check the deceleration of the scroll event listener

https://github.com/angular/material2/blob/master/src/cdk/scrolling/scrollable.ts#L50-L53

**Comment by vasiltabakov** [comment]
Really strange then, anyway, will find out what's going on and publish and update whenever. Cheers

**Comment by vasiltabakov** [comment]
@MurhafSousli it's the `transform: translate3d(0,0,0); ` css property that's causing the trouble. I don't think it's needed for the cdkScrollable div, please fix it. Thanks

Check my sample again:
https://stackblitz.com/edit/angular-ywog1v?file=src%2Fapp%2Fapp.component.html

When you inspect and remove the transform style it works fine.
![image](https://user-images.githubusercontent.com/1178309/49791510-507afa00-fd39-11e8-914c-eadb3c82b06b.png)

**Comment by vasiltabakov** [comment]
I mean can you remove the `transform: translate3d(0,0,0);` style from the **ng-scrollbar-view**:
https://github.com/MurhafSousli/ngx-scrollbar/blob/e6d4f9890d47f8fe760b12ca6e9d1a5d041241c7/projects/ngx-scrollbar/src/scrollbar/ng-scrollbar.scss#L28

if it's not needed, because that's what's causing the problem for me. 
Thanks for the tip, I was wondering what was disabling it.

**Comment by MurhafSousli** [comment]
That does not fix anything, your issue is not related to this library, it has to do with large data you are rendering in your page, using CDK virutal scroll will fix your problem.

**Comment by vasiltabakov** [comment]
Oh man. Let me do a video.

**Comment by vasiltabakov** [comment]
Here's a 1 minute video demonstrating the problem (There's something wrong with stackbiz and I can't save the changes, will do later).

To be even more clear: The actual problem is that the black 'boxes' do not 'scroll' along with the cdkScroller area. This seems to be some browser bug related to the styling of the cdkScrollable container which has a translate3d css style.

When you remove the style the 'synchronization' works - visually. Don't have time to dig as to why this happens. As I said - it's already fixed in my project using the same fix as demonstrated in the video.

But should this style be in the library too? Any reason for it?
And you're wrong, the problem is **with** the library. Because of that style and because of some webkit whatever it is not delivering the events properly or not scrolling properly.

It has **nothing** to do with the amount of items in the scroller.
Let me know if you need more explanations.


[ngx-scrollbar-bug-video.zip](https://github.com/MurhafSousli/ngx-scrollbar/files/2667838/ngx-scrollbar-bug-video.zip)

**Comment by MurhafSousli** [comment]
> But should this style be in the library too? Any reason for it?

Yes, using `transform: translate3d(0,0,0)` increases performance with Hardware-Accelerated CSS.

I have seen this in other custom scrollbar libraries too, your edge case actually proves that it is doing something, therefore will keep it and you can override its value in your app for your special case.

**Comment by vasiltabakov** [comment]
My edge case might become someone else's edge case. 
I mean, listening to scroll events is not unheard of. Using the mouse wheel to scroll - neither. You never know how users will consume such events and for what reason.

As I see it, the library is much more about styling than hardware acceleration. Without that css trick scrolling would perform just as expected and as usual for a browser.

The least you can do is add a note somewhere in the documentation stating that the hardware-accelerated CSS style might cause issues with mouse wheel scroll events.

**Comment by vasiltabakov** [comment]
In case someone else has the same issue, because of refactoring of the lib the class now is called `ng-scroll-view`, to avoid the scroll event issue do something like:
```css
::ng-deep ng-scrollbar .ng-scroll-view {
  transform: none !important;
}
```
and I'm asking again for the author (@MurhafSousli) to include information about this ... thing ... somewhere in the documentation. Not doing so is very unprofessional.
