### ISSUE TITLE
How to conditionally color the scroll bar?

### ISSUE THREAD

**Issue by kevpeisker** [MurhafSousli/ngx-scrollbar#107]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [ x] question
```
I need to conditionally style the scrollbar background color depending on how many rows I have in my table.

 My component stylesheet looks like:

`_::ng-deep .scroll-bar {
	background-color: #DDDDDD !important;
	top:42px !important;
}
::ng-deep .scroll-bar2 {
        background-color: #F8F8F8 !important;
	top: 42px !important;
}_'

My attempt to conditionally style:
`<ng-scrollbar #scrollable thumbClass="scroll-thumbs" viewClass="scroll-view" 
				  barClass="component.numExpensesAdded == 0 ? scroll-bar : scroll-bar2" 
				  [disableOnBreakpoints]="false">`

### Desired functionality

This is not working. Is there either different method or syntax to use, or is this functionality possible with the ngx-scrollbar?

**Comment by MurhafSousli** [comment]
Try CSS variables

```scss
::ng-deep .scroll-bar {
  background-color: var(--scrollbar-color) !important;
}
```
Get a reference any parent element or component and set the following property
```ts
element.style.setProperty('--scrollbar-color', colorValue);
```

**Comment by kevpeisker** [comment]
That worked great, much appreciated. Thank you!
