### ISSUE TITLE
bound [disabledOnBreakpoints] produces ExpressionChangedAfterItHasBeenCheckedError

### ISSUE THREAD

**Issue by vasiltabakov** [MurhafSousli/ngx-scrollbar#108]
https://stackblitz.com/edit/angular-suvv7p?file=src%2Fapp%2Fapp.component.html

Check the console, you'll find something similar to:
![image](https://user-images.githubusercontent.com/1178309/49890815-b0fb5b80-fe4d-11e8-9854-b06cefb4126d.png)

In my case I need this to **always** be 'false', so just having `disabledOnBreakpoints="false"` instead of `[disabledOnBreakpoints]="false"` works, maybe this should be improved

**Comment by MurhafSousli** [comment]
You should not use this input as an attribute, because the false you passed isn't false, it is "false" which return true,

The error you are getting is because of `setTimeout`, here is a fixed https://stackblitz.com/edit/angular-cpwcuw?file=src/app/app.component.ts

**Comment by vasiltabakov** [comment]
Fix it in your library. If you don't know how I can help you. You should not enforce people to use OnPush change detection strategy just because of your lib. 

The setTimeout is just a demonstration. If you INITIALLY set `[disableOnBreakpoints]="false"` with no change detection strategies or bound values and no timeout → you get the same error.

**Comment by mkhuda** [comment]
This problem still exist.
