### ISSUE TITLE
The scrollbar sets to default view if width of the screen is between 755 and 961 px

### ISSUE THREAD

**Issue by kodwi** [MurhafSousli/ngx-scrollbar#118]
### Bug Report or Feature Request (mark with an `x`)
```
bug report 

```

### OS and Version?

Windows 10

### Versions

Angular CLI: 7.1.4
Node: 8.11.4
OS: win32 x64
Angular: 7.1.4
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.11.4
@angular-devkit/build-angular     0.11.4
@angular-devkit/build-optimizer   0.11.4
@angular-devkit/build-webpack     0.11.4
@angular-devkit/core              7.1.4
@angular-devkit/schematics        7.1.4
@angular/cdk                      7.2.0
@angular/flex-layout              7.0.0-beta.22
@angular/material                 7.2.0
@ngtools/webpack                  7.1.4
@schematics/angular               7.1.4
@schematics/update                0.11.4
rxjs                              6.3.3
typescript                        3.1.6
webpack                           4.23.1

### Repro steps

The scrollbar sets to default view if width is is between 755 and 961 px.
Just try to change the width to 970 px and scroll up or down, then to 950 px and do the same. You'll see the bug.

[Update 1] The scrollbar repairs if width becomes less than 755 px. So, the bug appears between 755 and 961 px.

[Update 2] I noticed that there are several bug's ranges of width.

### Desired functionality

I desire the ngx-scrollbar to work correctly

**Comment by kodwi** [comment]
What do you mean? Should I record a video or what? I wrote the steps to reproduce. It reproduces even on the demo site.

[The bug](https://yadi.sk/i/b5z1vzwInZrIlQ)
[Ok](https://yadi.sk/i/r79VS_jjMS7CAQ)

**Comment by MurhafSousli** [comment]
@kodwi Is this the first time you use Angular and Github? Yes, you should help your self and use the  [stackblitz template](https://stackblitz.com/edit/ngx-scrollbar) to reproduce your issue, I don't have time to reproduce everyone's issue.

**Comment by MurhafSousli** [comment]
This isn't a bug, read the docs properly, It is mentioned in the README

 > Because it is not possible to hide the native scrollbars on mobile browsers, the only solution is to fallback to the native scrollbars. To disable this option give it false value.

```html
<ng-scrollbar [disableOnBreakpoints]="false"></ng-scrollbar>
```
