### ISSUE TITLE
Position fixed within ng-scrollbar not correctly positioned

### ISSUE THREAD

**Issue by elDrimm** [MurhafSousli/ngx-scrollbar#119]
### Bug Report or Feature Request (mark with an `x`)
```
- [X] bug report 
- [ ] feature request
- [ ] question
```

I've search in the issues and found [this closed issue](https://github.com/MurhafSousli/ngx-scrollbar/issues/24). (more about this below)

### OS and Version?
iOS 12.1

### Versions
ngx-scrollbar 4.1.1, Angular 7

### Repro steps
https://angular-l21cj6.stackblitz.io/
within a ng-scrollbar, create a fixed element which is fullscreen. (see stacklbitz)

### The log given by the failure
-

### Desired functionality
I want to know how to use a fullscreen fixed element which is inside of ng-scrollbar.

### Mention any other details that might be useful
https://angular-l21cj6.stackblitz.io/

I've attached two screenshots, one taken from an iPad and one from desktop (Chrome, Windows 10).
I've tried the solution of [this closed issue](https://github.com/MurhafSousli/ngx-scrollbar/issues/24) by setting the `.ng-scroll-view` to `none`. This doesn't seem to be working in the latest version.

iPad:
![ipad ng-scrollbar fullscreen](https://user-images.githubusercontent.com/34384541/50481152-4830e900-09e0-11e9-8710-916018b202c8.png)

Desktop:
![desktop ng-scrollbar fullscreen](https://user-images.githubusercontent.com/34384541/50481169-6696e480-09e0-11e9-9e3a-b5a6f9079044.PNG)

**Comment by MurhafSousli** [comment]
Let's go back to basics in CSS

_**When you use a fixed position element that covers a scrollable element, then it will block the scroll view and it won't scroll anymore.**_

Use `*ngIf` to show the modal on a condition, but don't complain if it blocks it, this is CSS

***

Another solution is to use `position: sticky;`, check this [fixed stackblitz](https://stackblitz.com/edit/angular-yjm6jn?file=src/app/app.component.css)

As mentioned in the README, the library uses native scrolling mechanism, so what works without the custom scrollbars, should work with the custom scrollbars.

**Comment by elDrimm** [comment]
Maybe I haven't explained it properly enough, but with the position sticky the element will still be within the ngx-scrollbar container. However I can't seem to get a fullscreen div (a popup with fullscreen backdrop) working if the poup is within ng-scrollbar. I know that a fixed element will block the scrolling, that's the preferred behaviour.

In the above screenshots I attached you'll see the `<header>`-element on iOS, but on the browser the modal overlaps the header which is the wanted behaviour.

The fixed element will stick to the ng-scrollbar container and not to the window. I thought by setting the transform to none will fix this because of the fact that `transform` creates a new local coordinate system.

So my popup becomes fixed relative to the element with the transform property (`.ng-scroll-view`). So when ng-scrollbar isn't the page's entire width/height it will never become fullscreen. Apparently this only happens on iOS. Unfortunatly setting the transform property to none doesn't fix the issue on iOS.

Tested it on: Android Tablet, Android Phone, iPhone, iPad, Chrome, FireFox, Edge and IE11.

**Comment by MurhafSousli** [comment]
1. Use the [Angular CDK for the overlay](https://material.angular.io/cdk/overlay/overview).
2. Keep the scrollbar component for the scrollable content, do not mix stuff.
3. Just in case you did not notice the custom scrollbar is disabled on mobile (iOS), as mentioned in the  README

**Comment by michal890203** [comment]
Or just overide css for .ng-scroll-viewport without the need to rebuild the modal

`.ng-scroll-viewport-wrapper .ng-scroll-viewport { 
                contain: none;
} `
