### ISSUE TITLE
Application Crash

### ISSUE THREAD

**Issue by ongun23** [MurhafSousli/ngx-scrollbar#121]
### Bug Report or Feature Request (mark with an `x`)
```
- [ x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] question
```

### Mention any other details that might be useful

After upgrading from ngx-scrollbar@3.1.2-beta.0 to latest version of the package the entire application is getting freeze and killing the web browser.

**Comment by MurhafSousli** [comment]
The latest version is `4.1.1` not `3.1.2-beta.0`

**Comment by ongun23** [comment]
@MurhafSousli I said the same thing. We migrated from and old version to newest version it crashed the application without any error or warning.

**Comment by MurhafSousli** [comment]
It is probably an issue with your project setup

**Comment by ongun23** [comment]
Do you have any suggestion to check which config can cause this?

Thanks.

**Comment by MurhafSousli** [comment]
You did not fill the issue template properly, but I can guess that there is a conflict with you Angular packages versions, you need to upgrade all angular packages to v7.

If you already have v7 and still not working, remove **node_modules** folder and try a fresh npm install
