### ISSUE TITLE
scrollTo() argument should be smoth-scroll.ScrollToOptions not lib.dom

### ISSUE THREAD

**Issue by trubit** [MurhafSousli/ngx-scrollbar#124]
https://github.com/MurhafSousli/ngx-scrollbar/blob/9cf19937dcd75503474528100317424e6f45db73/projects/ngx-scrollbar/src/scrollbar/ng-scrollbar.ts#L178

Currently this is using lib.dom ScrollToOptions, so its missing duration and easeFunc properties.
This shoud use exported interface ScrollToOptions from smooth-scroll.

**Comment by MurhafSousli** [comment]
Yupp! thanks for reporting, will fix that asap
