### ISSUE TITLE
Is there a way to subscribe to scrollbar.update() events

### ISSUE THREAD

**Issue by rooby** [MurhafSousli/ngx-scrollbar#126]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [x ] question
```

### OS and Version?
N/A

### Versions
node: 10.15.0
npm: 6.4.1
@angular-devkit/architect         0.12.2
@angular-devkit/build-angular     0.12.2
@angular-devkit/build-optimizer   0.12.2
@angular-devkit/build-webpack     0.12.2
@angular-devkit/core              7.2.2
@angular-devkit/schematics        7.1.4
@angular/cli                      7.1.4
@ngtools/webpack                  7.2.2
@schematics/angular               7.1.4
@schematics/update                0.11.4
rxjs                              6.3.3
typescript                        3.1.6
webpack                           4.28.4
ngx-scrollbar: 3.3.4

### Repro steps
I have some content in an ng-scrollbar which contains some accordions.
When all the accordions are collapsed there is no scrollbar but when they are expanded the scrollbar is visible.
When accordions are toggled I trigger scrollbar.update() so that the scrollbar can adjust to the new content height.
I have a special footer that appears when the user scrolls to the bottom, which is a bit like this:
```
      this.scrollbar.scrollable.elementScrolled().subscribe(event => {
        const scrollableDiv = event.srcElement
        this.footerVisible = scrollableDiv.scrollTop + scrollableDiv.clientHeight >= scrollableDiv.scrollHeight
      })
```

This works fine for the most part, however when the accordions are all collapsed and I call scrollbar.update() it doesn't trigger a scrollbar.scrollable.elementScrolled() event so my footerVisible flag is not updated.

Is there a recommended way that I can have some code run after scrollbar.update() has done it's thing?

### The log given by the failure
N/A

### Desired functionality

I would like to be able to trigger some code after scrollbar.update() runs, with the ability to easily get the scrollable div element at that time.

### Mention any other details that might be useful
N/A

**Comment by MurhafSousli** [comment]
@rooby Update is not an event, It is a function that just calls `this._changeDetectorRef.markForCheck()` to update its template binding manually.
If you look into previous issues, some had similar use cases

**Comment by rooby** [comment]
I haven't found anything comparable in other issues but I'll post back here if I work out how to do it.

**Comment by MurhafSousli** [comment]
As mentioned above, there is no need to subscribe as this will only update the template binding of the component, the following should work fine:
 
```ts
scrollbar.update();
doSomething();
```
