### ISSUE TITLE
Zooming in and out browser

### ISSUE THREAD

**Issue by applegb** [MurhafSousli/ngx-scrollbar#127]
### Bug Report or Feature Request (mark with an `x`)
```
- [ x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] question
```

### OS and Version?
Windows 10, chrome browser

### Versions
scrollbar - 4.1.1
angular 7

### Repro steps
Set zoom to 50% and you'll see the native scrollbar show up, also the size of the scroll area dramatically shifts. (probably because of scrollbar offset not being correct?)

### Desired functionality
Zooming in or out would not affect the size of the scroll area and the native scrollbar would not show

**Comment by MurhafSousli** [comment]
I am aware of this, there is no solution and we as developers are not supposed to provide great UI/UX while user is zooming 50% :)

**Comment by applegb** [comment]
Hmm. Ok, thanks for letting me know. I haven't looked into what is actually happening, do you know where the issue lies?

**Comment by MurhafSousli** [comment]
This plugin uses the browser scrollbar, it just hides them, so zooming will cause them to appear again.

**Comment by tfxdevelopment** [comment]
I agree an initial argued the same UI/UX concerns. Could you make NATIVE_SCROLLBAR_SIZE injectable so we could customize this behavior? I have a requirement to support 80% zoom for my users. Otherwise I have to hack at it to 22px

**Comment by cluetjen** [comment]
>  there is no solution for this
Shouldn't div.clientWidth give us the width w/o scrollbar so we can calculate how much space we've to move out of view? - to be honest, I didn't test it

> and we as developers are not supposed to provide great UI/UX while user is zooming 50% :)
totally agree, but when using scrollbars with dark background, even a zoom level of 90% will show a white line left beside the scrollbar (Chrome) and 90% makes totally sense on some laptop screens.
