### ISSUE TITLE
Can't scroll content using keyboard keys

### ISSUE THREAD

**Issue by Antobbo** [MurhafSousli/ngx-scrollbar#128]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] question
```

### OS and Version?

Windows 7
Scrollbar version 2.2.0

### Versions

`Angular CLI: 6.2.9
Node: 8.11.2
OS: win32 x64
Angular: 6.1.7
... animations, common, compiler, compiler-cli, core, forms
... http, platform-browser, platform-browser-dynamic, router

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.8.9
@angular-devkit/build-angular      0.8.9
@angular-devkit/build-ng-packagr   0.7.5
@angular-devkit/build-optimizer    0.8.9
@angular-devkit/build-webpack      0.8.9
@angular-devkit/core               0.8.9
@angular-devkit/schematics         0.8.9
@angular/cli                       6.2.9
@angular/language-service          6.1.10
@ngtools/json-schema               1.1.0
@ngtools/webpack                   6.2.9
@schematics/angular                0.8.9
@schematics/update                 0.8.9
ng-packagr                         3.0.6
rxjs                               6.2.2
typescript                         2.9.2
webpack                            4.16.4
`

### Repro steps

Anytime there is a scrollbar used in conjunction with NgbActiveModal I can't use the keyboard keys to scroll. For example, if the component which has the scrollbar applied to it sits inside a NgbActiveModal popup window, I can't use any of the keyboard keys to scroll the content. If it happens outside of the NgbActiveModal, everything works.

### The log given by the failure

N/A

### Desired functionality

Be able to scroll with keyboard keys when a component using the scrollbar sits inside a NgbActiveModal window

**Comment by MurhafSousli** [comment]
@Antobbo I think your issue is not related to this plugin, this scrollbar plugin uses the native scrolling mechanism, it just hides the native scrollbar, so it should scroll if the modal allows it to.

I have added a reproduction here: https://stackblitz.com/edit/angular-brt8td?file=app/modal-basic.html, The modal seems to disable the keyboard

**Comment by Antobbo** [comment]
@MurhafSousli, great, thanks for the clarification and the demo, I will then look into that and see what it is that's affecting the functionality of the scrollbar (in my case it's not blocking but limiting its functionality)
cheers
