### ISSUE TITLE
Angular Change Detection Stuck in Infinite Loop

### ISSUE THREAD

**Issue by RyanHow** [MurhafSousli/ngx-scrollbar#129]
Hi,

I updated from 3.1.0 to 4.1.1.

I have an issue with [autoUpdate]="true".

The angular change detection is getting stuck in an infinite loop when certain content is inside the scroll view and the browser freezes up.

If I set [autoUpdate]="true" it solves the issue.

I tried to narrow down the issue, but it seemed to be related to having an asynchronous ngFor inside the content (ie. ngFor on an observable array).

I haven't got a small reproducible test case sorry. And it only started doing it after the update.

Any ideas on the issue or the workaround?

Changing to onPush change detection works in some cases too, but I can't use that in every case.

**Comment by MurhafSousli** [comment]
@RyanHow I highly recommend you to use `OnPush` in every case, the `[autoUpdate]` uses the `MutationObserver` which emits when the content changes, if your component changes the content constantly then you might get infinite loop
Either disable `autoUpdate` and use `ngScrollbar.update()` manually or use `OnPush`

**Comment by RyanHow** [comment]
Thanks. I have one case where I can't change the strategy to OnPush. I have disabled autoUpdate. It was just strange that it only did it on some cases.

I'll manually call the update method like you suggest.

Perhaps my loop was replacing DOM every cycle, and that was in turn triggering the mutation observer. It was only a tiny loop, so I didn't add any trackBy. I'll try that and see if it fixes it.

Thanks!
