### ISSUE TITLE
Is it possible to know if an element in the scroll bar is in the visible region? 

### ISSUE THREAD

**Issue by nkmadala** [MurhafSousli/ngx-scrollbar#130]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] question
```

### Desired functionality
Is it possible to know if an element in the scroll bar is in the visible region? Basically, I'm trying to scroll using the provided scroll functions, only when the desired element is not in the visible region of the scrollbar.

**Comment by MurhafSousli** [comment]
No, it is not possible out of the box, but you can use a 3rd party library or implement your solution with this library
