### ISSUE TITLE
Slice pipe is not working

### ISSUE THREAD

**Issue by ArunPandianB** [MurhafSousli/ngx-scrollbar#131]
Slice pipe is not working inside the scrollbar.

**Versions:**

Angular:7.0
Node: 10.15.1
npm:6.7.0

### OS and Version?

> Windows 10.

**Comment by MurhafSousli** [comment]
Please add a reproduction for your issue

**Comment by ArunPandianB** [comment]
created a stackblitz repo  in https://angular-75kaqz.stackblitz.io.

**Comment by MurhafSousli** [comment]
The link you posted isn't useful, can you send the edit link instead

**Comment by ArunPandianB** [comment]
Edit URL: https://stackblitz.com/edit/angular-75kaqz

**Comment by ArunPandianB** [comment]
In Edit URl it is working fine, but as website its running into a loop.
Also tried downloading the project to local and serve resulted in the same infinite loop.

**Comment by MurhafSousli** [comment]
I cannot help you without a proper reproduction, however I think your problem is related to the change detection

Try if the following fixes your issue
```html
<ng-scrollbar [autoUpdate]="false"></ng-scrollbar>
```

If it did not work, try using `changeDetection: ChangeDetectionStrategy.OnPush` in your component

```ts
@Component({
  selector: 'my-app',
  templateUrl: './app.component.html',
  styleUrls: [ './app.component.css' ],
  changeDetection: ChangeDetectionStrategy.OnPush
})
```

**Comment by ArunPandianB** [comment]
The same project in local environment didn't worked for me.

**Comment by MurhafSousli** [comment]
Cannot help you without a reproduction

**Comment by ArunPandianB** [comment]
Already gave reproducible example in stackblitz.
Edit URL: https://stackblitz.com/edit/angular-75kaqz
View URL: https://angular-75kaqz.stackblitz.io.

**Comment by MurhafSousli** [comment]
it is working, no infinite loop, if you can't reproduce it then the issue has to be related with your project
