### ISSUE TITLE
new property SHOWN won't work with "hover"""""""""""

### ISSUE THREAD

**Issue by lisophorm** [MurhafSousli/ngx-scrollbar#132]
### Bug Report or Feature Request (mark with an `x`)
```
- [X ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] question
```

### OS and Version?
windows 10
### Versions
4.1.1

### Repro steps
    <ng-scrollbar [compact]="true" #ngScroller [shown]="hover" barClass="scroll-bar" thumbClass="scroll-thumbs" >

### The log given by the failure
n/a

### Desired functionality
scrollbar will show only on "hover". Expected functionality like deprecated "autohide"
actually scrollbar is always present

**Comment by MurhafSousli** [comment]
See the docs

 > [shown]: 'native' | 'hover' | 'always', default native
 > Configure when scrollbars should be shown.

  > **native**: scrollbars are shown when content is scrollable.
  > **hover**: scrollbars are shown when mouse is over the view port (and content is scrollable).
  > **always**: scrollbars are always shown.
