### ISSUE TITLE
MaxHeight with calc(100vh...) or calc(100%...) doesn't work

### ISSUE THREAD

**Issue by GitHubish** [MurhafSousli/ngx-scrollbar#133]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] question
```

### OS and Version?
> Windows 10 64bits
> Chrome 72

### Versions
Angular CLI: 7.2.1
Node: 8.9.0
Angular: 7.2.0

### Repro steps
CSS
`
.scroll-container {
  order: 1;
  flex: 0 1 auto;
  calc(100vh - 26rem)
}
`

HTML
`
<ng-scrollbar class="scroll-container" [compact]="true" #scrollRef>

</ng-scrollbar>
`

### Desired functionality
It seems that when I use a maxHeight defined in pixels (for example: 300px) it works. But if I put the maxHeight with a calculation in css in relation to the viewport or relative to its parent (ex: calc(100% - 26px)) it doesn't work. 

Thanks

**Comment by MurhafSousli** [comment]
If you still have the issue, please add a reproduction

**Comment by GitHubish** [comment]
I still have the problem. I share an example with you with the problem as soon as possible

**Comment by GitHubish** [comment]
Hello sorry about the problem, here is an example of what I'm trying to do with NgScrollbar. The max-height is not supported in this example. Maybe the solution is simple? 

https://stackblitz.com/edit/ngx-scrollbar-ydvegv

**Comment by GitHubish** [comment]
@MurhafSousli will you be able to study my problem?
