### ISSUE TITLE
Scrollbars

### ISSUE THREAD

**Issue by irinelpascu** [MurhafSousli/ngx-scrollbar#136]
### Bug Report or Feature Request (mark with an `x`)
```
- [x ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] question
```

### OS and Version?

macOS Mojave
Google Chrome 74

### Versions

node v10.6.0
npm 6.1.0
Angular 7.2.2

### Repro steps

Add a ```<ng-scrollbar>``` and style it with a max-height in px instead of a fixed height.
The vertical scrolling doesn't work and scrollbars don't appear.

### Desired functionality

the ```<ng-scrollbar>``` should work even when styled with max-height for the edge cases where we might only have one line in the scroll container and we need the scroll container to shrink

**Comment by MurhafSousli** [comment]
It has to have a fixed `height` or at least `min-height`

**Comment by irinelpascu** [comment]
> It has to have a fixed `height` or at least `min-height` just like a normal div

Have you ever worked with a div?
Here's how a div with a max-height works https://angular-vhx8ws.stackblitz.io
Maybe you will learn something new this time as i see you closed all the other issues on the same topic without having the decency of understanding the issue in the first place.
