### ISSUE TITLE
Bug. Change Detection is triggered too many times.

### ISSUE THREAD

**Issue by dmkorol** [MurhafSousli/ngx-scrollbar#137]
### Bug Report or Feature Request (mark with an `x`)
```
- [X] bug report -> please search issues before submitting
- [ ] feature request
- [ ] question
```

### OS and Version?
All

### Versions
4.1.1

### Repro steps
Add DoCheck() hook with logging to console.
Each scroll force changeDetection

Example with logging:
https://stackblitz.com/edit/ngx-scrollbar-kzjdzw?file=src%2Fapp%2Fhome%2Fhome.component.ts

### Desired functionality
Scroll shouldn't trigger change detection

**Comment by MurhafSousli** [comment]
This isn't a bug, I use the cdk scrolling module to handle the scrolling event, which should not trigger  change detection, however `ngDoCheck` always triggers, so don't use it.

Read [this article](https://blog.angularindepth.com/if-you-think-ngdocheck-means-your-component-is-being-checked-read-this-article-36ce63a3f3e5) for more info
