### ISSUE TITLE
No event on scrolling to bottom.

### ISSUE THREAD

**Issue by ibtisamniche-vteams** [MurhafSousli/ngx-scrollbar#139]
Hi!
I was using perfect scrollbar previously but there were some problems in that but now I am trying to use ngx-scrollbar. Everything works great except , I can't find any way to get to know when the scrollbar reached on bottom. Unlike perfect scrollbar there was an event on reaching bottom , but I can't find any way to get to know when the scrollbar reaches end.
If there's any way, Kindly let me know .
Thanks.

**Comment by MurhafSousli** [comment]
Hi! this can be a nice feature, for now you can do this

```ts
  @ViewChild(NgScrollbar) scrollbarRef: NgScrollbar;

  ngAfterViewInit() {
    this.scrollbarRef.scrollable.elementScrolled().subscribe(e => {
      let pos = e.target.scrollTop + e.target.clientHeight;
      let max = e.target.scrollHeight;
      if (pos >= max) {
        console.log('Reached the bottom');
      }
    })
  }
```

**Comment by MurhafSousli** [comment]
This feature will be tracked in #159
