### ISSUE TITLE
Scrollbars not shown if container is not displayed by default

### ISSUE THREAD

**Issue by edgargaza** [MurhafSousli/ngx-scrollbar#145]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting (done)
- [ ] feature request
- [ ] question
```

### OS and Version?

Windows 10, whatever

### Versions

**Angular CLI info**
Angular CLI: 7.3.9
Node: 11.13.0
OS: win32 x64
Angular: 7.2.15
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

**Packages and Versions**
@angular-devkit/architect         0.13.9
@angular-devkit/build-angular     0.13.9
@angular-devkit/build-optimizer   0.13.9
@angular-devkit/build-webpack     0.13.9
@angular-devkit/core              7.3.9
@angular-devkit/schematics        7.3.9
@angular/cdk                      7.3.7
@angular/cli                      7.3.9
@ngtools/webpack                  7.3.9
@schematics/angular               7.3.9
@schematics/update                0.13.9
rxjs                              6.3.3
typescript                        3.2.4
webpack                           4.29.0

### Repro steps

Create a div with `display: none` by default. Then, display it (`display: block`) and you will see that the scrollbars aren't shown.

### Desired functionality

The scrollbars should load when the document is ready, not when they're displayed (probably?).

**Comment by MurhafSousli** [comment]
Hi @edgargaza, Can you add a reproduction with this [stackblitz](https://stackblitz.com/edit/ngx-scrollbar)

**Comment by edgargaza** [comment]
Yeah, sure. Sorry for that, but I didn't find the stackblitz template for this resource. [Here it is](https://stackblitz.com/edit/ngx-scrollbar-itchwj)!

**Comment by MurhafSousli** [comment]
Use `*ngIf` to hide or show the scrollbar, here is a [fixed stackblitz](https://stackblitz.com/edit/ngx-scrollbar-y66uur?file=src%2Fapp%2Fhome%2Fhome.component.html)

**Comment by edgargaza** [comment]
Right! It solved the problem! Thanks a lot.
