### ISSUE TITLE
Nested scrollbars, child component scroll event not working

### ISSUE THREAD

**Issue by Nekronik** [MurhafSousli/ngx-scrollbar#146]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] question
```

### Repro steps

When using a scrollbar inside a virtual-scroll scrollbar, the nested scrollbar is not receiving scroll events.
 
I have prepared a reproduction of the problem on [Stackblitz](https://stackblitz.com/edit/ngx-scrollbar-hem2y4)

### Desired functionality

Nested scroll should work inside a virtual scroll

As always, thank you :smile:

**Comment by jaffbeto** [comment]
The last update fail on this.
![image](https://user-images.githubusercontent.com/17092218/63680712-965aee00-c7f4-11e9-9bde-79ca1a14f182.png)

**Comment by MurhafSousli** [comment]
Check the [changelog](https://github.com/MurhafSousli/ngx-scrollbar/blob/master/CHANGELOG.md), If that didn't help, please add a reproduction https://stackblitz.com/edit/ngx-scrollbar
