### ISSUE TITLE
How can we Use this scroller directive for third party html div element?

### ISSUE THREAD

**Issue by Sakthisivaprakash** [MurhafSousli/ngx-scrollbar#149]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x ] feature request
- [x] question
**How can we Use this scroller directive for third party html div element?**

```

### OS and Version?

> Windows 10 Home Basic

### Versions

Angular 7.0.4
Angular Material 7

### Mention any other details that might be useful

This one working fine as per your instructions:
` <ng-scrollbar #scrollable  class="my-scrollbar">`
    `<div class="">`
    `</div>`
`</ng-scrollbar>`

My requirement is, Does this third party element can be scrollable with this directive:

`<grid-table class>`
       `<div class="grid-header"></div>`
       `<div class="grid-content">`
`<---- Scrollable div --->`
        `</div>`
`<grid-table>`

**Comment by MurhafSousli** [comment]
Yea just add ng-scrollbar inside grid content
```html
<grid-table class>
  <div class="grid-header"></div>
  <div class="grid-content">

    <ng-scrollbar class="my-scrollbar">
           {{content}}
    </ng-scrollbar>

  </div>
<grid-table>
```

**Comment by Sakthisivaprakash** [comment]
> Yea just add ng-scrollbar inside grid content
> 
> ```
> <grid-table class>
>   <div class="grid-header"></div>
>   <div class="grid-content">
> 
>     <ng-scrollbar class="my-scrollbar">
>            {{content}}
>     </ng-scrollbar>
> 
>   </div>
> <grid-table>
> ```

Hi MurhafSousli,
But element with class "grid-content" is generated by third party library. So Adding ng-scollbar inside the element is not possible.
Is it possible to add the scroll based on querySelector like css queries.
Our template will look like this only:
`<grid-table [data]="dataSource">`
`</grid-table>`

**Comment by MurhafSousli** [comment]
it is up to the third party limitation, doesn't it allow custom template? try to put ng-scrollbar there
