### ISSUE TITLE
Use with ngx-infinite-scroll

### ISSUE THREAD

**Issue by nicholasp** [MurhafSousli/ngx-scrollbar#155]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [x] question
```

### Versions

angular 7

### Question
Is it possible to use ngx-scrollbar with another module like ngx-infinite-scroll ??
I would like to achive something like this: https://stackblitz.com/edit/ngx-infinite-scroll-plus-ngx-perfect-scrollbar

Is it possible to use ng-scrollbar as a directive?

### Desired functionality

I would like to load data from service when scroll reaches almost to the end

**Comment by MurhafSousli** [comment]
Hi @nicholasp, not with ngx-infinite-scroll, it works well with, with the current `version 4.2.0` You can listen to the scroll event and implement the logic your self, read https://github.com/MurhafSousli/ngx-scrollbar#scrollbar-functions

But next version, it will be much simpler, you will have an output `(bottomReached)="loadMore()"`

**Comment by nicholasp** [comment]
@MurhafSousli thanks for the reply! i did it with cdk to some point but the logic is very complex if you don't want to trigger it exactly at bottom and multiple times etc. the lib infinite scroll has implemented complex scenarios like scroll distance to trigger, throttle time, immediate invokes check etc. thats why i would like to use it. also i have multiple scrollbars in the same component and the viewchildren was a hell
