### ISSUE TITLE
Duplicate horizontal scrollbar if height is set to auto

### ISSUE THREAD

**Issue by marzn** [MurhafSousli/ngx-scrollbar#16]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [x] question
```

### OS and Version?
Linux and Firefox or Chrome

### Desired functionality
No duplicate horizontal scrollbar, if height is set to auto.

### Mention any other details that might be useful
Can be reproduced on https://murhafsousli.github.io/ngx-scrollbar/

[Screenshot](https://screenshots.firefox.com/Xcq3k8Yqmjvc7YmX/murhafsousli.github.io)

**Comment by MurhafSousli** [comment]
@marzn height should be fixed!
