### ISSUE TITLE
Content is cutted on Safari

### ISSUE THREAD

**Issue by lukasz-capala** [MurhafSousli/ngx-scrollbar#167]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] question
```

### OS and Version?

macOS High Sierra 10.13.6, Safari 12.1.1
### Versions

4.2.0, 4.1.1

### Repro steps

Scroll view has width of 100% + 18px that pushes native scrollbar outside the view. Its child width expands till it meet scrollbar (which results 100% on Windows, because native scrollbar presence affects child container, so it produce 100% + 18px - 18px). Unfortunately native Safari scrollbars overlays on content, so child container expanding to its 100% will result 100% + 18px, so content will be cutted (especially when text content hits right edge of container). Safari scrollbars just don't affect containers widths. It even can be seen on demo page, at second example.

### The log given by the failure

![image](https://user-images.githubusercontent.com/24389824/60197449-aa5b9100-983f-11e9-9fdd-c37e137b28b0.png)

**Comment by MurhafSousli** [comment]
I am currently in the process of finishing the new version, which fixes this since the strategy to hide native scrollbar has changed, will release it soon.

**Comment by MurhafSousli** [comment]
Please update to v5 and let me know if the issue still exist, closing this for now
