### ISSUE TITLE
Problems with getting it working

### ISSUE THREAD

**Issue by MTRNord** [MurhafSousli/ngx-scrollbar#17]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [x] question
```

### OS and Version?
> Windows 10
### Versions
```
Angular CLI: 1.6.1
Node: 9.3.0
OS: win32 x64
Angular: 5.2.4
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cli: 1.6.1
@angular-devkit/build-optimizer: 0.0.42
@angular-devkit/core: 0.3.1
@angular-devkit/schematics: 0.0.52
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.9.1
@schematics/angular: 0.1.17
typescript: 2.4.2
webpack: 3.10.0

```

### Repro steps
1. Made a fresh Project via the cli
2. Added a mdbs designed component (material design bootstrap)
3. Setup a Route. (The mdbs component is the target of this default route)
4. Add the following in the "index"/app.component.html
```
<ng-scrollbar>
  <router-outlet></router-outlet>
</ng-scrollbar>
```

### The log given by the failure

No errors in the console.

### Desired functionality

The browser scrollbar gets hidden like in your example page and replaced by a custom one.

### Mention any other details that might be useful

The Firefox Scrollbar doesn't get removed but the CSS is present when looking in the inspector. Manualy adding the `overflow: hidden` to the body disables the scroll and doesn't show the scrollbar of this repo

**Comment by MurhafSousli** [comment]
Did you set a height?

**Comment by MTRNord** [comment]
@MurhafSousli is there a way to use this with dynamic content where I don't know the exact height before I render the page?

**Comment by MurhafSousli** [comment]
@MTRNord I am not sure what you are trying to accomplish, but setting the height dynamically isn't a part of this plugin, you will find better answers on stackoverflow.

**Comment by MTRNord** [comment]
@MurhafSousli ok thanks anyway :) you gave me the needed hint
