### ISSUE TITLE
scrollToElement() issue

### ISSUE THREAD

**Issue by ajithanageswari** [MurhafSousli/ngx-scrollbar#170]
When i am trying to use scrollToElement(); I am passing the id as '34'.Its throwing the error
![error](https://user-images.githubusercontent.com/52451853/60507821-a8ce1500-9ce6-11e9-9126-e9b4b7d1e9fc.PNG)
![code](https://user-images.githubusercontent.com/52451853/60507877-c602e380-9ce6-11e9-9140-437c02e150e3.PNG)
![error](https://user-images.githubusercontent.com/52451853/60507878-c69b7a00-9ce6-11e9-8930-6aacb3c42617.PNG)

**Comment by MurhafSousli** [comment]
#34
