### ISSUE TITLE
Make it work on mobile browsers

### ISSUE THREAD

**Issue by MurhafSousli** [MurhafSousli/ngx-scrollbar#172]
Currently, `NgScrollbar` disables itself when used on mobile browser, because there were no way to figure out how to hide the native scrollbar on mobile browser.

Now I found out that we should provide the native scrollbar size manually (estimating 6px on Safari) a size that is sufficient to hide the native scrollbars.

To make it work properly, we should:
- Hide native scrollbars on mobile browsers
- Remove `disableOnBreakpoints` option completely.

**Comment by ruizmarc** [comment]
Just as a suggestion, if you make it work on phones, it would be great to be able to activate ngx-scrollbar or deactivate it depending if on phones/tablets or desktop.

**Comment by MurhafSousli** [comment]
@ruizmarc I will keep the `disabled` input, and user can activate/deactivate it by binding the `[disabled]` input
