### ISSUE TITLE
ERROR: when I use scrollIntoView in my code appears default browser scrollbar

### ISSUE THREAD

**Issue by VarPDev** [MurhafSousli/ngx-scrollbar#173]
### Bug Report or Feature Request (mark with an `x`)
```
- [x ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] question
```

### OS and Version?
windows 10

### Versions
@angular-devkit/architect         0.801.0
@angular-devkit/build-angular     0.801.0
@angular-devkit/build-optimizer   0.801.0
@angular-devkit/build-webpack     0.801.0
@angular-devkit/core              8.1.0
@angular-devkit/schematics        8.1.0
@angular/cdk                      8.0.2
@angular/material                 8.0.2
@ngtools/webpack                  8.1.0
@schematics/angular               8.1.0
@schematics/update                0.801.0
rxjs                              6.5.2
typescript                        3.4.5
webpack                           4.35.2

### Repro steps
setTimeout(() => {
   htmlElement.scrollIntoView({ behavior: 'auto', block: 'end', inline: 'center' })
}, 1000)

### The log given by the failure

no error in console

### Desired functionality
expected behaviour: not appear default browser scrollbar but only directive scrollbar

### Mention any other details that might be useful
it'all wrote up

**Comment by MurhafSousli** [comment]
Please add a reproduction

**Comment by VarPDev** [comment]
I resolved in other way, don't worry
