### ISSUE TITLE
MaxHeight with calc(100vh...) or calc(100%...) doesn't work

### ISSUE THREAD

**Issue by GitHubish** [MurhafSousli/ngx-scrollbar#174]
Bug Report or Feature Request (mark with an x)
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] question
OS and Version?
Windows 10 64bits
Chrome 72

Versions
Angular CLI: 7.2.1
Node: 8.9.0
Angular: 7.2.0

Repro steps
CSS
`.scroll-container { order: 1; flex: 0 1 auto; calc(100vh - 26rem) }`

HTML
`<ng-scrollbar class="scroll-container" [compact]="true" #scrollRef>`
Desired functionality
It seems that when I use a maxHeight defined in pixels (for example: 300px) it works. But if I put the maxHeight with a calculation in css in relation to the viewport or relative to its parent (ex: calc(100% - 26px)) it doesn't work.

reproduction: [stackblitz](https://stackblitz.com/edit/ngx-scrollbar-ydvegv)

The example has a one-button switch to see the case that works with the native scrollbar and the case that does not work with NgxScrollbar

Thanks

**Comment by MurhafSousli** [comment]
Please check v5.0.0 and let me know if the issue still exists, closing this for now
