### ISSUE TITLE
The scrollXTo method no longer seems to be available in version 5.0.0?

### ISSUE THREAD

**Issue by GitHubish** [MurhafSousli/ngx-scrollbar#176]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [x] question
```

### Versions
Ngx-Scrollbar 5.0.0.beta

### Desired functionality
Today I use this method to be able to scroll horizontally through a page with click-and-drag. I calculate how many pixels the cursor moves to scroll. It works well although it is not perfect or as smooth as a native solution.

I hope you are not planning to delete this method or do you see another solution for my use?

Thanks

**Comment by MurhafSousli** [comment]
There are some breaking changes in v5. that method is deprecated, use `scrollTo({left: xValue})` instead which does exactly the same.

The docs for v5 is available at the wiki page https://github.com/MurhafSousli/ngx-scrollbar/wiki, It is not finished yet, if you find some mistakes, please let me know.

For the smooth scroll, I don't know what ease function the native browser use, but you will be able to override the ease function in the next update and get the desired behavior. stay tuned!

**Comment by GitHubish** [comment]
Ok thank you, I will try to implement my code with the new version using the scrollTo({left: xValue}) method. I'll come back to you if I find any problems.

Thank you.
