### ISSUE TITLE
Safari native scrollbar is not hidden

### ISSUE THREAD

**Issue by ruizmarc** [MurhafSousli/ngx-scrollbar#177]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] question
```

### OS and Version?

MacOS Mojave, Safari 12.1 and Chrome 76

### Versions

Angular 8.1.3
Ngx-Scrollbar 5.0.0.beta.1

### Repro steps

In some of the examples, when using Safari or Chrome on MacOS, two scrollbars appear, the native one and the ngx-scrollbar one. 

![Screenshot 2019-08-06 at 17 43 21](https://user-images.githubusercontent.com/5717082/62554892-441c5200-b872-11e9-8043-38e4e78e66e4.png)

![Screenshot 2019-08-06 at 17 43 04](https://user-images.githubusercontent.com/5717082/62554898-47174280-b872-11e9-9538-0f7c4a2c43f8.png)

![Screenshot 2019-08-06 at 17 42 53](https://user-images.githubusercontent.com/5717082/62554901-4a123300-b872-11e9-932b-ea6a81238522.png)

### Desired functionality

I would expect to have only the ngx-scrollbar.

### Mention any other details that might be useful

I'm testing and looking to what you have done with version 5, you have done a great job! Thanks for your efforts! I hope this issue may help to polish the final details for the release :)

**Comment by MurhafSousli** [comment]
@ruizmarc Thanks for your feedback, it seems that the [native scrollbar size getter function](https://github.com/MurhafSousli/ngx-scrollbar/blob/dev/projects/ngx-scrollbar/src/lib/utils/scrollbar-manager.ts#L51-L68) is not working in Mac OS

I don't have Macbook, can you try it on your end?

```js
const box = this.document.createElement('div');
box.className = 'ng-scrollbar-measure';
this.document.body.appendChild(box);
const size = box.getBoundingClientRect().right;
this.document.body.removeChild(box);
return size;
```
```css
  .ng-scrollbar-measure {
    left: 0;
    overflow: scroll;
    position: fixed;
    top: -9999px;
  }
```

If it didn't work, give this a try

```js
function scrollbarWidth() {

  const body = document.body;
  const box = document.createElement('div');
  const boxStyle = box.style;

  boxStyle.position = 'fixed';
  boxStyle.left = 0;
  boxStyle.visibility = 'hidden';
  boxStyle.overflowY = 'scroll';

  body.appendChild(box);

  const width = box.getBoundingClientRect().right;

  body.removeChild(box);

  return width;
}
```

if that also didn't work, try the following code from [here](https://davidwalsh.name/detect-scrollbar-width)

```js
// Create the measurement node
var scrollDiv = document.createElement("div");
scrollDiv.className = "scrollbar-measure";
document.body.appendChild(scrollDiv);

// Get the scrollbar width
var scrollbarWidth = scrollDiv.offsetWidth - scrollDiv.clientWidth;
console.warn(scrollbarWidth); // Mac:  15

// Delete the DIV 
document.body.removeChild(scrollDiv);
```

If none worked, then we have to use a hardcoded size

**Comment by ruizmarc** [comment]
I will do it! I will come back with the results ;)

**Comment by ruizmarc** [comment]
I've just checked all three functions with MacOS and KDE. While in KDE I always obtain the real width of the scrollbar, in MacOS all functions output a 0. So I guess we will have to check if the output is 0, and in this case, hardcode the width...

**Comment by ruizmarc** [comment]
I've noticed that you solved it by checking if it is Safari or not. The thing is that it also happens when using Chrome, because the scrollbar is not a Browser thing, but a System thing. 

Mac users will probably keep seeing the scrollbar if using Chrome.

**Comment by MurhafSousli** [comment]
@ruizmarc How can we check if it is MacBook Safari? I am using the CDK platform to detect the browser

**Comment by ruizmarc** [comment]
From my point of view, I think it is easier that instead of taking into account OS or browser, we take into account the width of the scrollbar. I mean, it is no possible that the scrollbar takes 0px, so in this case, I would hardcode a fixed width. 

I don't see an easy way to get de OS a part from doing a Regex and extract the OS from the userAgent (present in window.navigator)

**Comment by MurhafSousli** [comment]
The main reason why it is not hardcoded because the scrollbar width will change if user zoomed in/out the browser

**Comment by ruizmarc** [comment]
I'm not sure I have understood your point, but I have never seen or noticed that a browser changes the size of the scrollbar when zooming in or out. (Just tested with my Mac just to make sure). However, I have noticed that ngx-scrollbar does it, were you referring to this?

Anyway, the calculation would work in most of the cases, except for Mac, so if we hardcode the size just when it is 0px (which means it overlapped), the problem is not as big as it seems... but I understand it is not the perfect solution.

**Comment by MurhafSousli** [comment]
@ruizmarc I am not sure about the Mac, but when you zoom in/out on Windows, the scrollbar width changes, e.g default size 17px, when zoom in it becomes 11px and out 20px

```ts
fromEvent(this.document.defaultView, 'resize', { passive: true }).pipe(
      debounceTime(this.globalOptions.windowResizeDebounce),
      tap(() => {
        const size = this.getNativeScrollbarSize();
        console.log(size);
        this.nativeScrollbarSizeSource.next(size);
      })
    ).subscribe();
```
![image](https://user-images.githubusercontent.com/8130692/62871335-ff863000-bd23-11e9-856f-0c26e4b8fcce.png)

https://www.loom.com/share/3b8128c809e04b969288387deeded2ab

---
 > so if we hardcode the size just when it is 0px 

0px? that won't hide it! that will keep it there

**Comment by ruizmarc** [comment]
It doesn't seem to happen on Mac and Ubuntu. It always gives you the same width, no matter the zoom level.

When I said 0px, I was referring to the result of the calculation of scrollbar width `getNativeScrollbarSize`. So if the calculation is 0, we can return a hardcoded width.

**Comment by MurhafSousli** [comment]
@ruizmarc Oh right, that is also an option
 
The best option is to hide them is using CSS
```
.hide-native-scrollbar {
  scrollbar-width: none; /* Firefox 64 */
  -ms-overflow-style: none; /* IE 11 */
  &::-webkit-scrollbar { /** Webkit */
    display: none;
  }
}
```
But that won't work on mobile browsers or older versions of FF, I am trying to figure out the best combination, what do you recommend?

**Comment by ruizmarc** [comment]
I'm agree with you that using CSS would be the cleanest option. However, if it won't work on mobile, we would be creating a new problem to solve. I think I would bet for the hardcoded width... until a better universal solution becomes feasible in order to avoid having different ways to do the same.

**Comment by MurhafSousli** [comment]
@ruizmarc Try v5.0.1, is it working now?

**Comment by ruizmarc** [comment]
Just tested it on Safari, Firefox and Chorme on MacOS and it looks perfect! Thanks a lot :D Great job!

**Comment by ryan-nebulock** [comment]
@MurhafSousli I know this is an old bug but the issue is back (present on the homepage as seen in screenshot)

<img width="1002" height="945" alt="Image" src="https://github.com/user-attachments/assets/24bb4faa-b997-4637-8058-0666e837c335" />

It seems like adding:
```css
.ng-scroll-viewport::-webkit-scrollbar {
  display: none !important;
  width: 0px !important;
  height: 0px !important;
}
```
fixes the issue as eluded to above (not sure if this would still be an issue mobile in 2026).

Is this the recommended way to resolve this Safari issue?
