### ISSUE TITLE
ScrollTo events always snap to the top

### ISSUE THREAD

**Issue by keyanrazi** [MurhafSousli/ngx-scrollbar#178]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [X ] question
```

### OS and Version?
Windows 8

### Versions
Angular CLI: 8.2.1
Node: 10.16.0
OS: win32 x64
Angular: 8.2.1

I've a pretty basic implementation of the ngx-scrollbar, and I copied some usage from a previous project. In this particular case, however, when I use any of the scrollTo events (scrolltobottom, scrolltoelement, etc), it always snaps to the top. I _assume_ it's a usage error, and so I'm just looking for help on how it should be structured to work appropriately.

Here is my markup:

```
 <div class="chat-history" #chatHistory>
                            <ng-scrollbar #chatHistoryScroll style="height: 600px;">
                                <ul style="margin-right: 15px;">
                                    <li class="clearfix" *ngFor="let message of conversation.messages">
                                     .........more stuff here.........
                                    </li>
                                    <div #chatHistoryBottom></div>
                                </ul>
                            </ng-scrollbar>
</div>
```

And the code in the component:

```
getConversation(id) {
    this.smsService.getConversation(id).then(r => {
      this.conversation = r;
      this.conversation.messages.sort((b, a) => new Date(b.sentAt).getTime() - new Date(a.sentAt).getTime());
      setTimeout(() => {
        this.scrollRef.scrollToBottom().then(r => {

        });
      }, 1000)

    })
  }
```

I added a setTimeout just to see if there was a conflict with the scrollToBottom running before the front-end fully rendered the new list of messages, causing it to think that the container was empty.

What am I missing or doing wrong here that causes the scroll events to always go to the top?

Thanks in advance for reading/replying, and for building this!

**Comment by MurhafSousli** [comment]
It would be much easier if you provide a stackblitz reproduction

**Comment by karedas** [comment]
It's not working for me either.
The "update" event doesn't work. I tried to pass him a simple pass:

View:
```
<ng-scrollbar class="scrollbar-output" #scrollBar resizeSensor [visibility]="always'" (updated)="test()">
    <div *ngFor="let item of values; let i=index;">{{i}}</div>
</ng-scrollbar> 
....
```

Inside my component: 
```
values = [];

ngOnInit() {
  setInterval() => {
    this.values.push('1');
  }, 1500);
}

test() {
    console.log('updated') 
}
```
---

But it doesn't work. Not even if I directly recall the function in this way:


```
setInterval(function(){
   this.scrollbar.scrollToBottom()
}, 1000)

```

**Comment by karedas** [comment]
Mhh, ok.
Calling the method "update", works.

this.scrollBar.update();
