### ISSUE TITLE
How to access thumb size when content size is changed

### ISSUE THREAD

**Issue by anary** [MurhafSousli/ngx-scrollbar#179]
I try to set the scroll bar in the center of the page by code. As the content is dynamic, I need to calculate the width and height when the content size is changed. 
I did something like that:  

@ViewChild('scrollable') scrollbarRef
this.scrollbarRef.scrollXTo( this.workSpace.width*0.5).subscribe();
this.scrollbarRef.scrollYTo( this.workSpace.height*0.5).subscribe();

but because of Scroll bar thumb size, it is not exact in the center.

My question is how can I access the thumb size  ( get thumbSize())? Or is there a better way to achieve that alway location thumb in the center of the page?

Thanks very much for help!

**Comment by MurhafSousli** [comment]
Closing as does not follow the template issue
