### ISSUE TITLE
Ngx-scrollbar with Angular Material(Drag and Drop)

### ISSUE THREAD

**Issue by komxvl** [MurhafSousli/ngx-scrollbar#180]
Hi! Thanx for this library. Can you help me? I use ngx-scrollbar with angular material dnd and container doesn't scroll when I dragging element, but when I remove ng-scrollbar everythin is good. 
`<ng-scrollbar  [track]="'horizontal'">
<div cdkDropList cdkDropListOrientation="horizontal"  [cdkDropListAutoScrollDisabled]='false' class="example-list" (cdkDropListDropped)="drop($event)" cdkDragLockAxis="x"> 
    <div class="example-box" *ngFor="let timePeriod of timePeriods" cdkDrag (cdkDragStarted)="dragStart($event)" (cdkDragMoved)="dragMoved($event)" >
      {{timePeriod}}
      <div class="test" cdkDragHandle>
         <span>+</span>
      </div>
    </div>
  </div>
</ng-scrollbar>`

**Comment by MurhafSousli** [comment]
@komxvl the custom scrollbars should work as the native ones, if the native one scrolls on dragging then ng-scrollbar will also scroll on dragging.
Please add a reproduction if you want further support https://stackblitz.com/edit/ngx-scrollbar

**Comment by komxvl** [comment]
Thnx, for your answer. Reproduction: https://stackblitz.com/edit/angular-vxgi97

**Comment by MurhafSousli** [comment]
First upgrade to latest version, then just add the following styles

```scss
ng-scrollbar {
  height: 70px;
  width: 100%;
}
```
Here you go https://stackblitz.com/edit/angular-jnthf4?file=src/app/components/tabs/tabs.component.html

**Comment by komxvl** [comment]
Thnx for your answer sir, but the container doesn't scroll yet. I update my stackblitz, https://stackblitz.com/edit/angular-h5jyqs . Help me, please!

**Comment by MurhafSousli** [comment]
In this case use the custom viewport directive `scrollViewport` on the `cdkDropList`

Here is a fixed one https://stackblitz.com/edit/angular-xozc2r?file=src/app/components/tabs/tabs.component.html

**Comment by beyondtheobservableuniverse** [comment]
Angular 9 solution?

**Comment by beyondtheobservableuniverse** [comment]
> In this case use the custom viewport directive `scrollViewport` on the `cdkDropList`
> 
> Here is a fixed one https://stackblitz.com/edit/angular-xozc2r?file=src/app/components/tabs/tabs.component.html

Hi
This is not working for me in Angular 9.
![image](https://user-images.githubusercontent.com/30147726/81901883-82902b80-95bf-11ea-8a32-72fb2f404c53.png)
