### ISSUE TITLE
Add '@juggle/resize-observer' to dependencies

### ISSUE THREAD

**Issue by ajeiie120120** [MurhafSousli/ngx-scrollbar#185]
**[Can't reproduce on stackblitz]**

In version 5.0.1 this error is triggered on ng start:

```
ERROR in ./node_modules/ngx-scrollbar/fesm2015/ngx-scrollbar.js
Module not found: Error: Can't resolve '@juggle/resize-observer' in 'C:\Users\davdi\IdeaProjects\CouchFactoryConsole\node_modules\ngx-scrollbar\fesm2015'
```

I suppose is due to this line of code in `ngx-scrollbar.js`:

`from(import('@juggle/resize-observer')).pipe(map((/**`

This is my angular.json:

`{
  "$schema": "./node_modules/@angular/cli/lib/config/schema.json",
  "version": 1,
  "newProjectRoot": "projects",
  "projects": {
    "CouchFactoryConsole": {
      "root": "",
      "sourceRoot": "src",
      "projectType": "application",
      "prefix": "eks",
      "schematics": {
        "@schematics/angular:component": {
          "styleext": "less"
        }
      },
      "architect": {
        "build": {
          "builder": "@angular-devkit/build-angular:browser",
          "options": {
            "outputPath": "dist/CouchFactoryConsole",
            "index": "src/index.html",
            "main": "src/main.ts",
            "polyfills": "src/polyfills.ts",
            "tsConfig": "src/tsconfig.app.json",
            "assets": [
              "src/favicon.ico",
              "src/assets",
              {
                "glob": "**/*",
                "input": "./node_modules/@ant-design/icons-angular/src/inline-svg/",
                "output": "/assets/"
              }
            ],
            "styles": [
              "src/styles/main.scss",
              "src/styles/main.less"
            ],
            "scripts": [],
            "stylePreprocessorOptions": {
              "includePaths": [
                "node_modules",
                "src/styles/"
              ]
            }
          },
          "configurations": {
            "production": {
              "fileReplacements": [
                {
                  "replace": "src/environments/environment.ts",
                  "with": "src/environments/environment.prod.ts"
                }
              ],
              "optimization": true,
              "outputHashing": "all",
              "sourceMap": false,
              "extractCss": true,
              "namedChunks": false,
              "aot": true,
              "extractLicenses": true,
              "vendorChunk": false,
              "buildOptimizer": true,
              "budgets": [
                {
                  "type": "initial",
                  "maximumWarning": "2mb",
                  "maximumError": "5mb"
                }
              ]
            }
          }
        },
        "serve": {
          "builder": "@angular-devkit/build-angular:dev-server",
          "options": {
            "browserTarget": "CouchFactoryConsole:build"
          },
          "configurations": {
            "production": {
              "browserTarget": "CouchFactoryConsole:build:production"
            }
          }
        },
        "extract-i18n": {
          "builder": "@angular-devkit/build-angular:extract-i18n",
          "options": {
            "browserTarget": "CouchFactoryConsole:build"
          }
        },
        "test": {
          "builder": "@angular-devkit/build-angular:karma",
          "options": {
            "main": "src/test.ts",
            "polyfills": "src/polyfills.ts",
            "tsConfig": "src/tsconfig.spec.json",
            "karmaConfig": "src/karma.conf.js",
            "styles": [
              "src/styles/main.scss",
              "src/styles/main.less"
            ],
            "scripts": [],
            "stylePreprocessorOptions": {
              "includePaths": [
                "node_modules",
                "src/styles/"
              ]
            },
            "assets": [
              "src/favicon.ico",
              "src/assets"
            ]
          }
        },
        "lint": {
          "builder": "@angular-devkit/build-angular:tslint",
          "options": {
            "tsConfig": [
              "src/tsconfig.app.json",
              "src/tsconfig.spec.json"
            ],
            "exclude": [
              "**/node_modules/**"
            ]
          }
        }
      }
    }
  },
  "defaultProject": "CouchFactoryConsole"
}`

Maybe the dependency has not been imported in the bundle?

Thanks

**Comment by MurhafSousli** [comment]
You have to install the package manually `npm i @juggle/resize-observer`

**Comment by demkalkov** [comment]
Can't you just add this dependency to package.json? This is definitely a dependency of ngx-scrollbar, so why it is not there?

**Comment by MurhafSousli** [comment]
@demkalkov It is added in the peer dependency https://github.com/MurhafSousli/ngx-scrollbar/blob/master/projects/ngx-scrollbar/package.json, is there a way to get it installed out of the box?

**Comment by ajeiie120120** [comment]
> @demkalkov It is added in the peer dependencies https://github.com/MurhafSousli/ngx-scrollbar/blob/master/projects/ngx-scrollbar/package.json, is there a way to get it installed out of the box?

Sure, just put it in the dependencies instead, npm will do the work

**Comment by MurhafSousli** [comment]
@ajeiie120120 Great will try that in the next update
