### ISSUE TITLE
Reached events not working with AOT

### ISSUE THREAD

**Issue by nilsmehlhorn** [MurhafSousli/ngx-scrollbar#187]
#### Reproduction

I don't think you can reproduce it on StackBlitz as it's working fine during serve. But you can see it on the example page: https://ngx-scrollbar.netlify.com/

The chips don't light up when scrolling to top or bottom. You can also reproduce it by serving with prod settings:
```
"serve": {
  "builder": "@angular-devkit/build-angular:dev-server",
  "options": {
    "browserTarget": "app:build"
  },
  "configurations": {
    "prod": {
      "optimization": true,
      "sourceMap": true,
      "vendorSourceMap": true,
      "aot": true,
      "vendorChunk": false
    }
  }
}
```
 
#### Expected Behavior

The events should fire just like they do during development serve.

#### Actual Behavior

The reached events - especially the one for reaching bottom - doesn't fire with production builds.

#### Environment

- Angular: 8.2.3
- ngx-scrollbar: 5.0.1
- Browser(s): Chrome, Firefox
- Operating System (e.g. Windows, macOS, Ubuntu): Ubuntu

**Comment by MurhafSousli** [comment]
This was caused by class inheritance, found the answer here https://github.com/angular/angular/issues/6781
