### ISSUE TITLE
How to get the event when scroll bar is show.

### ISSUE THREAD

**Issue by anary** [MurhafSousli/ngx-scrollbar#188]
#### What are you trying to do?

I set the scrollbar show when the content is bigger, otherwise the scrollbar will not show.

#### What troubleshooting steps have you tried?
I tried to listen to the event 

this.scrollbarRef.scrollable.elementScrolled().pipe(
      map((e: any) => {})

but this is not triggered when the scrollbar is coming from [not shown] to [shown].

My question is:

How should I do to get the event when the scroll bar is changed from notshown to shown?

Thanks for help!

  
#### Environment

- Angular:
- ngx-scrollbar:
- Browser(s):
- Operating System browser

**Comment by MurhafSousli** [comment]
First the version you are using is outdated, upgrade to the latest version and [check the docs](https://github.com/MurhafSousli/ngx-scrollbar/wiki).
Here is example of listening to the scroll event https://github.com/MurhafSousli/ngx-scrollbar/wiki/scroll-event
