### ISSUE TITLE
Mention incompatibility with IE11

### ISSUE THREAD

**Issue by Robouste** [MurhafSousli/ngx-scrollbar#196]
I've downloaded, installed and configured this plugin only because IE11 scrollbar cannot be styled properly.

After seeing it fails, I came here, searched through the issue and found out IE compatibility was not planned.

It would be nice to mention it in the home page of this git, this way, next people won't lose their time like I did

**Comment by MurhafSousli** [comment]
Yea that's a good idea, I will add a note at the wiki
