### ISSUE TITLE
Cant resolve @juggle/resize-observer

### ISSUE THREAD

**Issue by IsaacSomething** [MurhafSousli/ngx-scrollbar#197]
After installing the latest release i get the error
````
[ng] ERROR in ./node_modules/ngx-scrollbar/fesm5/ngx-scrollbar.js
[ng] Module not found: Error: Can't resolve '@juggle/resize-observer' in 'D:\[foobar]\node_modules\ngx-scrollbar\fesm5'
````

This is in a project using Angular 8 and ionic 4.8

**Comment by ruizmarc** [comment]
I think is a duplicated issue: https://github.com/MurhafSousli/ngx-scrollbar/issues/185

**Comment by IsaacSomething** [comment]
Yip .. thank you

**Comment by MurhafSousli** [comment]
In v6 you don't need to install `@juggle/resize-observer` anymore
