### ISSUE TITLE
Scrollbar appears even if there is no need.

### ISSUE THREAD

**Issue by ajeiie120120** [MurhafSousli/ngx-scrollbar#198]
#### Issue

I'm facing a weird problem with ant design tables.
When i put inside the `<ng-scrollbar>` an ant design table for some reason the scrollbar appears even if there's no need .
I've prepared two identical examples with the version 4 and 5 of the library (maybe for a stackblitz error in the v4 example the styled scrollbar does not appear, but the problem is visible).

Does anyone have any clue?

#### Reproduction

Just open this two stackblitz:

- [ngx-scrollbar v.4.2.0 example](https://stackblitz.com/edit/angular-xtb4gw)

- [ngx-scrollbar v.5.0.1 example](https://stackblitz.com/edit/angular-w1jdsm)

  
#### Environment

- Angular 8
- ngx-scrollbar: v4.2.0 and v5.0.1
- Chrome
- Windows

**Comment by MurhafSousli** [comment]
I think there is an unnecessary `min-height: 100%` on the content wrapper which is causing this behavior, it only appeared with your example

Unset the `min-height` to fix it

```css
.ng-scroll-content {
   min-height: unset !important;
}
```

**Comment by ajeiie120120** [comment]
Thanks a lot, that has solved the issue.
