### ISSUE TITLE
Migration Guide 'appearance' spelling issue

### ISSUE THREAD

**Issue by IsaacSomething** [MurhafSousli/ngx-scrollbar#199]
For the migration guide the section
[1. NgScrollbar inputs](https://github.com/MurhafSousli/ngx-scrollbar/wiki/migration-guide#1-ngscrollbar-inputs)

There is a spelling error for `[appearence]` it should be `[appearance]`

i know this is very minor, but just in case someone copy and pastes from the guide (like i did)

**Comment by MurhafSousli** [comment]
Thanks for opening the issue, I fixed it
