### ISSUE TITLE
Property 'unsubscribe' of undefined.

### ISSUE THREAD

**Issue by kolesnikov-sml** [MurhafSousli/ngx-scrollbar#20]
Hello @MurhafSousli. I installed last package version 1.5.6. But this bug is present.
It happens when I quickly navigation between pages. 
I suspect that the method does not have time to unsubscribe (ngOnDestroy) and again subscribe. Or there is an call to non-existent properties.

e.g included 

![screen shot 03-13-18 at 10 36 am](https://user-images.githubusercontent.com/33318539/37333799-7eb49afe-26aa-11e8-863d-026b0c643bd9.PNG)

![screen shot 03-13-18 at 10 12 am](https://user-images.githubusercontent.com/33318539/37332479-20661dc2-26a7-11e8-9874-8fe4f176c010.PNG)

![screen shot 03-13-18 at 10 41 am](https://user-images.githubusercontent.com/33318539/37334029-18c32a3e-26ab-11e8-8f81-95d4e540df19.PNG)

### Versions
Angular CLI: 1.5.4
Node: 6.10.3
OS: Windows 10
Angular: 5.0.3
Typescript: 2.4.2
NPM: 5.6.0
Node.js: 6.10.3

**Comment by MurhafSousli** [comment]
Hi @kolesnikov-sml can you reproduce it?

**Comment by kolesnikov-sml** [comment]
I tried reproduce and discovered that my code running in constructor. I implemented OnInit interface and moved my code to ngOnInit function. It solved my problem. Thank you for the answer. 
p.s
So if someone has this problem try the solution above.
