### ISSUE TITLE
Scrolling with the mouse wheel does not work correctly

### ISSUE THREAD

**Issue by paradoxm** [MurhafSousli/ngx-scrollbar#200]
**Reproduction**

Use integration with cdk virtual scroll

**Steps to reproduce:**

Try to scroll the mouse wheel a bit in small steps.

![Peek 2019-09-03 15-38](https://user-images.githubusercontent.com/12410438/64167047-d6a81500-ce61-11e9-95d7-a2faec8b4a17.gif)

**Expected Behavior**
Scroll down

**Actual Behavior**
It doesn't scroll. Content is jumping

Environment
Angular: 8.0.3
ngx-scrollbar: 5.0.2

**Comment by MurhafSousli** [comment]
I am aware of this, I think it has to do with the styling applied to that specific component, I spent a lot of time debugging it but couldn't figure out what is wrong with it.

Anyway this is only happening in the demo, but it works everywhere else, try it in the stackblitz https://stackblitz.com/edit/ngx-scrollbar

If you figure out what is causing that behavior in the demo please report it.. for now I am closing this..
