### ISSUE TITLE
Scrollbar does not work in mobile device

### ISSUE THREAD

**Issue by anary** [MurhafSousli/ngx-scrollbar#215]
#### Feature Description

On mobile devices, scroll bar scrolling does not work. 

#### Use Case

Is any way to make the scroll enable on mobile device? Current, the only way to scroll is draging the content, it will be good if the scroll bar has the option to work as well.

Thanks

**Comment by anary** [comment]
Thanks! I will check that out.
________________________________

**Comment by MurhafSousli** [comment]
The scrollbars are not expected to be clicked or dragged on mobile, this is by design.
