### ISSUE TITLE
Add feature: 2 options to detect pointer events

### ISSUE THREAD

**Issue by volser** [MurhafSousli/ngx-scrollbar#216]
this line https://github.com/MurhafSousli/ngx-scrollbar/blob/master/projects/ngx-scrollbar/src/lib/classes/scrollbar-ref.ts#L185

causes to Recalculate Style while moving mouse. For big documents it's not good.
You can check it in Chrome (Performance)

Why do not use `mouseenter ` and `mouseleave` events instead (Or subscribe to `mousemove` event only after `mouseenter`)?

![image](https://user-images.githubusercontent.com/10529385/64869219-9b6bca00-d649-11e9-8c2b-ecc28169d7f2.png)

![image](https://user-images.githubusercontent.com/10529385/64869269-b8a09880-d649-11e9-879e-f65bf4a64d60.png)

**Comment by MurhafSousli** [comment]
Thanks for opening this up! I will fix it asap

**Comment by MurhafSousli** [comment]
The scroll events it turned off for the scrollbar event in CSS using `pointer-events: none`
Therefore we cannot detect if the mouse is over the scrollbar straight away, instead, we need to check that detect if the mouse within scrollbar range manually using `trackElement.getBoundingClientRect()`

**Comment by MurhafSousli** [comment]
I test it out in chrome but couldn't get the same result, the performance seems fine! can you elaborate on how to reproduce the performance leak?

**Comment by qaxqaxqax** [comment]
Not sure if it is related with this ticket but...
I store elements in scroll view that are building calculations on mousemove. Could I ask what is the reason to stop the propagation inside the scroll area?

**Comment by MurhafSousli** [comment]
@qaxqaxqax because maybe you have nested scrollbars, wouldn't that do the calculation twice?

**Comment by qaxqaxqax** [comment]
@MurhafSousli in this case this should be an optional input of the scrollbar. For example if someone wraps his page with ngx scrollbar now he loses mousemove event on the whole page and it's content.

**Comment by volser** [comment]
I have complex layout on full page

**Comment by MurhafSousli** [comment]
Try `<ng-scrollbar [pointerEventsMethod]="'scrollbar'">` to use native click events instead of viewport events
