### ISSUE TITLE
Scrollbar doesn't work properly when ivy is enabled 

### ISSUE THREAD

**Issue by nikola-katic** [MurhafSousli/ngx-scrollbar#217]
#### Reproduction
After enabling angular ivy, content inside of ng-scrollbar container disappear and scroll becomes immovable like in PRT_SC_2.png. It compiles correctly but doesn't work properly on browsers.    

Steps to reproduce:
1. Enable angular ivy 
 
#### Expected Behavior
The text should appear like on PRT_SCT_1 and scroll should be able to move.

#### Actual Behavior
The content inside of ng-scrollbar container disappear and scroll becomes immovable like in PRT_SC_2.jpeg. This behavior happens in Chrome, on Mozilla scrollbar have double bars, one near other PRT_SCR_3.png. 

#### Environment

- Angular: 8.0.3.
- ngx-scrollbar: 6.0.0
- Browser(s): Chrome, Mozilla
- Operating System (e.g. Windows, macOS, Ubuntu): 
Linux Mint

![PRT_SCR_1](https://user-images.githubusercontent.com/54700856/64912412-21157580-d72f-11e9-8948-3e5f01338acd.png)
![PRT_SCR_2](https://user-images.githubusercontent.com/54700856/64912413-24106600-d72f-11e9-8886-8227c4a9080a.png)
![PRT_SCR_3](https://user-images.githubusercontent.com/54700856/64912414-2672c000-d72f-11e9-9e4d-bf92a185e750.png)

**Comment by MurhafSousli** [comment]
Can you add a reproduction repo?

**Comment by nikola-katic** [comment]
Hello, you can take reproduced bug here: https://github.com/nikola-katic/ngx-scroll-ivy-bug

**Comment by MurhafSousli** [comment]
You pushed `node_modules` into your github repo? ARE YOU SERIOUS?
This is a very newbie mistake, I cannot clone it your repo.

Now does this happen when ivy enabled only or when ivy is disabled too?

**Comment by nikola-katic** [comment]
Sorry, my bad that isn't ivy. I always forget that angular put everything in sub-folder when creating a new project. When I replaced it to the root folder of repository git recognized node_modules like change.

**Comment by nikola-katic** [comment]
Everything should work now.

**Comment by MurhafSousli** [comment]
But you didn't tell me, is this issue only with ivy or also without ivy?

**Comment by nikola-katic** [comment]
Only with ivy.

**Comment by nikola-katic** [comment]
Everything works fine when ivy disabled.

**Comment by nikola-katic** [comment]
Everything works fine when ivy is disabled.

**Comment by MurhafSousli** [comment]
Ok, after investigating the issue, it turned out that it is related to https://github.com/angular/angular/issues/26436#issuecomment-431252708

There is a problem with the async pipe and ivy, but the error doesn't show when using the library.

As IgorMinar mentioned

> in general, there are still too many failing tests for us to resolve before we are ready to accept ivy related issues, so I'm going to close this one.

IVY isn't ready yet for production so I am going to close this as it is related to this package.

If you still want to use IVY however, there is a workaround, set the CSS variable manually
```ts
@ViewChild(NgScrollbar, { static: true }) scrollbarRef: NgScrollbar;

ngAfterViewInit() {
  this.scrollbarRef.nativeScrollbarSizeFactory.nativeScrollbarSize.subscribe((nativeScrollbarSize: number) => {
    document.body.style.setProperty('--native-scrollbar-size', `-${nativeScrollbarSize}px`);
  });
}
```

**Comment by ruizmarc** [comment]
Hi! 

The workaround works great, but now Angular 9 with IVY has been released as stable, and without the workaround, ngx-scrollbar is not showing the content. 

Should this issue be reopened?

**Comment by MurhafSousli** [comment]
It is already fixed, waiting for a release. stay tuned
