### ISSUE TITLE
Rename disabled attribute in scrollbar-wrapper

### ISSUE THREAD

**Issue by cluetjen** [MurhafSousli/ngx-scrollbar#218]
#### Reproduction

Component renders a disabled attribute in scrollbar wrapper div. This is not valid and causes problems with common css selectors. (Here: Kendo angular ui lib)

DOM:

`<div _ngcontent-boa-c1="" class="ng-scrollbar-wrapper" position="native" track="all" appearance="compact" visibility="native" disabled="false" dir="ltr" verticalused="true" horizontalused="false" isverticallyscrollable="true" ishorizontallyscrollable="false" verticalhovered="false" verticaldragging="true">`

Problematic css selector example:
`[disabled] .my-button { … }`

Steps to reproduce:
1. Open any page containing ngx-scrollbar and check dom
 
#### Expected Behavior

While one can argue, that CSS selectors like my example are not perfect, `<div disabled="false">` is still invalid HTML. I think it would make thinks easier, if there wouldn't be a 'disabled' attribute at all to prevent such CSS problems.

#### Actual Behavior

'disabled' attribute makes CSS selectors like `[disabled] button { pointer-events: none; }` match and breaks content.

#### Environment

- Angular: 8.2
- ngx-scrollbar: 6.0.0
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Win

**Comment by MurhafSousli** [comment]
Thanks for reporting! I think we can change that

**Comment by MurhafSousli** [comment]
Please try v7 beta and let me know if you still have an issue!

**Comment by cluetjen** [comment]
Tested with 7.0.0-beta.0. Works perfectly. Thanks!
