### ISSUE TITLE
Virtual scroll

### ISSUE THREAD

**Issue by kolesnikov-sml** [MurhafSousli/ngx-scrollbar#22]
@MurhafSousli Hello. You have a good library. I have a question: how to customize the scrollbar that like [this](https://github.com/DineroRegnskab/ngx-virtual-scroll). I need to apply virtual scroll. Do you have ideas? 
Thanks for the answer.

Regards, 
Roman.

**Comment by MurhafSousli** [comment]
@kolesnikov-sml Thanks!
This plugin does not change the default scrolling behavior, so I expect it to work with any virtual scroll plugin, but I never tried it with one.

**Comment by dhilt** [comment]
Hey! I've just integrated ngx-scrollbar with ngx-ui-scroll that implements virtual scrolling: https://stackblitz.com/edit/angular-aba8se
