### ISSUE TITLE
Bug using CDK Virtual Scroll 

### ISSUE THREAD

**Issue by Expometals** [MurhafSousli/ngx-scrollbar#233]
#### Reproduction
https://ngx-scrollbar.netlify.com/

Steps to reproduce:
1. go to CDK Virtual Scroll Example 
2. scroll until number 7 
 
 
#### Expected Behavior

What behavior were you expecting to see?
see the number 7 

#### Actual Behavior

What behavior did you actually see?

It scroll back to number 3

#### Environment

- Angular:
- ngx-scrollbar:
- Browser(s):
- Operating System (e.g. Windows, macOS, Ubuntu):

**Comment by MurhafSousli** [comment]
I am aware of this, it is happening only in the demo for some reason maybe related to CSS, but it is working properly as shown in the [stackblitz](https://stackblitz.com/edit/ngx-scrollbar)

**Comment by Expometals** [comment]
Seems to be due to this line of code, (in case of vertical scroll):
isVerticallyScrollable = this.viewport.scrollHeight > this.viewport.clientHeight;

https://github.com/MurhafSousli/ngx-scrollbar/blob/master/projects/ngx-scrollbar/src/lib/ng-scrollbar.ts
line 140

**Comment by MurhafSousli** [comment]
How come! do you know why is that causing this issue?

**Comment by Expometals** [comment]
I will try to find out.

**Comment by manzonif** [comment]
I created a new [simple angular app](https://github.com/manzonif/cdk-virtual-scroll-test), without any particular css rule, to reproduce the issue.

I don't know why it works in the stackblitz.

Now I will investigate more deeply.

P.S. Sorry for the username change.

**Comment by manzonif** [comment]
I tried this code:
```typescript
@Component({
  selector: 'app-root',
  template: '
  <cdk-virtual-scroll-viewport itemSize="50" minBufferPx="200" maxBufferPx="400"
  class="example-viewport">
  <div *cdkVirtualFor="let item of items" class="example-item">{{item}}</div>
  </cdk-virtual-scroll-viewport>',
  styleUrls: ['./app.component.scss']
})
export class AppComponent implements AfterViewChecked {
  items = Array.from({ length: 100000 }).map((_, i) => `Item #${i}`);
  title = 'cdk-virtual-scroll-test';

  constructor(
    public elementRef: ElementRef,
  ) { }

  ngAfterViewChecked() {
    const x = this.elementRef.nativeElement.scrollTop;
    console.log(x);
  }
}

```

without scrollbar, and I got the same issue.
So, unless there is a solid remedy, it could be considered a cdk-virtual-scroll bug.

**Comment by MurhafSousli** [comment]
Could be! anyway I am gonna close this, if you find out, please let me know

**Comment by manzonif** [comment]
Waiting for merge. 

[PR](https://github.com/angular/components/pull/17727)

**Comment by MurhafSousli** [comment]
Great! I've been wondering for a long time what was causing it, I had a feeling it was a bug in the CDK https://github.com/angular/components/pull/17727
