### ISSUE TITLE
Scrollbar breaks when loading on mobile

### ISSUE THREAD

**Issue by BovineEnthusiast** [MurhafSousli/ngx-scrollbar#236]
#### Reproduction

Steps to reproduce:
1. Load (not resize to) https://ngx-scrollbar.stackblitz.io/#/lazy-test on mobile (Chrome dev tool emulator is OK to use)
2. Click on "Basic"
3. You'll see `TypeError: Cannot read property 'complete' of undefined` in the console and the page breaks

If it matters, in my app it breaks right away on load rather than when I navigate, but the error is exactly the same.

![ezgif com-video-to-gif (2)](https://user-images.githubusercontent.com/8148243/68437698-85c0df80-0176-11ea-98bf-d76bd8815118.gif)

#### Environment

From the stackblitz: 
- Angular: `^8.2.3`
- ngx-scrollbar: `^7.0.0`
- Browser(s): Chrome. I haven't noticed this issue in desktop Safari when squeezing the viewport
- Operating System (e.g. Windows, macOS, Ubuntu): MacOS, iOS

**Comment by MurhafSousli** [comment]
Thanks for reporting!

**Comment by MurhafSousli** [comment]
Fixed in 7.0.1

**Comment by BovineEnthusiast** [comment]
Wow that was fast, thank you!
