### ISSUE TITLE
Compatibility Indications

### ISSUE THREAD

**Issue by FarizF** [MurhafSousli/ngx-scrollbar#240]
Hi Murhaf!

I'm looking to use your scrollbar package in our Angular 6 project, but (as expected) I seem to have some problems with using the latest version of your package. I didn't find any reference in your documentation regarding Angular version compatibility. Might be a nice addition. **Should your 7.0.x version work on Angular 6? If not, which version of your package is compatible with said Angular version?**

Might not be the right issue section for it, probably not even related to compatibility but rather a leftover file reference; I'm currently getting the following error when I try to run 7.0.1 on Angular 6:

```
ERROR in ./node_modules/ngx-scrollbar/fesm5/ngx-scrollbar.js
Module not found: Error: Can't resolve 'ngx-scrollbar/smooth-scroll' in 'C:\work\olbico-webapp\node_modules\ngx-scrollbar\fesm5'
 @ ./node_modules/ngx-scrollbar/fesm5/ngx-scrollbar.js 6:0-86 986:16-35 2964:24-42
 @ ./demo/app/ng/ng-examples.module.ts
 @ ./demo/app/app.routes.module.ts
 @ ./demo/app/app.module.ts
 @ ./demo/boot.browser.ts
 @ multi (webpack)-dev-server/client?http://localhost:8088 (webpack)/hot/dev-server.js ./demo/boot.browser.ts ./src/js/olbico.js ./src/sass/screen.scss ./src/icons/build-templates/olbico-icons.font.js
```

**Comment by MurhafSousli** [comment]
Hi @FarizF, For angular < 8 use v4.2.0. I added this info to the docs
