### ISSUE TITLE
Cannot read property 'duration' of undefined

### ISSUE THREAD

**Issue by GitHubish** [MurhafSousli/ngx-scrollbar#246]
When I use the "scrollToElement" method I have an error that occurs. If I set the duration to 0 it in scroll not.

`this.scrollRef.scrollToElement('#' + itemId);`

#### Environment

- Angular: 8.2.3
- ngx-scrollbar: 7.0.2
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Windows 10

Thanks

**Comment by MurhafSousli** [comment]
Please add a stackblitz repro

**Comment by GitHubish** [comment]
Here is a stackblitz that reproduces the error I have: 

https://stackblitz.com/edit/ngx-scrollbar-ghstnc?file=src/app/scroll-event/scroll-event/scroll-event.component.ts

**Comment by MurhafSousli** [comment]
@GitHubish You added the an element with the id test `<span id="test">` but it was stripped off because you didn't sanitize the innerHTML value.

Here it is working after using the sanitizer, [fixed stackblitz](https://stackblitz.com/edit/ngx-scrollbar-3gfllc?file=src/app/scroll-event/scroll-event/scroll-event.component.ts)

**Comment by GitHubish** [comment]
If you delete the options of the method we have the same problem. This means that the "duration" parameters are mandatory. 

this.scrollbarRef.scrollToElement("#test"**, { duration: 0, top: -100 }**); 

With duration it works. Did I misunderstand the doc?

I had another problem the scrollbar was in a "if", so I didn't have access to it with the "ViewChild" surprisingly. 

Thanks

**Comment by MurhafSousli** [comment]
You can use `this.scrollbarRef.scrollToElement("#test", {});` as well

The duration is not mandatory, but the options object seems to be required, will fix this in a future release.

If `<ng-scrollbar>` used with `*ngIf`, the `ViewChild` must use `static: false`

```ts
@ViewChild(NgScrollbar, { static: false }) scrollbarRef: NgScrollbar;

ngAfterViewInit() {
  if (this.scrollbarRef) {
   // do something
  }
}
```
