### ISSUE TITLE
Add clickable arrow buttons like the native scollbar

### ISSUE THREAD

**Issue by Danny4927** [MurhafSousli/ngx-scrollbar#252]
#### Feature Description

Scrollbar can be used via arrow buttons like the native scrollbar.

#### Use Case

For users who are used to the native scrollbar.

**Comment by MurhafSousli** [comment]
I think you can already use the arrow buttons to scroll like the native scrollbar!

**Comment by Danny4927** [comment]
Hey i was not clear enough, i meant this ones:

![grafik](https://user-images.githubusercontent.com/902430/70067442-938b4880-15ee-11ea-8dcc-9b1d8cc15d95.png)

**Comment by MurhafSousli** [comment]
I am not sure if this is something wanted by many, but adding this won't be straight forward, we have 2 different pointer-events methods

**Comment by Danny4927** [comment]
It doesn't have to be there for all usecases, just as an option to enable it. We would appreciate that 😄
