### ISSUE TITLE
Do not stop 'mousemove' from propagation

### ISSUE THREAD

**Issue by vasiltabakov** [MurhafSousli/ngx-scrollbar#255]
#### Reproduction

Use StackBlitz to reproduce your issue: 
https://stackblitz.com/edit/ngx-scrollbar-k8byjv

Steps to reproduce:
1. Create a mousemove listener
2. Do something useful on mouse move
3. Hover over the ng scrollbar component

**In the StackBlitz example:**
![2019-12-12_19-11-30](https://user-images.githubusercontent.com/1178309/70733586-4b1d0a80-1d13-11ea-8c0c-1fb4cb40ed97.gif)

 
#### Expected Behavior

`mousemove` should be propagated

#### Actual Behavior

the `mousemove` event is stopped from propagating

#### Environment

- Angular: 9.0.0-rc.6 (shouldn't matter)
- ngx-scrollbar: 7.1.0
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Windows

_**Note**_
I understand why this might be stopped from propagation (because there might be multiple listeners for the event within the scrollbar component - e.g. the thumb and the viewport - which might be a performance improvement). 

However in many cases parties outside of the component might be interested in the `mousemove` event. 

For example in our case there's a split view which can resize two areas with the mouse, but if one of the area stops the `mousemove` event propagation the 'resize' effect also stops. Here's a demonstration (the whole left area is ng-scrollbar), drag resizing to the right works, but to the left fails:
![2019-12-12_18-51-07](https://user-images.githubusercontent.com/1178309/70733821-be268100-1d13-11ea-8536-5e70b58870f3.gif)

**Comment by MurhafSousli** [comment]
Yes, it is caused by this line

https://github.com/MurhafSousli/ngx-scrollbar/blob/c25e385149d27df89b4f1f40c3382230b6ce326f/projects/ngx-scrollbar/src/lib/scroll-viewport.ts#L71

I added this to avoid detecting the pointer-events for the outer scrollbar component in case of **nested scrollbars components**, but it seems that we should not stop the propagation in your case.

On the bright side, you can use `<ng-scrollbar pointerEventsMethod="scrollbar">`

**Comment by vasiltabakov** [comment]
Thanks! 
This solution is more than enough (`pointerEventsMethod="scrollbar"`), keep up the great work!

**Comment by BovineEnthusiast** [comment]
This fixed the issue I had where ngx-dragula stopped working in desktop mode! 🎉
