### ISSUE TITLE
When dialog/modal is inside the <ng-scrollbar> tag, it encapsulates the modal

### ISSUE THREAD

**Issue by ospree-ui** [MurhafSousli/ngx-scrollbar#261]
#### Reproduction

Use StackBlitz to reproduce your issue: https://stackblitz.com/edit/ngx-scrollbar

Steps to reproduce:
1.  Put a modal content inside the ng-scrollbar tag. Open the modal
2. 
 
 
#### Expected Behavior

What behavior were you expecting to see?
The scrollbar should not interfere with modal/dialog display

#### Actual Behavior

What behavior did you actually see?
The modal/dialog background is encapsulated in the  ng-scrollbar container

#### Environment

- Angular:
- ngx-scrollbar:
- Browser(s):
- Operating System (e.g. Windows, macOS, Ubuntu):

**Comment by MurhafSousli** [comment]
Can you please reproduce the issue and add the link to the reproduction stackblitz?
