### ISSUE TITLE
ng2dragula

### ISSUE THREAD

**Issue by jm06487** [MurhafSousli/ngx-scrollbar#263]
Having issues with implementing this module with ng2dragula.  I'm not able to drag anything when the component is in the ng-scroll element.

**Comment by MurhafSousli** [comment]
please add a reproduction!

**Comment by jm06487** [comment]
In this example it moves once and then it stops. But in my project, you cant drag it at all. 
https://stackblitz.com/edit/ngx-scrollbar-btyeep

**Comment by jm06487** [comment]
#255 solved the issue.
