### ISSUE TITLE
Add support for @angular/material v9

### ISSUE THREAD

**Issue by danielprrazevedo** [MurhafSousli/ngx-scrollbar#264]
#### Feature Description

The @angular/cdk is incompatible with the latest version.
Update the dependencies to make the plugin compatible.

**Comment by MurhafSousli** [comment]
Will update with Angular 9 as soon as I can

**Comment by fabdeceglia** [comment]
are there any ETA for this?

**Comment by danielprrazevedo** [comment]
> Will update to Angular CDK 9 as soon as I can

@MurhafSousli  Thanks!
If there's anything I can help with, be sure to delegate

**Comment by MurhafSousli** [comment]
@danielprrazevedo Thanks!
I mistakenly pushed directly to master thinking I was on another branch

Closed in https://github.com/MurhafSousli/ngx-scrollbar/commit/a97f69f0135f7612a69334667cc9d185327c22a9

**Comment by ClemannD** [comment]
@MurhafSousli 

Thank you fro the quick work! However, not seeing a new version published to NPM

**Comment by vpetrusevici** [comment]
I'm sorry, but when will be release?

**Comment by MurhafSousli** [comment]
I just published a beta version

**Comment by vpetrusevici** [comment]
@MurhafSousli I created Issue #266 for last version
