### ISSUE TITLE
Scrollbar makes content too wide when it appears in v. 7.2.0

### ISSUE THREAD

**Issue by vpetrusevici** [MurhafSousli/ngx-scrollbar#266]
#### Reproduction
It's also reproduced on example https://stackblitz.com/edit/ngx-scrollbar

Steps to reproduce:
1. Just open scrollbar
 
 
#### Expected Behavior

What behavior were you expecting to see?
![image](https://user-images.githubusercontent.com/40790510/74632665-8bac6080-5168-11ea-8237-81e4f039f2f8.png)

#### Actual Behavior

![image](https://user-images.githubusercontent.com/40790510/74632626-76cfcd00-5168-11ea-9194-be1b3a66e576.png)

#### Environment

- Angular: 9
- ngx-scrollbar: 7.2.0
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Windows 10

**Comment by MurhafSousli** [comment]
This is by design! the content should fill the width of the viewport in compact mode, which is the default (`appearance="compact"`).

If you don't want the content to overlap with the scrollbar, then use `appearance="standard"`

**Comment by vpetrusevici** [comment]
I may not have given the most explicit example.  The problem is that the content does not just fill the space, but even goes beyond the scope.  By design, as I understand it, only the native scroll should hide

**Comment by vpetrusevici** [comment]
the content moves when the scroll appears, although in compact mode it should not

**Comment by vpetrusevici** [comment]
![image](https://user-images.githubusercontent.com/40790510/74660230-69cdd080-519e-11ea-8b87-969e394c39c3.png)
![image](https://user-images.githubusercontent.com/40790510/74660260-76eabf80-519e-11ea-850e-290e40712461.png)

**Comment by vpetrusevici** [comment]
link to reproduce https://ngx-scrollbar-6yqkz4.stackblitz.io

**Comment by MurhafSousli** [comment]
Is this only happening in the recent version (7.2.0)?

Can you try to apply the following styles and check if it fixes the issue

```scss
::ng-deep {
  .ng-native-scrollbar-hider {
    scrollbar-width: unset !important;
    -ms-overflow-style: unset  !important;
    &::-webkit-scrollbar {
      display: unset  !important;
    }
  }
}
```

**Comment by vpetrusevici** [comment]
Yes it was after update to 7.2.0
Ok. I'll try

**Comment by vpetrusevici** [comment]
Yes. It fixes the issue. Thank you!

**Comment by vpetrusevici** [comment]
I also removed scrollbar-width: unset !important; from fix. Because of this, the width of scroll is not correctly determined on Firefox when I use scrollbar-width: thin; for other blocks

**Comment by vpetrusevici** [comment]
Looks good. Thank you for your great work!

**Comment by MurhafSousli** [comment]
@vpetrusevici welcome :)

**Comment by habundes** [comment]
still facing this issue when building package with --aot
