### ISSUE TITLE
Server side rendering runtime error

### ISSUE THREAD

**Issue by Nekronik** [MurhafSousli/ngx-scrollbar#267]
#### Reproduction

I am getting an error when running with server side rendering on version 7.2.0. It was fine under 7.1.0 even on angular 9 with the css variable workarround.

```
TypeError: box.getBoundingClientRect is not a function
    at NativeScrollbarSizeFactory.getNativeScrollbarSize
```

I'm not sure how to provide a stackblitz reproduction about this one.

I noticed you moved where the function is called but not the logic of this function call. Maybe it is done too early now, I'm not sure.

Maybe a special case for when not running in browser should be created.

#### Expected Behavior

No error

#### Actual Behavior

An error is thrown

#### Environment

- Angular: 9.0.0
- ngx-scrollbar: 7.2.0
- Browser(s): Google Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): KDE Neon (Ubuntu)

**Comment by marcoripa96** [comment]
I'm getting the same error with angular 9.1.

**Comment by MurhafSousli** [comment]
Thanks for reporting!

**Comment by manzonif** [comment]
same error in  el.nativeElement.style.setProperty:
`        this._subscriber = hideNativeScrollbar.scrollbarSize.subscribe((size) => {
            el.nativeElement.style.setProperty('--native-scrollbar-size', `-${size}px`);
        });`
