### ISSUE TITLE
Not working in angular 7

### ISSUE THREAD

**Issue by eldhose-cavli** [MurhafSousli/ngx-scrollbar#274]
`ERROR in node_modules/@angular/cdk/bidi/dir.d.ts(26,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/@angular/cdk/bidi/dir.d.ts(27,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/@angular/cdk/bidi/dir.d.ts(29,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/@angular/cdk/collections/selection-model.d.ts(24,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/@angular/cdk/scrolling/fixed-size-virtual-scroll.d.ts(75,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/@angular/cdk/scrolling/fixed-size-virtual-scroll.d.ts(76,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/@angular/cdk/scrolling/fixed-size-virtual-scroll.d.ts(82,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/@angular/cdk/scrolling/fixed-size-virtual-scroll.d.ts(83,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/@angular/cdk/scrolling/fixed-size-virtual-scroll.d.ts(88,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/@angular/cdk/scrolling/fixed-size-virtual-scroll.d.ts(89,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/@angular/cdk/scrolling/virtual-for-of.d.ts(49,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/@angular/cdk/scrolling/virtual-for-of.d.ts(50,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/@angular/cdk/scrolling/virtual-for-of.d.ts(56,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/@angular/cdk/scrolling/virtual-for-of.d.ts(57,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/@angular/cdk/scrolling/virtual-for-of.d.ts(60,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/@angular/cdk/scrolling/virtual-scroll-viewport.d.ts(27,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/@angular/cdk/scrolling/virtual-scroll-viewport.d.ts(28,9): error TS1086: An accessor cannot be declared in an ambient context.`

**Comment by vpetrusevici** [comment]
![image](https://user-images.githubusercontent.com/40790510/76335619-7eb10600-62fd-11ea-8828-d42b91bd180d.png)

**Comment by Navodya94** [comment]
@eldhose-cavli  Im having the same issue. were you able to find a solution for this? If so could you please help me on this? Thanks
