### ISSUE TITLE
ResizeObserver errors

### ISSUE THREAD

**Issue by Z6DAG** [MurhafSousli/ngx-scrollbar#275]
#### Reproduction

~~Use StackBlitz to reproduce your issue: https://stackblitz.com/edit/ngx-scrollbar~~
Cannot reproduce on StackBlitz, but please clone this [repo](https://github.com/Z6DAG/scrollbar-error).

Steps to reproduce:
1. Run project
2. Click 'test' link
 
 
#### Expected Behavior

No errors logged in console.

#### Actual Behavior

In index.html there is a hook on `window.onerror`. On every enter to test component which has scrollbar error with `ResizeObserver` is logged. It doesn't affect behavior of the app, but pollute logs as for example Microsoft AppInsights use this hook to get all errors logged.
This started to occur after update to Angular 9 and ngx-scrollbar 7.2.0.

In repro repo there is one error: `ResizeObserver loop limit exceeded`, but we also faced `ResizeObserver loop completed with undeliver`.

#### Environment

- Angular: 9.0
- ngx-scrollbar: 7.2.0
- Browser(s): Chrome 80
- Operating System (e.g. Windows, macOS, Ubuntu): Windows

**Comment by MurhafSousli** [comment]
That is probably happening only in your project

**Comment by zlatoroh** [comment]
I had similar problem.

After setting this:  ` [sensorDebounce]="1"`  the error stopped.
