### ISSUE TITLE
Angular 8 serve issue: 

### ISSUE THREAD

**Issue by IamTC** [MurhafSousli/ngx-scrollbar#276]
#### Error:

node_modules/ngx-scrollbar/lib/utils/resize-sensor.directive.d.ts:20:9 -  error TS1086: An accessor cannot be declared in an ambient context.

#### What are you trying to do?

Install and use NgxScrollbar in a new project

#### What troubleshooting steps have you tried?

Trying different 7.1.0 and 7.2.0 and the latest cdk and 8.1.4

#### Reproduction

Cannot reproduce in other projects. The other project I am working on is fine.

#### Environment

- Angular: 8.2.14
- ngx-scrollbar: 7.1.0
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Windows 10

[package.txt](https://github.com/MurhafSousli/ngx-scrollbar/files/4324823/package.txt)

**Comment by yehiasalam** [comment]
same here

**Comment by cyfrost** [comment]
Same issue, neither `ng serve` or `ng build` work because of typescript throwing a compile-time error as mentioned in OP. We're debating if upgrading to Angular 9 (also has typescript v3.8.3 as stack update) would fix this issue.

**Comment by MurhafSousli** [comment]
I cannot replicate this. and I think you should upgrade to Angular 9 and use the latest version  https://stackblitz.com/edit/ngx-scrollbar

**Comment by MurhafSousli** [comment]
Ok has to do with your typescript version.

https://stackoverflow.com/questions/58802463/types-sequelize-error-ts1086-an-accessor-cannot-be-declared-in-ambient-context/58804230#58804230
