### ISSUE TITLE
Can't bind to 'reachedOffset' since it isn't a known property of 'ng-scrollbar'

### ISSUE THREAD

**Issue by manthonyp** [MurhafSousli/ngx-scrollbar#279]
#### What are you trying to do?

Use **reachedOffset** input.

#### What troubleshooting steps have you tried?

Having error: Can't bind to 'reachedOffset' since it isn't a known property of 'ng-scrollbar'.
  
#### Environment

- Angular: 9.0
- ngx-scrollbar: 7.2.1-beta.0
- Browser(s): Chrome (latest)
- Operating System: Windows

**Comment by MurhafSousli** [comment]
```
import { NgScrollbarModule } from 'ngx-scrollbar';
import { NgScrollbarReachedModule } from 'ngx-scrollbar/reached-event';

@NgModule({
  imports: [
    NgScrollbarModule,
    NgScrollbarReachedModule
  ],
})
export class AppModule {
}
```

https://github.com/MurhafSousli/ngx-scrollbar/wiki/reached-events

**Comment by gregor-srdic** [comment]
@MurhafSousli this does not help, I am seeing the same issue but I've imported the NgScrollbarReachedModule
