### ISSUE TITLE
Initial Scroll Position

### ISSUE THREAD

**Issue by yehiasalam** [MurhafSousli/ngx-scrollbar#281]
#### What are you trying to do?
Well I'm creating a chat application, and im trying to make the initial position of the scrollbar to the bottom. I'm trying to make it works like Messenger or Whats app. My problems is when I use `	this.messages_list.scrollTo({ bottom: 0, duration: 0 });` there is always a quick repaint where I can see the top of the content for a fraction of a second and then it scrolls to the end of the content. How can overcome this? 

Thanks for your package btw, the 3rd scrollbar component and everything looks great now.
#### Environment

- Angular: 8.2
- ngx-scrollbar: 7.1.0
- Browser(s): Chrome/Firetofx
- Operating System (e.g. Windows, macOS, Ubuntu): Windows 10

**Comment by MurhafSousli** [comment]
Hi @yehiasalam thanks!

I tried using `scrollbarRef.scrollTo({ bottom: 0, duration: 0 });` and didn't notice a quick repaint you mentioned.

Check https://stackblitz.com/edit/ngx-scrollbar-gqrtix?file=src/app/scroll-event/scroll-event/scroll-event.component.ts

Anyway in case that method is not working for you, you can use the native element

```ts
scrollbarRef.viewport.nativeElement.scrollTop = 
  scrollbarRef.viewport.scrollHeight - scrollbarRef.viewport.clientHeight;
```

**Comment by sujeetjaiswara** [comment]
Same issue getting with angular material mat'tab

**Comment by sheikalthaf** [comment]
@MurhafSousli I want to restore scroll positions in material tab. But there is any way to do it?

**Comment by xylplm** [comment]
I also encountered the same problem, wanting the scrollbar to default to the bottom. If you want to make a chat tool, the default is at the bottom. After each addition, scroll to the bottom and it will flash briefly.

**Comment by MurhafSousli** [comment]
If someone can reproduce the issue in a stackblitz, then we can look into it.
