### ISSUE TITLE
Error on running ng-serve: node_modules/@angular/cdk/coercion/array.d.ts(10,60): error TS1005: ',' expected.

### ISSUE THREAD

**Issue by vladNVT** [MurhafSousli/ngx-scrollbar#284]
Hello,

I have angular 5.2.11 and angular-cli 1.7.4
I've installed the **ngx-scrollbar 4.2.0** version and **@angular/cdk version 9.2.0**

When I try to run ng-serve it gives me:

node_modules/@angular/cdk/coercion/array.d.ts(10,60): error TS1005: ',' expected.
node_modules/@angular/cdk/coercion/array.d.ts(10,61): error TS1005: ',' expected.
node_modules/@angular/cdk/coercion/array.d.ts(10,75): error TS1144: '{' or ';' expected.
node_modules/@angular/cdk/coercion/array.d.ts(10,77): error TS1011: An element access expression should take an argument.

How can I make it work ?

thanks!

**Comment by MurhafSousli** [comment]
angular cdk 9 is not compatible with angular 5.. you should update to latest version
