### ISSUE TITLE
scrollable property missing / undefined?

### ISSUE THREAD

**Issue by stephen-dirtcreative** [MurhafSousli/ngx-scrollbar#286]
#### What are you trying to do?
I am trying to get a reference to the CdkScrollable that the README_V4 suggests is available, in order to provide it to a CdkOverlay (so it can determine its positioning)

Following the README_V4 advice regarding accessing the scrollable property (under Options, Scroll functions).
```
...
@ViewChild(NgScrollbar)
private readonly scrollbarRef: NgScrollbar
...
public ngAfterViewInit (): void {
  const { scrollable } = this.scrollbarRef // scrollable is undefined
}
```

#### What troubleshooting steps have you tried?

According to the documentation this property should exist, and presumably would be a CdkScrollable instance. I've checked in the console to double-check that the property is not appearing, typescript flags the property as missing, and my initial dig into the source code is not turning it up anywhere, either.

#### Reproduction

https://stackblitz.com/edit/ngx-scrollbar

Steps to reproduce:
1. Use the existing stackblitz default and go to the scroll-event typescript file where a scrollbarRef is defined
2. Try and access the scrollable property, it's not there. Also, the example code is very different from what is in the README. Presumably this means the scrollable property has been replaced by this other functionality, but as someone still learning the CDK I'm not at all sure how to interface ngx-scrollbar with my overlay's positioning strategy without it.
  
#### Environment

- Angular: 9.1
- ngx-scrollbar: 7.2.0-beta1
- Browser(s): Chrome (latest stable)
- Operating System (e.g. Windows, macOS, Ubuntu): macOS

**Comment by MurhafSousli** [comment]
Hi @stephen-dirtcreative, documentations for v4 does not work for v7. I completely got rid of `CdkScrollable` long time ago. the wiki documentation does not have any missing properties as far as I know.

With the scrollable reference you can get the the `scrolled` stream and the `viewport` directive reference which can be useful for you to determine the position etc...
