### ISSUE TITLE
Horizontal Scrollbar not applied

### ISSUE THREAD

**Issue by meghansh36** [MurhafSousli/ngx-scrollbar#288]
I don't know if its a bug or i am using the library wrong but i am not able to apply horizontal scrollbars on my elements. I have also tried setting track value to 'all' and 'horizontal' but to no avail.

#### Expected Behavior

Ng Horizontal Scrollbar applied

#### Actual Behavior

Native browser scrollbar

#### Environment

- Angular: 9 
- ngx-scrollbar: 7.2.1 beta

**Comment by MurhafSousli** [comment]
This is not helpful, you need to add a reproduction stackblitz

**Comment by meghansh36** [comment]
I actually fixed the issue. My HTML structure was not right. Correcting it fixed the issue. Thanks
