### ISSUE TITLE
NG8002: Can't bind to 'reachedOffset' since it isn't a known property of 'ng-scrollbar'.

### ISSUE THREAD

**Issue by sasapesic** [MurhafSousli/ngx-scrollbar#292]
#### Reproduction
`{
  "name": "ang9",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "~10.0.0-rc.6",
    "@angular/cdk": "^9.2.4",
    "@angular/common": "~10.0.0-rc.6",
    "@angular/compiler": "~10.0.0-rc.6",
    "@angular/core": "~10.0.0-rc.6",
    "@angular/forms": "~10.0.0-rc.6",
    "@angular/platform-browser": "~10.0.0-rc.6",
    "@angular/platform-browser-dynamic": "~10.0.0-rc.6",
    "@angular/router": "~10.0.0-rc.6",
    "ngx-scrollbar": "^7.2.0",
    "rxjs": "~6.5.5",
    "tslib": "^2.0.0",
    "zone.js": "~0.10.3"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.1000.0-rc.5",
    "@angular/cli": "~10.0.0-rc.5",
    "@angular/compiler-cli": "~10.0.0-rc.6",
    "@types/node": "^12.11.1",
    "@types/jasmine": "~3.5.0",
    "@types/jasminewd2": "~2.0.3",
    "codelyzer": "^6.0.0-next.1",
    "jasmine-core": "~3.5.0",
    "jasmine-spec-reporter": "~5.0.0",
    "karma": "~5.0.0",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage-istanbul-reporter": "~3.0.2",
    "karma-jasmine": "~3.3.0",
    "karma-jasmine-html-reporter": "^1.5.0",
    "protractor": "~7.0.0",
    "ts-node": "~8.3.0",
    "tslint": "~6.1.0",
    "typescript": "~3.9.5"
  }
}
`

App module:

`@NgModule({
  declarations: [
    AppComponent
  ],
  imports: [
    BrowserModule,
    AppRoutingModule,
    NgScrollbarModule,
    NgScrollbarReachedModule
  ],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule { }`

Build error:
ERROR in src/app/app.component.html:9:51 - error NG8002: Can't bind to 'reachedOffset' since it isn't a known property of 'ng-scrollbar'.
1. If 'reachedOffset' is an Angular directive, then add 'CommonModule' to the '@NgModule.imports' of this component.
2. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component.

9 <ng-scrollbar (reachedBottom)="onBottomReached()" [reachedOffset]="50">
                                                    ~~~~~~~~~~~~~~~~~~~~

  src/app/app.component.ts:5:16
    5   templateUrl: './app.component.html',
                     ~~~~~~~~~~~~~~~~~~~~~~
    Error occurs in the template of component AppComponent.

Works fine until i add the [reachedOffset] directive.

**Comment by MurhafSousli** [comment]
A reproduction is a link were I can see it in action
