### ISSUE TITLE
gives me ERROR in node_modules/ngx-scrollbar/lib/ng-scrollbar.module.d.ts when i try to serve

### ISSUE THREAD

**Issue by AbdallahR99** [MurhafSousli/ngx-scrollbar#294]
I just installed the package by: npm i ngx-scrollbar @angular/cdk and i did import in the app module
and i got this Error after serve: 

>     ERROR in node_modules/ngx-scrollbar/lib/ng-scrollbar.module.d.ts:3:22 - error NG6002: Appears in the NgModule.imports of AppModule, but could not be resolved to an NgModule class.
>     
>     This likely means that the library (ngx-scrollbar) which declares NgScrollbarModule has not been processed correctly by ngcc, or is not compatible with Angular Ivy. Check if a newer version of the library is available, and update if so. Also consider checking with the library's authors to see if the library is expected to be compatible with Ivy.
>     
>     3 export declare class NgScrollbarModule {
>                            ~~~~~~~~~~~~~~~~~
>     

can help?

**Comment by MurhafSousli** [comment]
Please fill the issue template, include the version and a reproduction, it could caused by the project, try to remove _node_modules_ directory and reinstall `npm install`

**Comment by superman-lopez** [comment]
I ran into the same issue.  It was cause by the autoimport of the class in my module.  Auto import gave me:
```js
import { NgScrollbarModule } from 'ngx-scrollbar/lib/ng-scrollbar.module';
```
instead of the correct value:
```js
import { NgScrollbarModule } from 'ngx-scrollbar';
```
