### ISSUE TITLE
Unable to scroll via scrollbar indicator

### ISSUE THREAD

**Issue by hammadaries** [MurhafSousli/ngx-scrollbar#295]
Hi,
I am unable to scroll via scrollbar thumb/indicator when tested on a touch tablet. I am using the current release i.e. 7.2.3.
Even this StackBlitz example does not work on an Android tablet/phone.

[https://stackblitz.com/edit/ngx-scrollbar](url)

It was working fine with version 4.2.0

**Comment by MurhafSousli** [comment]
This is by design, it is meant to behave like original scrollbars. it only gets activated on desktop
