### ISSUE TITLE
Console error

### ISSUE THREAD

**Issue by beyondtheobservableuniverse** [MurhafSousli/ngx-scrollbar#298]
Hi

When body `overflow: hidden;` I get this error to console:

![image](https://user-images.githubusercontent.com/30147726/87944720-0e32a680-caa0-11ea-954f-1f3e7ed93beb.png)

The scrollbar works fine, but please fix this!

**Comment by MurhafSousli** [comment]
I can't do the reproduction step for you, you should add a reproduction link so I can look into the issue, I would suggest considering a wrapper to wrap the scrollbar component
