### ISSUE TITLE
Please add a @NgModule annotation

### ISSUE THREAD

**Issue by rknbgl** [MurhafSousli/ngx-scrollbar#30]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] question
```

### OS and Version?
Windows 10

### Versions
Angular CLI: 1.7.4
Node: 6.10.3
OS: win32 x64
Angular: 5.2.10
... animations, common, compiler, compiler-cli, core, forms
... http, platform-browser, platform-browser-dynamic
... platform-server, router

@angular/cdk: 5.2.5
@angular/cli: 1.7.4
@angular/material: 5.2.5
@angular-devkit/build-optimizer: 0.3.2
@angular-devkit/core: 0.3.2
@angular-devkit/schematics: 0.3.2
@ngtools/json-schema: 1.2.0
@ngtools/webpack: 1.10.2
@schematics/angular: 0.3.2
@schematics/package-update: 0.3.2
typescript: 2.4.2
webpack: 3.11.0

### Repro steps
$ npm install ngx-scrollbar@latest --save
$ ng build --prod --aot

### The log given by the failure
ERROR in : Unexpected value 'ScrollbarModule in {pat}/node_modules/ngx-scrollbar/lib/scrollbar.module.d.ts' imported by the module 'InboxModule in {path}/src/app/inbox/inbox.module.ts'. Please add a @NgModule annotation.

**Comment by MurhafSousli** [comment]
It is fixed in v2.0.1
