### ISSUE TITLE
Ngx-scrollbar auto scroll to top after detect change

### ISSUE THREAD

**Issue by daollobit** [MurhafSousli/ngx-scrollbar#301]
#### What are you trying to do?
I used ngx-scrollbar in 2 places. One in child component has problem. I set an interval in parent component, after fetch new data ngx-scollbar (in parent component) auto scroll to top.

#### What troubleshooting steps have you tried?
I try remove ngx-scrollbar in child component, then the problem is gone.

#### Reproduction
![ngx-scrollbar](https://user-images.githubusercontent.com/63795620/89603817-165a5680-d894-11ea-9050-31c36391a81b.png)
  
#### Environment
- Angular: 9.1.0
- ngx-scrollbar: 7.2.3
- Browser(s): Chrome 84.0.4147.105
- Operating System (e.g. Windows, macOS, Ubuntu): Windows 10

**Comment by MurhafSousli** [comment]
You need to add a reproduction if you want me to look into it
