### ISSUE TITLE
Cannot move scrollbar with mouse

### ISSUE THREAD

**Issue by kirilpetrov36** [MurhafSousli/ngx-scrollbar#305]
#### Reproduction

Steps to reproduce:
1. Click the scrollbar with cursor and hold
2. Trying to move it down
 
 
#### Expected Behavior

Expecting scrollbar to move down with cursor

#### Actual Behavior

Scrollbar don't move with cursor, it moves only with mouse wheel.

#### Environment

- Angular: 10.0.12
- ngx-scrollbar: "7.3.0"
- Browser: Chrome
- Operating System : Windows 10

**Comment by MurhafSousli** [comment]
It actually works! but if you are using it on small screen then it is mouse drag is disabled by design because it is considered mobile scrollbar
