### ISSUE TITLE
scrollbar should not scroll to top automatically, whenever i add new elements in the begininning of array.

### ISSUE THREAD

**Issue by shivamSharmaMWP** [MurhafSousli/ngx-scrollbar#306]
#### Reproduction

Use StackBlitz to reproduce your issue: https://stackblitz.com/edit/ngx-scrollbar

Steps to reproduce:
1. i have added simple array values into the list. 
2. whenever i unshift() some values into the list, it always scrolls to top.

 
#### Expected Behavior

What behavior were you expecting to see?
it should stay as it was before unshift() of items.

#### Actual Behavior

What behavior did you actually see?

#### Environment

- Angular: 10
- ngx-scrollbar: "^7.3.0", 
- Browser(s):
- Operating System (e.g. Windows, macOS, Ubuntu):

**Comment by MurhafSousli** [comment]
I think you forgot to fork the stacklblitz, save your changes and add your link so I can try it out

**Comment by shivamSharmaMWP** [comment]
hey @MurhafSousli 

please check the stackblitz link  https://stackblitz.com/edit/ngx-scrollbar-aaznw1
here i have added a component called conversation. which listens to scroll to top event. if it reaches top ( event scrollTop = 0), then i am unshifting elements to the array _masterList.
on my local machine array.push() works fine. means it doesn't scroll down to end. but array.unshift() always scroll to top. which i think should stay which it is before.

moreover i am not able to replicate on stackblitz because stackblitz is not even updating a simple variable value.  https://stackblitz.com/edit/refresh-g3smfb      i have created one issue on github  https://github.com/stackblitz/core/issues/1326, 

for adding a fix on my local machine. i  have used these 3 statements.

   // const deltaFromBottom = e.target.scrollHeight - e.target.scrollTop;
   // ..... adding entries into the array, then scrolling back to original location
   // e.target.scrollTop = e.target.scrollHeight - deltaFromBottom;

maybe you need to try this on your local machine, as my stackblitz account is not showing updated scrollbar elements at all.

**Comment by shivamSharmaMWP** [comment]
hi @MurhafSousli , please suggest your opinion.

**Comment by shivamSharmaMWP** [comment]
hey @MurhafSousli , please reply.

**Comment by MurhafSousli** [comment]
The way you explain your problem makes it over-complicated, it is unclear what you are asking for! 

If I understood you correctly, you want to scroll to bottom when new message is added? correct? then just say that instead of saying array unshift list...etc .. you describe your issue in simple english!

After you add your values, just use `this.scrollbarRef.scrollTo({ bottom: 0});`

here is a [fixed stackblitz](https://stackblitz.com/edit/ngx-scrollbar-zzaqxx?file=src%2Fapp%2Fconversation%2Fconversation.component.ts)

**Comment by shivamSharmaMWP** [comment]
hi @MurhafSousli ,

no, your understanding is incorrect.

here is the actual scenario: 
[ **whenever i add new elements in the beginning of the array ( i.e. prepending elements to the array / inserting elements at the 0th location ), the ngx-scrollbar is scrolling the top every time.** ]

Explanation : lets say i am scrolling to the top of the container and using infinite scroll concept, i am fetching more data from my db. then I prepend that new data to the top (because i want to see those previous data, correct) . then suddenly ngx-scrollbar scrolls to the topmost location of the container. which gives a sudden flickering scroll kind of experience. but actually i want to stay at that element only where i was earlier (i.e before reaching the top location).

Expectation : if i am currently scrolls to 0th element, and after adding 12 elements to the begnning, the previous 0th element will become 13th element, and scrollbar should stay at 13th element only. must not scroll to 0th element now.

or may be in short ( just think of any conversations application like whatsapp. whenever you scrolls to the top,  new elements are added but your actual scroll position stays as it. ) 


what i have added as a fix:  before adding new elements i calculating actual scrollheight from bottom, and after elements are added to the list, i again moves back to the original location.


just an info, whenever i am scrolling to bottom and i fetches new elements and insert them to the last of array, it doesn't scroll to bottom of the container. it stays as it. (like scrollbar size shrinks but scrollbar doesn't moves to the end) . which is working fine as expected. but above said thing is not working.



But few things i am not able to understand, i have written simple thing (unshift means inserting elements to the beginning of the array. and after unshifting elements it is scrolling to the top of the container. which is the issue)

moreover if you were not able to understand the issue, then you should have informed that in the beginning ( 19 days ! ) , and you have also replied now after 13 days !)

**Comment by shivamSharmaMWP** [comment]
hi @MurhafSousli ,

no, your understanding is incorrect.

here is the actual scenario: 
[ **whenever i add new elements in the beginning of the array ( i.e. prepending elements to the array / inserting elements at the 0th location ), the ngx-scrollbar is scrolling the top every time.** ]

Explanation : lets say i am scrolling to the top of the container and using infinite scroll concept, i am fetching more data from my db. then I prepend that new data to the top (because i want to see those previous data, correct) . then suddenly ngx-scrollbar scrolls to the topmost location of the container. which gives a sudden flickering scroll kind of experience. but actually i want to stay at that element only where i was earlier (i.e before reaching the top location).

Expectation : if i am currently scrolls to 0th element, and after adding 12 elements to the begnning, the previous 0th element will become 13th element, and scrollbar should stay at 13th element only. must not scroll to 0th element now.

or may be in short ( just think of any conversations application like whatsapp. whenever you scrolls to the top,  new elements are added but your actual scroll position stays as it. ) 


what i have added as a fix:  before adding new elements i calculating actual scrollheight from bottom, and after elements are added to the list, i again moves back to the original location.


just an info, whenever i am scrolling to bottom and i fetches new elements and insert them to the last of array, it doesn't scroll to bottom of the container. it stays as it. (like scrollbar size shrinks but scrollbar doesn't moves to the end) . which is working fine as expected. but above said thing is not working.

But if you were not able to understand the issue, then you should have suggested that in the beginning ( 19 days ! ).

**Comment by MurhafSousli** [comment]
@shivamSharmaMWP It is not mandatory that I reply 19 days ago, I can only look at an issue if I have free time, this is open source, not a customer service. so the better the issue is described the more likely I would look into it.

Anyway, this is objective of this component is to act like a normal div element, not a chat widget, so the question is how would a list container behave if it was a normal scrollable div element? (not ng-scrollbar)

I tried to do the same in a normal div, and I got the same result, [see this stackblitz](https://stackblitz.com/edit/ngx-scrollbar-ju5oes?file=src%2Fapp%2Fconversation%2Fconversation.component.ts)

If I got it wrong, and if a normal div behaves differently, please add a reproduction of the expected behavior using a normal div element.

**Comment by shivamSharmaMWP** [comment]
no worries @MurhafSousli , Thanks for your time.
