### ISSUE TITLE
CDK Drag and Drop Integration: Cannot read property 'clientHeight' of undefined

### ISSUE THREAD

**Issue by cosme-benito** [MurhafSousli/ngx-scrollbar#307]
#### Reproduction

Use StackBlitz to reproduce your issue: https://stackblitz.com/edit/angular-ivy-kxlxep

Steps to reproduce:
1. Just load the StackBlitz: https://stackblitz.com/edit/angular-ivy-kxlxep
2. There is a Javascript error in the console

 
#### Expected Behavior

I wasn't expecting to see a JavaScript error right off the bat. The error appears to be caused by the [scrollViewport] directive, though I have no idea of the implications of the error.

#### Actual Behavior

```javascript
preview-66bbcea50a05892bfce3b.js:1 ERROR TypeError: Cannot read property 'clientHeight' of undefined
    at ScrollViewport.get (ngx-scrollbar.umd.js? [sm]:438)
    at NgScrollbar.update (ngx-scrollbar.umd.js? [sm]:738)
    at NgScrollbar_Template_div_resizeSensor_1_listener (ngx-scrollbar.umd.js? [sm]:738)
    at executeListenerWithErrorHandling (core.umd.js? [sm]:15824)
    at wrapListenerIn_markDirtyAndPreventDefault (core.umd.js? [sm]:15859)
    at SafeSubscriber.schedulerFn [as _next] (core.umd.js? [sm]:25595)
    at SafeSubscriber.__tryOrUnsub (Subscriber.ts:265)
    at SafeSubscriber.next (Subscriber.ts:207)
    at Subscriber._next (Subscriber.ts:139)
    at Subscriber.next (Subscriber.ts:99)
```

#### Environment

- Angular: 10.2.1
- ngx-scrollbar: 7.3.0
- CDK: 10.2.6
- Browser(s): Chrome 86.0.4240.111
- Operating System (e.g. Windows, macOS, Ubuntu): Windows

**Comment by MurhafSousli** [comment]
This is because the `cdkDropList` directive you are using is altering the `scrollViewport` directive.

You should separate the two, here is a fixed stackblitz https://stackblitz.com/edit/angular-ivy-6gatut?file=src%2Fapp%2Fmodal-test%2Fmodal-test.component.html

**Comment by cosme-benito** [comment]
Thanks for the fast feedback. I tried your fix and it does get rid of the JavaScript error. I would maybe suggest the wiki (and stackblitz) to be updated [here](https://github.com/MurhafSousli/ngx-scrollbar/wiki/Integration#integrate-with-cdk-drag-and-drop).

Unfortunately your suggestion also broke the "auto-scroll" feature (ie: dragging an element outside of the view should scroll but it no longer does it). Stackblitz here: https://stackblitz.com/edit/angular-ivy-ggxrjj?file=src%2Fapp%2Fmodal-test%2Fmodal-test.component.html

**Comment by MurhafSousli** [comment]
Ok, then it make sense to use it on the same directive, maybe it is better to allow disabling the auto-height feature or safe check it
