### ISSUE TITLE
Content height after updating to v7

### ISSUE THREAD

**Issue by W3bDan** [MurhafSousli/ngx-scrollbar#311]
#### What are you trying to do?

After updating to v7 all content in ng-scrollbar went beyond of page. I think because auto-height set height programmaticaly. I need an option to disable auto-height.

![screen1](https://user-images.githubusercontent.com/32509512/98845761-612dd080-2478-11eb-93fd-e72383079014.png)
![screen2](https://user-images.githubusercontent.com/32509512/98845767-625efd80-2478-11eb-8354-a3d6c030ed4c.png)

  
#### Environment

- Angular: 10.2.0
- ngx-scrollbar: 7.3.1

**Comment by MurhafSousli** [comment]
For now you can simply set the max-height to 100%, but it will be possible to disable the auto-height feature in a future release, stay tuned!
