### ISSUE TITLE
Inverse scroll vector

### ISSUE THREAD

**Issue by soft-angel** [MurhafSousli/ngx-scrollbar#312]
#Feature Description
Make scroll inferior to reverse direction

#Use Case
Implementation of a list of messages for chat, I plan to flip the scroll area 180 degrees to avoid problems when new messages appear

P.S. I really hope that you will tell me how this can be done on your plugin

**Comment by MurhafSousli** [comment]
I don't understand the use case, what do you mean by flip the scroll!

**Comment by soft-angel** [comment]
> Я не понял варианта использования, что вы имеете в виду под переворотом прокрутки?

I have already decided to use the standard scroll, and refused to reverse scrolling, I had a task when filling the content of the scroll so that it would remain in place, your scroll is scrolling up, tell me, can you do it to stay in place?

**Comment by MurhafSousli** [comment]
@soft-angel This is only a scrollbar component that emulate native scrollbar, it is not meant to do anything more than that.

If you want to make a chat widget, you should either do it manually by implementing your own code, or integrate it with other libraries that does the job for you.

**Comment by soft-angel** [comment]
> @soft-angel This is only a scrollbar component that emulate native scrollbar, it is not meant to do anything more than that.
> 
> If you want to make a chat widget, you should either do it manually by implementing your own code, or integrate it with other libraries that does the job for you.

I thought I could use your solution, only I need your scrollbar to behave like Google chrome, when adding a new one it would stand still
