### ISSUE TITLE
Doesn't update height on window resize

### ISSUE THREAD

**Issue by W3bDan** [MurhafSousli/ngx-scrollbar#313]
#### What are you trying to do?

If reload page on short size and after it increase page - scrollbar's container height doesn't increase (see GIF)

#### What troubleshooting steps have you tried?

[GIF](https://imgur.com/a/HTCB1PJ)
  
#### Environment

- Angular: 10.2.0
- ngx-scrollbar: 7.3.1

**Comment by MurhafSousli** [comment]
Your GIF does not show that you have change the window size!

**Comment by W3bDan** [comment]
Updated Link: [GIF](https://imgur.com/a/2q1PkyW)

**Comment by MurhafSousli** [comment]
From the GIF it shows that resizing the window is not causing the scrollbar to change its size therefore, therefore why would the height of the thumb change??

Check the demo and try to resize the window, you will see it works properly.
