### ISSUE TITLE
Auto-width functionality does not respect "max-width" CSS property

### ISSUE THREAD

**Issue by cosme-benito** [MurhafSousli/ngx-scrollbar#319]
#### Reproduction

Use StackBlitz to reproduce your issue: https://stackblitz.com/edit/angular-ivy-meexhr

Steps to reproduce:
1. Stackblitz: https://stackblitz.com/edit/angular-ivy-meexhr
2. Notice that even though max-width is set to 60px, the ng-scrollbar element has 77px width
3. ng-scrollbar has "min-width: 77px", which I feel should be "width: 77px"
3. Clicking the toggle button swaps the "min-width" property with a "width" property, which presents the result I was expecting
 
 
#### Expected Behavior

The ng-scrollbar max-width should be respected

#### Actual Behavior

It seems that the auto-width behavior is setting a min-width CSS property in the ng-scrollbar. If min-width > max-width then the max-width CSS property is not respected. I feel like auto-width should set a "width" CSS property, though I'm unsure in which use-cases this would be a problem.

#### Environment

- Angular: 10.2.3
- ngx-scrollbar: 7.4.0
- Browser(s): Chrome 86.0.4240.193 
- Operating System (e.g. Windows, macOS, Ubuntu): Windows 10

**Comment by MurhafSousli** [comment]
fixed [stackblitz](https://stackblitz.com/edit/angular-ivy-xo6ths?file=src%2Fapp%2Fmodal-test%2Fmodal-test.component.css) in v7.4.1
