### ISSUE TITLE
Broken @angular/cdk after uninstalling package

### ISSUE THREAD

**Issue by andrey-lazarev** [MurhafSousli/ngx-scrollbar#324]
Steps to reproduce:
1. install the package via `npm i ngx-scrollbar @angular/cdk`
2. uninstall the package itself via `npm uninstall ngx-scrollbar`
3. `@angular/cdk` is broken, lacking dependency to `ngx-scrollbar`

Can this issue be solved in theory? Can we perform a clean up (remove imports, function calls, etc.) on package uninstall.
  
#### Environment

- Angular 11:
- ngx-scrollbar:
- Chrome
- Debian 10

**Comment by pdsavard** [comment]
Do you find an solution?  In my case I got this error after uninstalling:
Error: Cannot resolve type entity ɵngcc10.BidiModule to symbol

**Comment by MurhafSousli** [comment]
I don't think so, ngx-scrollbar depends on the CDK not the other way around, it maybe better to remove node_modules directory and reinstall the packages

**Comment by muuvmuuv** [comment]
Try to compile CDK compiled scripts again: `$(npm bin)/ngcc --use-program-dependencies --tsconfg tsconfig.app.json`

**Comment by MurhafSousli** [comment]
You can clean up with `npm audit fix`
