### ISSUE TITLE
Scrollbar v5 doesn't support position: absolute content anymore

### ISSUE THREAD

**Issue by TheoRM20** [MurhafSousli/ngx-scrollbar#325]
#### Reproduction

Use StackBlitz to reproduce your issue: https://stackblitz.com/edit/ngx-scrollbar

Steps to reproduce:
1. Check scrollbar V4 with absolute content
https://stackblitz.com/edit/ngx-scrollbar-v4-kurx9r?file=src%2Fapp%2Fhome%2Fhome.component.html

2. Check scrollbar V5 with the same content
https://stackblitz.com/edit/ngx-scrollbar-n2q94g?file=src%2Fapp%2Fhome%2Fhome.component.html
 
 
#### Expected Behavior

What behavior were you expecting to see?

I am expecting the ngx-scrollbar to be able to scroll absolute content, like it used to.

#### Actual Behavior

What behavior did you actually see?

The current version does not support scrolling absolute content.

#### Environment

Demo stackblitz from the ngx-scrollbar wiki.

**Comment by MurhafSousli** [comment]
In the newer version, the auto height is enabled by default, you can disable it `<ng-scrollbar [autoHeightDisabled]="true"></ng-scrollbar>` here is a fixed [stackblitz](https://stackblitz.com/edit/ngx-scrollbar-s9s64d?file=src%2Fapp%2Fhome%2Fhome.component.html)

**Comment by TheoRM20** [comment]
Thank you!!
