### ISSUE TITLE
Update default value in wiki

### ISSUE THREAD

**Issue by zepa19** [MurhafSousli/ngx-scrollbar#341]
#### Documentation Feedback

Hi. I have looked into the wiki about [global options API](https://github.com/MurhafSousli/ngx-scrollbar/wiki/global-options#global-options-api-ngscrollbaroptions). The default value for the **authoHeightDisabled** property should be `true` ([code ref](https://github.com/MurhafSousli/ngx-scrollbar/blob/2f86f79da4e64658d8221ab2f6aab0cfae1753d6/projects/ngx-scrollbar/src/lib/utils/scrollbar-manager.ts#L20)).

The WIKI should be updated with correct value, because it misleads people ;)

**Comment by MurhafSousli** [comment]
That was in the older version, and forgot to update it. it is fixed now, thanks for opening this!
