### ISSUE TITLE
Scrollbar doesn't work if page was scrolled with native scrollbar

### ISSUE THREAD

**Issue by andrei-varchanka** [MurhafSousli/ngx-scrollbar#342]
#### Reproduction

Use StackBlitz to reproduce your issue: https://stackblitz.com/edit/ngx-scrollbar

Steps to reproduce:
1. Reduce window height so native scrollbar appears
2. When scroll offset of the page is 0, ngx-scrollbar works fine
3. Scroll the page and try to scroll the content inside ngx-scrollbar using scrollbar
 
#### Expected Behavior

working scrollbar 

#### Actual Behavior

content is not scrolling. (it can be scrolled only using mouse wheel but i want a working scrollbar)

#### Environment

- Angular:
- ngx-scrollbar:
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu):  any

https://media.giphy.com/media/kG2SL1UGEjYoLxtYJm/giphy.gif

**Comment by andrei-varchanka** [comment]
@MurhafSousli

**Comment by andrei-varchanka** [comment]
Hey @MurhafSousli did you start investigating? take a look please

**Comment by MurhafSousli** [comment]
@andrei-varchanka I couldn't replicate this in the the demo, could it be caused by the stackblitz env because it is wrapped in an iframe? can you reproduce it in the demo? https://ngx-scrollbar.netlify.com/

**Comment by andrei-varchanka** [comment]
https://ngx-scrollbar.netlify.com/ doesn't use native scroll for the page so i moved out the content from ngx-scrollbar to demonstrate

https://user-images.githubusercontent.com/53002740/104917912-1911b980-59a5-11eb-9f4e-282c47384ef7.mp4

**Comment by MurhafSousli** [comment]
Is it the same if you try the scrollbar pointer event method?

**Comment by MurhafSousli** [comment]
It seems that there is a problem with the mouse pointer position before dragging the scrollbar at that point..

A good starting point is to look at the dragging methods in https://github.com/MurhafSousli/ngx-scrollbar/blob/master/projects/ngx-scrollbar/src/lib/scrollbar/thumb/thumb.ts#L86

Help is apperciated!

**Comment by andrei-varchanka** [comment]
@MurhafSousli i found the fix, commit it please 
![image](https://user-images.githubusercontent.com/53002740/106150812-c4342700-618c-11eb-9beb-25ca369a0c5c.png)

**Comment by andrei-varchanka** [comment]
Current:     return this.clientRect.top;
Expected:     return this.clientRect.top + window.pageYOffset;

**Comment by MurhafSousli** [comment]
@andrei-varchanka Thank you very much!
