### ISSUE TITLE
scrollbarRef is undefined inside NGX Bootstrap Modal

### ISSUE THREAD

**Issue by swagata1603** [MurhafSousli/ngx-scrollbar#344]
I have added ng-scrollbar selector inside a bootstrap modal. I have subscribed to on modal shown event but trying to get `this.scrollbarRef.scrollable` it is always returning undefined. Here is the code that I am using. Inside the modal I want to use scroll pagination on reached end of the container.

```
openModal(modalTemplate: TemplateRef<any>){
  this._modalService.onShown.subscribe(() => {
      console.log(this.scrollbarRef.scrollable)
  })
  this.modalRef = this._modalService.show(modalTemplate, this.modalConfig);
}
```

**Comment by MurhafSousli** [comment]
Please add a [reprduction stackblitz](https://stackblitz.com/edit/ngx-scrollbar)!
