### ISSUE TITLE
Angular 8 Compilation Error

### ISSUE THREAD

**Issue by veeravetrivel** [MurhafSousli/ngx-scrollbar#347]
**Error:**

ERROR in /node_modules/ngx-scrollbar/fesm2015/ngx-scrollbar.js 591:23
Module parse failed: Unexpected token (591:23)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|             const resizeObserverApi = document.defaultView.ResizeObserver
|                 ? of(document.defaultView.ResizeObserver)
>                 : from(import('@juggle/resize-observer')).pipe(map((module) => module.ResizeObserver), catchError((e) => {
|                     console.log('Unable to load ResizeObserver polyfill', e);
|                     return EMPTY;

Then Added **"@juggle/resize-observer": "3.2.0",** as dependency 
Then Error showing as 

**Error:**
ERROR in Directive ?g in /node_modules/ngx-scrollbar/ngx-scrollbar.d.ts has no selector, please add it!
Can't resolve all parameters for ?g in /node_modules/ngx-scrollbar/ngx-scrollbar.d.ts: ([object Object], [object Object], ?, ?).
Directive ?h in /node_modules/ngx-scrollbar/ngx-scrollbar.d.ts has no selector, please add it!
Can't resolve all parameters for ?h in /node_modules/ngx-scrollbar/ngx-scrollbar.d.ts: ([object Object], ?, ?).
Directive ?m in /node_modules/ngx-scrollbar/ngx-scrollbar.d.ts has no selector, please add it!
Can't resolve all parameters for ?m in /node_modules/ngx-scrollbar/ngx-scrollbar.d.ts: (?, [object Object], [object Object], ?, [object Object]).
Cannot determine the module for class ?g in /node_modules/ngx-scrollbar/ngx-scrollbar.d.ts! Add ?g to the NgModule to fix it.
Cannot determine the module for class ?h in /node_modules/ngx-scrollbar/ngx-scrollbar.d.ts! Add ?h to the NgModule to fix it.
Cannot determine the module for class ?m in /node_modules/ngx-scrollbar/ngx-scrollbar.d.ts! Add ?m to the NgModule to fix it.
#### Environment

- Angular: 8.2.11 @angular/cdk: 8.2.3
- ngx-scrollbar: 7.2.0
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Windows

@MurhafSousli  Please check and tell as soon as possible we are facing it all of the sudden

**Comment by MurhafSousli** [comment]
For the old version you are using, you should `npm i @juggle/resize-observer -D` or update to latest version of the plugin

**Comment by veeravetrivel** [comment]
Hello @MurhafSousli 

Thank you for your reply. Just now we found the issue we have added "fabric": "4.3.0" and "@types/fabric": "4.2.1", dependency npm component in our angular application this made as issue in "ngx-scrollbar". Now we fixed my removing that component in package.json and accessing fabric.js as script file.

Thank you
