### ISSUE TITLE
typo in smooth scroll

### ISSUE THREAD

**Issue by kchowanski** [MurhafSousli/ngx-scrollbar#359]
Hi, I found typo in your documentation in following places:
https://github.com/MurhafSousli/ngx-scrollbar/wiki/smooth-scroll-functions#scroll-to-a-specific-element-by-a-selector
https://github.com/MurhafSousli/ngx-scrollbar/wiki/smooth-scroll-functions#scroll-to-a-specific-element-by-element-reference

![image](https://user-images.githubusercontent.com/24584658/110118475-b5a7e380-7dba-11eb-8438-479b5497f9a6.png)

**Comment by MurhafSousli** [comment]
I fixed it, Thanks!
