### ISSUE TITLE
Auto hide 

### ISSUE THREAD

**Issue by yabood** [MurhafSousli/ngx-scrollbar#369]
#### Feature Description

An option to choose whether or not to auto hide the scroll bar when not scrolling. 

#### Use Case

An always visible scrollbar is not ideal. There are many scenarios where showing the scrollbar only when scrolling results in a much improved user experience. An example to that would be a multi-column layout where multiple visible scrollbars can make the page look more busy and overload the user with unnecessary feedback.

**Comment by MurhafSousli** [comment]
Hey @yabood This option already exists! `<ng-scrollbar visibility="hover"></ng-scrollbar>` https://github.com/MurhafSousli/ngx-scrollbar/wiki/usage#options

**Comment by yabood** [comment]
@MurhafSousli thanks!

**Comment by argelj289** [comment]
Hi, it seems that scrollbar is showing when the container is hovered. Is it possible that it will only show if we hover on the scrollbar side and not the content where scrollbar is applied?

**Comment by argelj289** [comment]
or is there a solution for adding css styles to the scrollbar?

**Comment by MurhafSousli** [comment]
@argelj289 Hi, no, there is not such option, but you can play with CSS for sure https://github.com/MurhafSousli/ngx-scrollbar/wiki/styling
