### ISSUE TITLE
ngx-scrollbar causes a requestAnimationFrame recursion/loop when used without OnPush change detection

### ISSUE THREAD

**Issue by yabood** [MurhafSousli/ngx-scrollbar#373]
#### Reproduction

Unfortunately this issue cannot be observed on stackblitz easily, but will reproduce on any vanilla Angular 11/12 project generated by the CLI. 

Steps to reproduce:
1. Generate a new angular project using the CLI
2. Add ngx-scrollbar to the project
3. Install the newly release [Angular DevTools](https://chrome.google.com/webstore/detail/angular-devtools/ienfalfjdbdpebioblfackkekamfmbnh?hl=en&authuser=0)
4. Start recording with the Angular DevTools Profiler and you'll notice NgScrollbar hammering the application with  requestAnimationFrame requests. 
5. Disable ngx-scrollbar in the project using the disabled property and the behavior in step four will not occur.  

Disabling all ngx-scrollbar options without disabling ngx-scrollbar itself will result in the same behavior. The issue doesn't seem to be caused by any specific feature or addon, but by the library itself.  
 
#### Expected Behavior
NgScrollbar to not trigger a requestAnimationFrame loop.

#### Actual Behavior
NgScrollbar causing a requestAnimationFrame loop. 

#### Environment

- Angular: 11 and 12
- ngx-scrollbar: 7.5.5
- Browser(s): Chrome Version 90.0.4430.212
- Operating System (e.g. Windows, macOS, Ubuntu): macOS

**Comment by MurhafSousli** [comment]
The `requestAnimationFrame` is used to update the thumbnails position of the scrollbar (not in a loop)!

It is supposed to improve  to smooth the animation, allows the CPU to chill and more battery-friendly, check this article https://css-tricks.com/using-requestanimationframe/

In the library, the `animationFrameScheduler` is used which is based on `requestAnimationFrame`, https://github.com/MurhafSousli/ngx-scrollbar/blob/master/projects/ngx-scrollbar/src/lib/scrollbar/thumb/thumb.ts#L57

**Comment by vijaymsit88** [comment]
We are facing the exact same issue in our project. We are using this library in 4 components and when all 4 are open simultaneously, all 4 instances of ngx scrollbar are making these calls to requestAnimationFrame. It's really affecting the overall application performance for us. We also used Angular Dev tools to observe this pattern.

**Comment by MurhafSousli** [comment]
@vijaymsit88 Could make a reproduction?

**Comment by sujeetjaiswara** [comment]
I am also facing the same issue.

**Comment by thecodejedi** [comment]
We also have the same issue.

Could it be, that this is triggered by the ChangeDetection mechanism?

**Comment by thecodejedi** [comment]
I can recreate this issue with an empty Angular app and using Firefox Performance Debugger to verify how many events are triggered.

The events stop triggering immediately if I change the ChangeDetection Strategy for my root object to `ChangeDetectionStrategy.OnPush`


`@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss'],
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class AppComponent {`

**Comment by MurhafSousli** [comment]
@thecodejedi It is good that at least you identified the cause, the scrollbar re-calculate when `ngAfterViewChecked` is triggered.

I couldn't reproduce the issue before since I always have `OnPush` switched on. the problem now is to figure out a way to redo the calculation without depending on `ngAfterViewChecked`

Apps that don't use it, always fell into performance issues because sooner or later, you will have a lot of binding which will be executed very often when the OnPush is off.

**Comment by MurhafSousli** [comment]
I want to try replacing ngAfterViewChecked with ngOnChanges, however, this could cause the scrollbar to not recalculate when it should. any for that I need a reproduction for the issue so I can test the fix.

Can you reproduce the issue in stackblitz or Github repo?

**Comment by thecodejedi** [comment]
I'm currently trying out some possible fixes, and I have an idea that might help, besides switching awaiy from the ngAfterViewChecked

Currently the ChangeDetector is triggerd in a loop, causing all elements in the scroll area to refresh.
I'm now trying to determine if anything changed and if it is really necessary to trigger change detection....

**Comment by thecodejedi** [comment]
> I want to try replacing ngAfterViewChecked with ngOnChanges, however, this could cause the scrollbar to not recalculate when it should. any for that I need a reproduction for the issue so I can test the fix.
> 
> Can you reproduce the issue in stackblitz or Github repo?

I think i can provide you with a sample, no problemo

**Comment by thecodejedi** [comment]
Sample to try changes with the demo application by removing the OnPush:
https://github.com/thecodejedi/ngx-scrollbar/tree/changeDetection-Sample

**Comment by thecodejedi** [comment]
Withj using resize events it looks a lot better, but I don't know if I might have missed something there....

**Comment by thecodejedi** [comment]
I fixed a lot of the troubles I found and integrated it already in our app. It seems to work and only to refresh when needed.

I don't know how to verify more but this feels already solid somehow.

**Comment by MurhafSousli** [comment]
@thecodejedi Thanks for the PR, hopefully I will be able to try it by the weekend!
