### ISSUE TITLE
I want to fire a event if vertical scroll is visible 

### ISSUE THREAD

**Issue by khanani92** [MurhafSousli/ngx-scrollbar#380]
Is there a way to track the scroll visibility of vertical scroll. I want to fire the event on it and add dynamic CSS on it. I'm using Angular 9

**Comment by MurhafSousli** [comment]
There is no event for that at the moment, we can keep this open if it is interesting for others, they can leave a like

**Comment by MurhafSousli** [comment]
It turns out that you can already do that using the `(updated)` output

```html
<ng-scrollbar #scrollbar="ngScrollbar" (updated)="onScrollbarUpdate(scrollbar.state)"></ng-scrollbar>
```

```ts
onScrollbarUpdated(state: NgScrollbarState) {
   if (state.isVerticallyScrollable) {
    console.log('Scrollable');
  } else {
    console.log('Not Scrollable');
  }
}
```

Check the [demo stacbklitz](https://stackblitz.com/edit/ngx-scrollbar-f2qto9?file=src%2Fapp%2Fhome%2Fhome.component.ts)

**Comment by MurhafSousli** [comment]
I added this to the docs https://github.com/MurhafSousli/ngx-scrollbar/wiki/updated-event

Closing...
