### ISSUE TITLE
RTL support

### ISSUE THREAD

**Issue by rasa-app** [MurhafSousli/ngx-scrollbar#384]
#### What are you trying to do?

I'm trying to use RTL direction but I can't achieve this.

#### What troubleshooting steps have you tried?

I put  [dir] =" 'rtl' " to the component but nothing changed and scrollbar is always ltr  

#### Reproduction

[https://stackblitz.com/edit/angular-ivy-ia4odv?file=src%2Fapp%2Fapp.component.html](https://stackblitz.com/edit/angular-ivy-ia4odv?file=src%2Fapp%2Fapp.component.html)

Steps to reproduce:
1. 
2. 
  
#### Environment

- Angular: 12.1
- ngx-scrollbar: 7.5.6
- Browser(s): chrome 91
- Operating System (e.g. Windows, macOS, Ubuntu):  win 10

**Comment by MurhafSousli** [comment]
Can you try adding the dir attribute on the HTML tag `<html dir="rtl"></html>`

**Comment by rasa-app** [comment]
By adding dir to html, it worked.
Thank you

**Comment by rasa-app** [comment]
By adding dir to html, it worked.
Thank you
