### ISSUE TITLE
Scroll to bottom feature

### ISSUE THREAD

**Issue by adrianbenjuya** [MurhafSousli/ngx-scrollbar#39]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ x ] feature request
- [ ] question
```

### Desired functionality

I'd like the scrollbar API to have a "scrollToBottom()" method that allows the scroll container to scroll to its bottom just after its view refreshes, so it can take the latest container height update.

**Comment by MurhafSousli** [comment]
Available in v2.1.0
