### ISSUE TITLE
Feature Request: Pan / Drag using the mouse

### ISSUE THREAD

**Issue by dstj** [MurhafSousli/ngx-scrollbar#396]
#### Feature Description

I think a nice addition to the `ngx-scollbar` component would be the ability to (optionally) use the mouse to pan the content and control the scrollbar offsets.

For example:
```html
<ng-scrollbar track="horizontal" [enableDrag]="true">
```

#### Use Case

I'm creating a visual representation of some multi-step process, so it is larger than the available screen width. I use `ngx-scrollbar` to do the horizontal scroll, but I often find myself wanting to "grab" any empty space in the graphic representation and move the whole thing sideways instead of hunting down for the small scrollbar at the bottom.

I managed to work around it a bit by using the following code, but it "fights" with the `ngx-scrollbar` component when dragging the scrollbar itself as both want to control the X offset.

```html
<ng-scrollbar track="horizontal" #scrollable>
	<div class="graph" (mousedown)="onMouseDown($event)" [ngClass]="{'dragging': pan.active }">
```
```typescript
public onMouseDown($event: MouseEvent) {
	this.pan.active = true;
	this.pan.originX = $event.x;
	this.pan.originScrollX = this.scrollable.viewport.nativeElement.scrollLeft;

	this.mouseMoveSubscription = fromEvent(document, 'mousemove').pipe(
		takeWhile(() => this.pan.active),
		takeUntil(this.onDestroy$),
	)
		.subscribe(e => {
			this.onMouseMove(e as MouseEvent);
		});

	fromEvent(document, 'mouseup').pipe(
		takeWhile(() => this.pan.active),
		takeUntil(this.onDestroy$),
	)
		.subscribe(e => {
			this.cancelPan();
		});

	$event.preventDefault();
}

public onMouseMove($event: MouseEvent) {
	if (!this.pan.active) return;

	const deltaX = $event.x - this.pan.originX;
	this.scrollable.scrollTo({ left: this.pan.originScrollX - deltaX, duration: 0 }); // minus to inverse drag direction
}

private cancelPan() {
	this.pan.active = false;
	this.pan.originX = undefined;
	this.pan.originScrollX = undefined;
	this.cdr.markForCheck();
}
```

A built-in way would probably be simpler then trying to fix it externally, hence the suggestion. :)

**Comment by MurhafSousli** [comment]
Users can already scroll horizontally using a touchpad, or using screens natively and the goal of this project is to make the custom scrollbar behaves as the native scrollbars.

Unfortunately, this feature is outside the scope of this plugin and users may find the extra code unnecessary to be included in their projects.

However, such feature should be easily integrated with the scrollbar, I recommend you to create a custom directive for it.

> but it "fights" with the ngx-scrollbar component when dragging the scrollbar itself as both want to control the X offset.

I am not sure about this, when you drag the plugin will not manipulate the x offset of the viewport, as long as you don't touch the scrollbar.

I'm closing this, but if you need help, feel free to continue the discussion here.

**Comment by dstj** [comment]
@MurhafSousli 
Thanks for the reply,  Ok. I'll try to work around it then.

> > but it "fights" with the ngx-scrollbar component when dragging the scrollbar itself as both want to control the X offset.
> 
> I am not sure about this, when you drag, the plugin should not manipulate the x offset of the viewport, as long as you don't touch the scrollbar.

My problem was actually the opposite. Since the ngx-scrollbar is positioned above the `div`, the mousedown event is captured by both viewport and scrollbar. Using `<ng-scrollbar pointerEventsMethod="scrollbar">` seems to have done the trick.

> However, such feature should be easily integrated with the scrollbar, I recommend you to create a custom directive for it.

I got it working I think. In case someone googles his way here, here's a [repro for all my test cases](https://stackblitz.com/edit/angular-ivy-nr1vsz?file=src/app/app.component.html).
