### ISSUE TITLE
autoHeightDisabled default change

### ISSUE THREAD

**Issue by tj-boyle** [MurhafSousli/ngx-scrollbar#407]
#### Reproduction

Steps to reproduce:
1. Using version 7.6.1
2. Use `ng-scrollbar` in scenario where autoHeight is necessary
3. Omit `autoHeightDisabled`
 
 
#### Expected Behavior

What behavior were you expecting to see?
`autoHeightDisabled` be false

#### Actual Behavior

What behavior did you actually see?
`autoHeightDisabled` is true

Your documentation still lists autoHeightDisabled as being false by default, but your CHANGELOG mentioned how it changed from false to true in version 7.5.0.

It also mentioned how it's a breaking change - Standard version rules specify breaking changes should be major version bumps. Everyone who pulls in the package using `^` and is expecting nothing to change may have issues with their application.

#### Environment

- Angular: 11.2.5
- ngx-scrollbar: 7.6.1
- Browser(s): Chrome 
- Operating System (e.g. Windows, macOS, Ubuntu): macOS

**Comment by MurhafSousli** [comment]
I updated the docs, thanks for noticing!
