### ISSUE TITLE
After upgrading to 8.0.0 my jest unit test fails

### ISSUE THREAD

**Issue by chikakow** [MurhafSousli/ngx-scrollbar#411]
#### Reproduction

Use StackBlitz to reproduce your issue: https://stackblitz.com/edit/ngx-scrollbar

Steps to reproduce:
1. Update ngx-scrollbar to v 8.0.0
2. have ng-scrollbar element on your markup of your component.
2. create spec.ts for that component
3. run the test with jest 27.3.1
4. You get "Uncaught (in promise): Failed to load ng-scrollbar.html" error. Note: The error comes from zone.js and I don't have ng-scrollbar.html in my application. 

Revert to ngx-scrollbar v7.5.6, the test passes.
 
 
#### Expected Behavior

What behavior were you expecting to see?
The test should also pass with v 8.0.0

#### Actual Behavior

What behavior did you actually see?
You get "Uncaught (in promise): Failed to load ng-scrollbar.html" error

#### Environment

- Angular: 12.2.12
- ngx-scrollbar: 8.0.0
- Browser(s): N/A but I use chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Windows 10

**Comment by MurhafSousli** [comment]
This could be caused by your project env, please try installing ngx-scrollbar@8.0.0 in a new brand project and check if the same happens
