### ISSUE TITLE
Update the documentation for autoHeightDisabled.

### ISSUE THREAD

**Issue by TheJLifeX** [MurhafSousli/ngx-scrollbar#412]
## Documentation Feedback

Please update the documentation for `autoHeightDisabled` default value from `false` to `true`.
- See the code line where `autoHeightDisabled` is set to `true` as default value: https://github.com/MurhafSousli/ngx-scrollbar/blob/4a321f06174ed05f51dbbcaf9f482f94c360c9f0/projects/ngx-scrollbar/src/lib/utils/scrollbar-manager.ts#L20
- See the documentation where `autoHeightDisabled` is still `false` as default: https://github.com/MurhafSousli/ngx-scrollbar/wiki/usage#options

### Why ?
Because when you write (your content does not have a fix height (`<ng-scrollbar style="height: 300px">` not adequate)) :
```html
<ng-scrollbar [track]="'horizontal'">
  <div>content</div>
</ng-scrollbar>

```
you expect to see something, since the documentation says `autoHeightDisabled: false` per default, but you actually see nothing.
So you have to explicitly write:
```html
<ng-scrollbar [track]="'horizontal'" [autoHeightDisabled]="false">
  <div>content</div>
</ng-scrollbar>
```

**Comment by MurhafSousli** [comment]
Good catch in the documentation! I fixed it.

For the example, I would keep it as it is, I wouldn't suggest that you use unless you have a need for it.

In some cases it could cause a performance issue if you have a lot of content being altered by a directive, added/removed, animated or if used in CDK. The resize-observer will cause recalculation of the scrollbar.

https://github.com/MurhafSousli/ngx-scrollbar/wiki/Performance-tweak#regarding-the-auto-height-and-auto-width-features

**Comment by TheJLifeX** [comment]
What about the following (in term of performance) ?
```html
<ng-scrollbar [track]="'horizontal'" [ngStyle]="{'height': myElement.offsetHeight}">
  <div #myElement>content</div>
</ng-scrollbar>
```
PS: This is what I used before using `[autoHeightDisabled]="false"`.

**Comment by MurhafSousli** [comment]
Using `[autoHeightDisabled]="false"` is totally fine!

Only if your content height or content changes very frequently in a second then it might be better to disable it

To figure out, get the Angular devtools then in the profiler tab, you will be able to see how often the change detection is triggers
https://chrome.google.com/webstore/detail/angular-devtools/ienfalfjdbdpebioblfackkekamfmbnh

**Comment by TheJLifeX** [comment]
All right, thank you.
