### ISSUE TITLE
Support for angular 13

### ISSUE THREAD

**Issue by rbalet** [MurhafSousli/ngx-scrollbar#413]
#### Feature Description

A support for the Angular 13 would nice

**Comment by MurhafSousli** [comment]
Released v9.0.0 for Angular 13

**Comment by Sergiobop** [comment]
You are the best @MurhafSousli , should you upgrade rxjs too?
Current is
`"rxjs": "^6.6.0",`
And it should be (for Angular13)
`"rxjs": "~7.4.0",`

Thanks!

**Comment by MurhafSousli** [comment]
It doesn't seem to matter, because the project was upgraded using the CLI and RxJS version didn't change. it shouldn't make any difference since it is a peer dependency, it will you use the RxJS version you have in your project.

**Comment by oljp** [comment]
It's possible this is specific to my local environment (node: v16.13.0, npm: v8.1.0), but I am indeed seeing package resolution issues with regard to `ngx-scrollbar@9.0.0`:

```
npm ERR! Could not resolve dependency:
npm ERR! peer rxjs@"^6.6.0" from ngx-scrollbar@9.0.0
npm ERR! node_modules/ngx-scrollbar
npm ERR!   ngx-scrollbar@"^9.0.0" from the root project
```

I should note that this occurred during the migration to Angular 13.

**Comment by jcrespoven** [comment]
Same is happening to me. It seems that peer dependency of rxjs shoud be upgraded to 7.4.0 version...

**Comment by oljp** [comment]
I added a PR for this: https://github.com/MurhafSousli/ngx-scrollbar/pull/419. I don't think we need to force rxjs to be marked as 7.x, but allowing anything greater than 6.6.0 should be more than safe.
