### ISSUE TITLE
Integration with ag-grid table

### ISSUE THREAD

**Issue by jasonparallel** [MurhafSousli/ngx-scrollbar#421]
#### Documentation Feedback

Not sure if this is a documentation request or a feature request.
I'm looking for recommendations on how to apply the scrollbar to a HTMLElement. The use case is for applying to to content created by a library (such as a ag-grid table)

ngx-perfect-scrollbar (which is recommending users migrate to ngx-scrollbar) allows the passing of css selector into the constructor
`new PerfectScrollbar('.ag-body-viewport', { suppressScrollX: true, minScrollbarLength: 15 });
  new PerfectScrollbar('.ag-body-horizontal-scroll-viewport', { suppressScrollY: true, minScrollbarLength: 15 });` 

Can it be done?

**Comment by MurhafSousli** [comment]
I tried that table component, but I was not able to hide the scrollbars using `overflow: hidden`

![image](https://user-images.githubusercontent.com/8130692/149868142-3b21e93d-6ee3-4347-bda6-cc5c08e9b85f.png)

And it seems that it uses weird fake scrollbar wrappers, not sure what it is used for!

Were you able to have `PerfectScrollbar` to work with the table? please add a demo link if possible!

**Comment by jasonparallel** [comment]
@MurhafSousli Thanks for taking a look. I do. I get it moved over to a stackblitz and post

**Comment by MurhafSousli** [comment]
Ag-grid is not compatible to work with ngx-scrollbar

**Comment by MurhafSousli** [comment]
Now it is supported in v14, https://github.com/MurhafSousli/ngx-scrollbar/wiki/Integration#ag-grid-table
