### ISSUE TITLE
Downgrade - rxjs tp v6.6.7

### ISSUE THREAD

**Issue by rbalet** [MurhafSousli/ngx-scrollbar#424]
#### Feature Description

Downgrade from rxjs 7.4.0 to the v6.6.7.

#### Use Case

Actually, angular v13 is working with the v6.6.7.   
Having 7.4.0 in the repo we'll force developer to download the ngx-scrollbar library through `--force` because the following error is shown. 

```
npm ERR! Could not resolve dependency:
npm ERR! peer rxjs@">=7.4.0" from ngx-scrollbar@9.0.1
npm ERR! node_modules/ngx-scrollbar
npm ERR!   ngx-scrollbar@"*" from the root project
```

Working with v6.6.7 is working as expected

**Comment by MurhafSousli** [comment]
Does it interrupt the `npm i` or `npm i ngx-scrollbar`?

**Comment by rbalet** [comment]
@MurhafSousli Yes,it does. 

And since I'm using the library in one of my libraries, it made the auto download peerDependencies from npm 7 impossible.

**Comment by MurhafSousli** [comment]
Ok, will downgrade the rxjs version
