### ISSUE TITLE
Module and Angular 5 

### ISSUE THREAD

**Issue by OlgaMatosova** [MurhafSousli/ngx-scrollbar#43]
Does your module work with angular 5? I am trying but get error:
TypeError: Object(...) is not a function at ngx-scrollbar.js:51 

( _this._scrollSub$ = fromEvent(_this.view, 'scroll').pipe(tap(function (e) { return _this.scrollWorker(e); })).subscribe();)
 
- [x] question

### OS and Version?

> Windows  10.

### Versions
Angular CLI: 1.6.0 (e)
Node: 8.4.0
OS: win32 x64
Angular: 5.2.9

### Repro steps
Just added to component as on your example

### Desired functionality
if I get error because I use angular 5, maybe you know how I can fix it ?

**Comment by MurhafSousli** [comment]
Hi @OlgaMatosova, For Angular 5 use ngx-scrollbar@1.5.7, check the [changelog](https://github.com/MurhafSousli/ngx-scrollbar/blob/master/CHANGELOG.md)
