### ISSUE TITLE
Unable to drag the scrollbar when the page is responsive

### ISSUE THREAD

**Issue by shivani-vemula** [MurhafSousli/ngx-scrollbar#431]
We are using ngx scrollbar in our application, The resolution of our screen is 1920 * 1080 
when I make the browser page responsive. I am unable to hold the thumb and drag it.

https://ngx-scrollbar-v4.stackblitz.io/#/
Click on the top URL and put it on responsive and try to hold and drag the thumb.

Is this possible to have that dragging functionality when the screen is of touch?

**Comment by MurhafSousli** [comment]
The scrollbar thumbs are disabled on mobile by design https://github.com/MurhafSousli/ngx-scrollbar/wiki/Pointer-Events#-note

**Comment by shivani-vemula** [comment]
Thank you.
