### ISSUE TITLE
Error message showing while compile ngx-scrollbar

### ISSUE THREAD

**Issue by HDaghash** [MurhafSousli/ngx-scrollbar#433]
#### What are you trying to do?
Using ngx-scrollbar in angular library

What are you trying to do?
build a library with ngx-scrollbar module imported 

#### What troubleshooting steps have you tried?

changing `angular/cdk` versions to make sure it's compatible 

What are you seeing that does not match your expectations? 
error message showing while compiling 

`symbol Dir declared in /node_modules/@angular/cdk/bidi/dir.d.ts is not exported from @angular/cdk/bidi`

#### Reproduction

We can only help if we can reproduce the problem ourselves. 

Use StackBlitz to demonstrate what you are trying to do: https://stackblitz.com/edit/ngx-scrollbar

Steps to reproduce:
1. generate lib using angular 
2. packge.json like so

```
{
  "name": "xxx",
  "version": "0.0.1",
  "peerDependencies": {
    "@angular/common": "^9.1.13",
    "@angular/core": "^9.1.13",
    "ng-zorro-antd": "^11.4.1",
    "randomcolor": "0.6.2"
  },
  "dependencies": {
    "@angular/cdk": "^9.0.0",
    "@ngx-translate/core": "^13.0.0",
    "@ngx-translate/http-loader": "^6.0.0",
    "ngx-scrollbar": "^9.0.2",
    "tslib": "^1.10.0"
  },
  "devDependencies": {
    "@angular-devkit/build-ng-packagr": "^0.1002.0"
  }
}
```

  
#### Environment

- Angular:9.x
- ngx-scrollbar:9.0.2
- Browser(s): compiler level
- Operating System (e.g. Windows, macOS, Ubuntu):  macOs

Thank you for the support.

**Comment by MurhafSousli** [comment]
Either upgrade your Angular version or use an older version of ngx-scrollbar, check the [changelog](https://github.com/MurhafSousli/ngx-scrollbar/blob/master/CHANGELOG.md) to find a suitable version, maybe try ngx-scrollbar@7.2.3 with Angular 9

**Comment by HDaghash** [comment]
> changelog

Thanks, Murhaf for the fast response,
I decided to upgrade to angular version @13

and then I got new types related  error :
```

Cannot find module 'ngx-scrollbar' or its corresponding type declarations.

51 import * as i48 from "ngx-scrollbar";
```

**Comment by MurhafSousli** [comment]
You have to find the issue in your project, maybe you need to remove your node_modules dir and install it again, or something went wrong while you're upgrading your angular. but I cannot tell what is wrong with your setup.

**Comment by HDaghash** [comment]
> You have to find the issue in your project, maybe you need to remove your node_modules dir and install it again, or something went wrong while you're upgrading your angular. but I cannot tell what is wrong with your setup.
> 
> Did you follow the [Angular update guide](https://update.angular.io/) or did you just install the latest angular using `npm i`?

Thanks, Murhaf.
I was doing it using the official guide actually, but I understand it's hard to till until you have the same packge.json installed
