### ISSUE TITLE
Error on startup

### ISSUE THREAD

**Issue by novakand** [MurhafSousli/ngx-scrollbar#436]
Error on startup.
https://stackblitz.com/edit/angular-ivy-6vd2qk?file=src%2Fapp%2Fapp.module.ts

**Comment by MurhafSousli** [comment]
There is no such input `disableOnBreakpoints` in the latest version, this was deprecated in an older version long time ago.

https://stackblitz.com/edit/angular-ivy-gn4bva?file=src%2Fapp%2Fapp.component.html

**Comment by novakand** [comment]
Ок, Thanks!
