### ISSUE TITLE
ngx-datatable compatibility

### ISSUE THREAD

**Issue by elementalPRESS** [MurhafSousli/ngx-scrollbar#439]
Usually the default behavior of the scrollbar works fine. However, I need to use some 3rd-party components, whereby the scrollbar should only be applied to automatically generated elements of this component. Example:

Works fine:

	<ng-scrollable>
		<div> <-- scrollable area
		...
		</div>
	</ng-scrollable>

Doesn't work:

	<ng-scrollable>
		<ngx datatable>
			<headers>
			...
			</header>
			
			<body> <-- scrollable area
			...
			</body>
	
			<footers>
			...
			</footer>
		</ngx-datatable>
	</ng-scrollable>

Is there any way to tell `ng-scrollbar` to apply to `body`?

**Comment by MurhafSousli** [comment]
Yes, you can! read here https://github.com/MurhafSousli/ngx-scrollbar/wiki/integration

```html
<ng-scrollbar>
	<ngx datatable>
		<headers>
		...
		</header>
		
		<body scrollViewport >
		...
		</body>

		<footers>
		...
		</footer>
	</ngx-datatable>
</ng-scrollbar>
```

BTW it is `ng-scrollbar` not `ng-scrollable`!

**Comment by elementalPRESS** [comment]
At first thx for your prompt feedback! I already saw the `scrollViewport` directive. But I afraid it's not what I'm looking for. In the original given example it works well, but the `header`, `body` and `footer` are generated automatically by the `ngx-datatable` component. See here:

	<ng-scrollbar>
		<ngx-datatable [options] ... ></ngx-datatable>
	</ng-scrollbar>

So I have no access to the inner code and cannot add the `scrollViewport` to the body. But I know that a `div` for the area I want to scroll with a certain class is generated by `ngx-datatable`.

What I'm more looking for is an `ng-scrollbar` option to add the scrollbar to this class name. Do you have any idea how to realize it?


P.S. sorry for the wrong name ;-)

**Comment by MurhafSousli** [comment]
Duplicates of #421 

I am afraid it cannot be integrated with that kind of library at the moment, but maybe we can add it as a feature in a future release.

**Comment by MurhafSousli** [comment]
It is supported in v14
