### ISSUE TITLE
<QUESTION> Dynamic scrolling

### ISSUE THREAD

**Issue by arjan674** [MurhafSousli/ngx-scrollbar#44]
It is possible to scroll to a specific position with:
`scrollRef.scrollXTo(position, duration?)`

But I need to be able to dynamically scroll down and not to a fixed position.
For example something like this: `scrollRef.scrollXDownBy(value, duration?)`

Do you have any idea how I can fix this?

Thank you for your time.

**Comment by MurhafSousli** [comment]
Hi @arjan674, Yes you can but first you need to get a reference of `ScrollbarComponent`

```ts
@ViewChild(ScrollbarComponent) scrollRef: ScrollbarComponent;

scrollXDownBy(value, duration) {
   const position = this.ScrollbarComponent.view.scrollLeft + value;
   this.scrollRef.scrollXTo(position, duration)
}
```
