### ISSUE TITLE
NG_SCROLLBAR_OPTIONS are not working

### ISSUE THREAD

**Issue by elementalPRESS** [MurhafSousli/ngx-scrollbar#440]
I tried to set global options for the scrollbar and tried both ways but none of it is working. I tried:

	@NgModule({
		imports: [
			NgScrollbarModule.withConfig({
				visibility: 'hover',
				track: 'all',
				appearance: 'standard'
			})
		],
		providers: [{
			provide: NG_SCROLLBAR_OPTIONS,
			useValue: {
				visibility: 'hover',
				track: 'all',
				appearance: 'standard',
		},
		}],

Used are the most current versions of Angular and the ngx-scrollbar. 
Is there any trick or something I need to take into account to make it work?

**Comment by MurhafSousli** [comment]
Please fill the template issue properly and add reproduction stackblitz!

**Comment by elementalPRESS** [comment]
> Please fill the template issue properly and add reproduction stackblitz!

That is precisely the problem. When I try this in StackBlitz with a minimal configuration everything works fine. Only in my project the global config is ignored. It is therefore difficult for me to generate a reproducible scenario that I could publish here.

Hence the question of whether any pitfalls are known?

**Comment by MurhafSousli** [comment]
Yes, it probably has to do with where you import that config. if you use ngx-scrollbar only in a child module

If you import `NgScrollbarModule` in one module only or in the root module, then calling `NgScrollbarModule.withConfig()` should work fine.

If you use `NgScrollbarModule`  in multiple child/lazy modules, then provide the injection token `NG_SCROLLBAR_OPTIONS` in the root module. in this case, you don't need to call `NgScrollbarModule.withConfig()`

**Comment by sdspvtltd** [comment]
Hi,I am also facing this issue scine 2 days.Tried above thing in app.module.ts
```
`@NgModule({
    declarations: [
        AppComponent,
        
           ],   
    imports: [`
 NgScrollbarModule.withConfig({
        track	: 'vertical',//Directions to track horizontal, vertical, all
        position	:'native',	//Invert scrollbar position native,invertX,invertY, invertAll
        visibility	:'native'	,//Scrollbar visibility native, hover, always
        appearance	:'compact'	,//Scrollbar appearance standard, compact.
        viewClass	: null	,//Add custom class to the viewport element.
        trackClass	: null	,//Add custom class to scrollbar track elements.
        thumbClass	: null	,//Add custom class to scrollbar thumbnail elements.
        trackClickScrollDuration :	300	,//The smooth scroll duration when a scrollbar is clicked.
        minThumbSize	: 20	,//The minimum scrollbar thumb size in px.
        scrollAuditTime	: 0	,//Throttle scroll event in ms.
        windowResizeDebounce	: 0,//	Debounce interval for detecting changes via window.resize event.
        sensorDebounce	: 0	,//Debounce interval for detecting changes via ResizeObserver.
        sensorDisabled	: false	,//Whether ResizeObserver is disabled.
        pointerEventsMethod:	'viewport'	,//The method used to detect scrollbar pointer-events, read more.
        pointerEventsDisabled:	false	,//Enable/disable the scrollbar track clicked and thumb dragged events.
        autoHeightDisabled :	false	,//Whether to set component height to content height.
        autoWidthDisabled	:true,//Whether to set component width to content width.
     }),
],
 providers: [
 {provide : NG_SCROLLBAR_OPTIONS,useValue :{
            track	: 'vertical',//Directions to track horizontal, vertical, all
position	:'native',	//Invert scrollbar position native,invertX,invertY, invertAll
visibility	:'native'	,//Scrollbar visibility native, hover, always
appearance	:'compact'	,//Scrollbar appearance standard, compact.
viewClass	: null	,//Add custom class to the viewport element.
trackClass	: null	,//Add custom class to scrollbar track elements.
thumbClass	: null	,//Add custom class to scrollbar thumbnail elements.
trackClickScrollDuration :	300	,//The smooth scroll duration when a scrollbar is clicked.
minThumbSize	: 20	,//The minimum scrollbar thumb size in px.
scrollAuditTime	: 0	,//Throttle scroll event in ms.
windowResizeDebounce	: 0,//	Debounce interval for detecting changes via window.resize event.
sensorDebounce	: 0	,//Debounce interval for detecting changes via ResizeObserver.
sensorDisabled	: false	,//Whether ResizeObserver is disabled.
pointerEventsMethod:	'viewport'	,//The method used to detect scrollbar pointer-events, read more.
pointerEventsDisabled:	false	,//Enable/disable the scrollbar track clicked and thumb dragged events.
autoHeightDisabled :	false	,//Whether to set component height to content height.
autoWidthDisabled	:true,//Whether to set component width to content width.
        }}
]
```
Trying toset the NGScrollbar in one of the directive .Code from directive inside onInit()
` this.ps = new NgScrollbar(this.elementRef.nativeElement
            , NgZone.bind(this.fusePerfectScrollbarOptions), 
            this.fusePerfectScrollbarOptions,Directionality.prototype,
             SmoothScrollManager.bind(this.fusePerfectScrollbarOptions),
             ScrollbarManager.bind(this.fusePerfectScrollbarOptions),
            
            
        );
`
Still getting the err in console '
properties of undefined (reading 'sensorDisabled')
    at new NgScrollbar (ngx-scrollbar.mjs:880:59)
    at _a5._init (fuse-perfect-scrollbar.directive.ts:192:19)
    at set enabled [as enabled]
'
any help would be appreciated.

**Comment by hakimio** [comment]
@sdspvtltd if you want to manually instantiate `ng-scrollbar` component, use [createComponent()](https://netbasal.com/getting-to-know-the-createcomponent-api-in-angular-22fb115f08e2) function instead of calling the constructor yourself.
```ts
const ngScrollbar = createComponent(NgScrollbar, {
    hostElement: this.elementRef.nativeElement,
    environmentInjector: this.environmentInjector,
    projectableNodes: [
        Array.from(this.elementRef.nativeElement.children)
    ]
});
this.applicationRef.attachView(ngScrollbar.hostView);
```

**Comment by MurhafSousli** [comment]
This is fixed v14
