### ISSUE TITLE
Opening ngx-bootstrap modal inside ng-scrollbar does not work correctly

### ISSUE THREAD

**Issue by scurk1415** [MurhafSousli/ngx-scrollbar#444]
#### Reproduction

Use StackBlitz to reproduce your issue: https://stackblitz.com/edit/ngx-scrollbar-gxz5tv?file=src/app/home/home.component.html

Steps to reproduce:
1. Install ngx-bootstrap and implement a modal inside ng-scrollbar
2. You will have to refresh the page after you click on the button on the "not working" page

I found out that the problem lies in the css property
`.ng-scroll-viewport {
  contain: strict;
}
`
which treats the ng-scrollbar as its own container. The reproduction StackBlitz contains a working example of the "solution" with `.ng-scroll-viewport {
  contain: initial;
}
`, but i have no idea if that affects your component in any way
 
#### Expected Behavior
The expected behavior is that the modal gets shown in the middle of the page above the backdrop

#### Actual Behavior
The modal gets opened underneath the backdrop (which gets added outside of the ng-scrollbar container, in the body tag) and the modal is centered based on the ng-scrollbar container instead of the page (i made a sidebar in my reproduction example, to show this)

The issue mentions ngx-bootstrap, but my guess is that every component/modal that has backdrop outside of the ng-scrollbar component has the same problem. The centering of the modal in the middle of the page is probably affected for every modal type of component (regardless of backdrop)

This is an issue that sounds similar to my problem https://github.com/MurhafSousli/ngx-scrollbar/issues/261 (but there is no reproduction, so i might be wrong :D )

#### Environment

- Angular: 14
- ngx-scrollbar: 10
- Browser(s): Chrome@102.0.5005.63 
- Operating System (e.g. Windows, macOS, Ubuntu):  Windows

**Comment by MurhafSousli** [comment]
Interesting, but you shouldn't put the dialog inside the scrollbar component. here is a [fixed stackblitz](https://stackblitz.com/edit/ngx-scrollbar-vx4hij?file=src%2Fapp%2Fhome%2Fhome.component.html) without overriding `contain: initial`
