### ISSUE TITLE
Unable to scroll prerendered version of Angular Universal app

### ISSUE THREAD

**Issue by joeveiga** [MurhafSousli/ngx-scrollbar#446]
In SSR applications, the page needs to be (somewhat) usable before the JS is downloaded and the final SPA is loaded. In a very slow connection scenario, it could be several seconds before the user sees the final version of the app. Right now ngx-scrollbar is "hijacking" the scroll and I'm unable to scroll the page until the js chunks are finally downloaded. This kinda defeats the purpose of providing the prerendered version to the user if they can't consume the information 😄. 

I tried `[disable]`ing the component until the app loads in the browser but still same behavior.

#### Reproduction

(I can provide a stackblitz with the code but you'll need to prerender the app locally anyways to be able to reproduce it so I thought maybe it isn't necessary)

```ts
// app.component.ts
import { isPlatformBrowser } from '@angular/common';
import { Component, Inject, PLATFORM_ID } from '@angular/core';

@Component({
  selector: 'app-root',
  template: `
    <ng-scrollbar [disabled]="!enabled">
      <div>A</div>
      <div>B</div>
      <div>C</div>
      <div>D</div>
      <div>E</div>
    </ng-scrollbar>
  `,
  styles: [`
    ng-scrollbar {
      height: 400px;
      border: 2px solid black;

      div {
        font-size: 60px;
        padding: 40px;
        text-align: center;
      }
    }
  `],
})
export class AppComponent {
  enabled: boolean;

  constructor(@Inject(PLATFORM_ID) platformId: Object) {
    this.enabled = isPlatformBrowser(platformId);
  }
}
```

![Kapture 2022-07-04 at 21 47 28](https://user-images.githubusercontent.com/19226858/177233712-3880ef10-f7e9-46f0-bae8-05cea1150916.gif)

Steps to reproduce:
1. `npx @angular/cli new ngx-scrollbar-ssr`
2. `cd ngx-scrollbar-ssr`
3. Add angular universal to the project: `npx ng add @nguniversal/express-engine`
4. Add minimal ng-scrollbar to app
5. Prerender application: `npm run prerender`
6. `cd dist/ngx-scrollbar-ssr/browser`
7. Serve the prerendered app: `npx http-server`
8. Use Chrome DevTools to simulate slow connection conditions and try to scroll before the non-SSR version of the app is fully loaded. 
 
#### Expected Behavior

We're able to scroll the prerendered version of the app. Basically ngx-scrollbar needs to be actually disabled until it can be used.

#### Actual Behavior

We're unable to scroll, even when the document (HTML and CSS, no JS) is fully loaded.

#### Environment

- Angular: ^14.0.0
- ngx-scrollbar: ^10.0.0
- Browser(s): Chrome 103
- Operating System (e.g. Windows, macOS, Ubuntu): macOS Monterey

**Comment by MurhafSousli** [comment]
It's strange that the content was rendered but was unscrollable, Did you try to force the CSS to scroll vertically on `.ng-scroll-viewport`?

What do you think should be done in the library to improve this!

**Comment by joeveiga** [comment]
Update:

> Did you try to force the CSS to scroll vertically on .ng-scroll-viewport
>

This sorta works. We're able to scroll the document but the scrollbar isn't shown.

```ts
import { isPlatformBrowser } from '@angular/common';
import { Component, HostBinding, Inject, PLATFORM_ID, ViewEncapsulation } from '@angular/core';

@Component({
  selector: 'app-root',
  template: `
    <ng-scrollbar>
      <div class="item">A</div>
      <div class="item">B</div>
      <div class="item">C</div>
      <div class="item">D</div>
      <div class="item">E</div>
    </ng-scrollbar>
  `,
  styles: [`
    .app-root {
      ng-scrollbar {
        height: 400px;
        border: 2px solid black;

        .item {
          font-size: 60px;
          padding: 40px;
          text-align: center;
        }
      }

      &.pre-rendered {
        .ng-scroll-viewport {
          overflow-y: auto;
        }
      }
    }
  `],
  encapsulation: ViewEncapsulation.None,
  host: {
    class: 'app-root'
  }
})
export class AppComponent {
  @HostBinding('class.pre-rendered')
  preRenderedered: boolean;

  constructor(@Inject(PLATFORM_ID) platformId: Object) {
    this.preRenderedered = !isPlatformBrowser(platformId);
  }
}
```

**Comment by MurhafSousli** [comment]
We hide the scrollbar using CSS, but the CSS is applied through the scrollbar component stylesheet, which should be bundled with the JS.

I am not sure what to do with this issue, so I will keep it open in case someone else is having it. maybe they can think of a solution.

___

The `--native-scrollbar-size` shouldn't  matter, it is CSS variable is used to push the content when the native scrollbar is shown, however, since we hide them using CSS, it should always be 0 unless used in mobile chrome or safari. then the CSS is incompatible with those browsers and there is no other way to hide the native scrollbar besides pushing it outside the viewport.. therefore we use this CSS variable as a fallback for those browsers.

**Comment by MurhafSousli** [comment]
This should be fixed in v14
