### ISSUE TITLE
bundlephobia.com can't display the bundle size

### ISSUE THREAD

**Issue by Bykiev** [MurhafSousli/ngx-scrollbar#453]
https://bundlephobia.com/package/ngx-scrollbar

```
EntryPointError
We could not guess a valid entry point for this package. Perhaps the author hasn't specified one in its package.json ?
```

**Comment by MurhafSousli** [comment]
Not sure how to fix it!

**Comment by Bykiev** [comment]
I believe you should specify [main](https://docs.npmjs.com/cli/v8/configuring-npm/package-json#main) field in package.json

**Comment by MurhafSousli** [comment]
it works fine without specifying the main field in other projects, like [ng-gallery](https://github.com/MurhafSousli/ngx-gallery) and [ngx-highlightjs](https://github.com/MurhafSousli/ngx-highlightjs)! I guess it is a random bug from their side!
