### ISSUE TITLE
CommonJS or AMD dependencies can cause optimization bailouts

### ISSUE THREAD

**Issue by Bykiev** [MurhafSousli/ngx-scrollbar#454]
Hi, when building angular app there is an warning:

`\node_modules\ngx-scrollbar\fesm2015\ngx-scrollbar-smooth-scroll.mjs depends on 'bezier-easing'. CommonJS or AMD dependencies can cause optimization bailouts.For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies`

Can we replace `bezier-easing` dependency with smth else or patch it?

**Comment by MurhafSousli** [comment]
We rely on this package for smooth scrolling, add the following to your angular.json to get rid of that warning

https://github.com/MurhafSousli/ngx-scrollbar/blob/c56d31d83f8f2f592f0d4c3549232486ca344c80/angular.json#L61-L64

**Comment by Bykiev** [comment]
I know about it, but such dependencies will cause optimization issues, I don't want use such libraries in  my projects

**Comment by Sergiobop** [comment]
I just open https://github.com/gre/bezier-easing/issues/51 to see if the owners can do something about this one @Bykiev

**Comment by MurhafSousli** [comment]
`bezier-easing` has been removed from dependencies list
