### ISSUE TITLE
Scrollbars only visible on scroll

### ISSUE THREAD

**Issue by elementalPRESS** [MurhafSousli/ngx-scrollbar#455]
It would be really great to have a scrollbar behaviour similar as on a MacOS.

In other words: to see the scrollbars only when scrolling. On Mac the scrollbars are visible when the mouse hovers the scrollbar (not the element but the area of the element where the scrollbars are) or when the user scrolls via the touchpad. After scrolling is done the scrollbar disappears after a second or so.

Can you imagine to implement such a feature, or is it already possible (and I still don't know it) 

Thx and best regards,
Lars

**Comment by MurhafSousli** [comment]
Did you try setting `visibility="hover"` or you mean you only want it to appear only the scrollbar container? if so try CSS it is straight forward

**Comment by MurhafSousli** [comment]
Because you're adding a layer on top the component which blocks the hover event. add `z-index: -1;` to the pseudo element and it will work fine!

**Comment by elementalPRESS** [comment]
> Because you're adding a layer on top of the component which blocks the hover event. add `z-index: -1;` to the pseudo element and it will work fine!

Thx a lot!

**Comment by LinboLen** [comment]
should't closed. 

may listen on scrolling event, when scrolling then set scrollbar visible.
