### ISSUE TITLE
Scrollbar not working with CSS :before in parent node

### ISSUE THREAD

**Issue by elementalPRESS** [MurhafSousli/ngx-scrollbar#456]
Today I planned to enhance my sidebar with the scrollbar. But it wasn't working. After a while of debugging I could find the reason in a CSS statement of the parent node of the scrollbar. The scrollbar breaks whenever a `:before` or `:after` with a `content` tag is used.

https://stackblitz.com/edit/angular-ivy-uad6ad

Please see the SCSS file. Comment out the `content` and it's working. Any idea how to solve, because I would need this CSS statement as it is.
 
#### Environment

- Angular: 14.2.2
- ngx-scrollbar: 10.0.1
- Browser(s): Chrome > 100
- Operating System (e.g. Windows, macOS, Ubuntu): macOS

**Comment by MurhafSousli** [comment]
Just add a z-index to the component [fixed stackblitz](https://stackblitz.com/edit/angular-ivy-qm8t2e?file=src%2Fapp%2Fapp.component.scss,src%2Fapp%2Fapp.component.html)
