### ISSUE TITLE
Is there an event to know if there is a scrollbar or not ?

### ISSUE THREAD

**Issue by wibimaster** [MurhafSousli/ngx-scrollbar#458]
#### What are you trying to do?

I'm trying to detect if the scrollbar is displayed or not.
But, I don't want to know its visible state, but if the content is longer than the container and if the scrollbar is needed.

The later goal is to add 2 arrows to scroll left/right, but hide them if no scrolling is needed.

#### What troubleshooting steps have you tried?

I cannot use the classical `element.offsetWidth/Height` VS `element.clientWidth/Height` because of ngx-scrollbar's DIV elements dynamically added in the DOM

#### Environment

- Angular: 14.2.5
- ngx-scrollbar: 10.0.1
- Browser(s): Chrome 105.0.5195.125
- Operating System (e.g. Windows, macOS, Ubuntu): Ubuntu 22.04

**Comment by MurhafSousli** [comment]
You can use `NgScrollbar.viewport.offsetWidth/Height`

**Comment by wibimaster** [comment]
> For now you can use `NgScrollbar.viewport.offsetWidth/Height`

I just found `NgScrollbar.state.isHorizontallyScrollable`, and it seems to be updated on the `NgScrollbar.updated` event ; isn't it a boolean to know if there's a scrollbar ?

**Comment by MurhafSousli** [comment]
Correct, you can use that too but as you mentioned it only updates on `NgScrollbar.updated`, but I don't know your use case so I gave you the source element

**Comment by MurhafSousli** [comment]
I think this can be closed as you can already get the state you need! closing...
