### ISSUE TITLE
Unable to scroll using keyboard arrows inside a dialog

### ISSUE THREAD

**Issue by Abdulrrahman** [MurhafSousli/ngx-scrollbar#473]
#### Reproduction

stackblitz: https://stackblitz.com/edit/angular-sblvne?file=src/main.ts

Steps to reproduce:
1. place scroll inside dialog
2. use keyboard arrows no scroll (native scroll works just fine)
 
 
#### Expected Behavior

What behavior were you expecting to see?
to be able to scroll using keyboard

#### Actual Behavior

What behavior did you actually see?
stuck

#### Environment

- Angular:
- ngx-scrollbar:
- Browser(s):
- Operating System (e.g. Windows, macOS, Ubuntu):

**Comment by MurhafSousli** [comment]
It happened because you put the scrollable `<ul>` element outside `ng-scrollbar` component

Here is a [fixed stackblitz](https://stackblitz.com/edit/angular-1yxjkb?file=src%2Ftest%2Ftest.component.html,src%2Ftest%2Ftest.component.css,src%2Ftest%2Ftest.component.ts)

Use

```html
  <ng-scrollbar style="height: 100px">
    <ul tabindex="0">
      <li><span>&#10003;</span> Panda</li>
      <li><span>&#10003;</span> Unicorn</li>
      <li><span>&#10003;</span> Lion</li>
      <li><span>&#10003;</span> Panda</li>
      <li><span>&#10003;</span> Unicorn</li>
      <li><span>&#10003;</span> Lion</li>
      <li><span>&#10003;</span> Panda</li>
      <li><span>&#10003;</span> Unicorn</li>
      <li><span>&#10003;</span> Lion</li>
    </ul>
  </ng-scrollbar>
```
Or

```html
  <ng-scrollbar style="height: 100px">
    <ul scrollViewport tabindex="0">
      <li><span>&#10003;</span> Panda</li>
      <li><span>&#10003;</span> Unicorn</li>
      <li><span>&#10003;</span> Lion</li>
      <li><span>&#10003;</span> Panda</li>
      <li><span>&#10003;</span> Unicorn</li>
      <li><span>&#10003;</span> Lion</li>
      <li><span>&#10003;</span> Panda</li>
      <li><span>&#10003;</span> Unicorn</li>
      <li><span>&#10003;</span> Lion</li>
    </ul>
  </ng-scrollbar>
```

**Comment by MurhafSousli** [comment]
Your stackblitz didn't work!

**Comment by Abdulrrahman** [comment]
> Your stackblitz didn't work!

it should be working right now

**Comment by MurhafSousli** [comment]
This one is difficult, I have no idea!
