### ISSUE TITLE
Integration with ScrollDispatcher?

### ISSUE THREAD

**Issue by EdwardIII** [MurhafSousli/ngx-scrollbar#474]
#### Feature Description

I had a look through the sourcecode but I couldn't find a way to neatly integrate this so that CDK ScrollDispatcher would fire when the element got scrolled: https://material.angular.io/cdk/scrolling/overview#cdkscrollable-and-scrolldispatcher

In theory you can drop cdkScrollable onto an existing element (like a div, for example) and it will publish notifications to ScrollDispatcher#scrolled: https://material.angular.io/cdk/scrolling/api#ScrollDispatcher

I did try adding this to the scrollbar: 

```
<ng-scrollbar cdkScrollable
              visibility="hover">
```

When I inspected with the angular inspector in Chrome, I could see it had setup properly (I could see the ScrollDispatcher instance etc on there), but it didn't seem to actually be firing. I guess this is because the `ng-scrollbar` is not the element doing the actually scrolling, but one of the nested elements that gets created inside it.

I thought I'd try to jerry-rig something with `scrollbarRef.scrolled.subscribe(e => ...)`, but that seemed incompatible as the ScrollDispatcher doesn't let you just call it to dispatch a new scroll event, it only accepts an actual `Element` to register, and then takes it from there. 

Is there a way to do this with the ngx-scrollbar existing code, or would it need a new feature?

#### Use Case

RepositionScrollStrategy with CdkOverlay would then automatically be able to move overlays around when something gets scrolled inside an ng-scrollbar.

**Comment by MurhafSousli** [comment]
<The scrollable element is not the component itself, but its child component which you don't have control over, UNLESS you use the `viewport` directive

```html
<ng-scrollbar visibility="hover">
  <div scrollViewport cdkScrollable>
     <!-- CONTENT -->
  </div>
</ng-scrollbar>
```

Here is a [working stackblitz](https://stackblitz.com/edit/ngx-scrollbar-bgfh4p?file=src%2Fapp%2Fhome%2Fhome.component.ts,src%2Fapp%2Fhome%2Fhome.component.html)

**Comment by EdwardIII** [comment]
@MurhafSousli that's fantastic - thank you!
