### ISSUE TITLE
Facing difficulty in installing in Both version of Angular 10 and Angular 14

### ISSUE THREAD

**Issue by husenindia** [MurhafSousli/ngx-scrollbar#475]
#### Reproduction

On Execution of the installation command:
npm i ngx-scrollbar 
 
#### Actual Behavior
Getting This erros. 
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/cdk@">=15.0.0" from ngx-scrollbar@11.0.0
npm ERR! node_modules/ngx-scrollbar
npm ERR!   ngx-scrollbar@"*" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.

#### Environment

- Angular 10 and 14 in both versions.
- ngx-scrollbar: latest version and older version both
- Browser(s): Chrome
- Operating System: Windows

**Comment by MurhafSousli** [comment]
For Angular 14

`npm i ngx-scrollbar@10.0.1`

For Angular 11

`npm i ngx-scrollbar@8.0.0`

See the [changelog](https://github.com/MurhafSousli/ngx-scrollbar/blob/master/CHANGELOG.md)
