### ISSUE TITLE
Make the Scrollbar grow to its given max-width

### ISSUE THREAD

**Issue by MRH4287** [MurhafSousli/ngx-scrollbar#477]
#### What are you trying to do?

I want to display an element that is positioned absolutly in the browser.
The element itself doesn't know which size it's going to have, as it's defined by the content.

I want to set the max-width and max-height of the container, but have it otherwise grow as needed.

The problem ist, that the scrollbar component does not grow to its max-width before it wraps the content.
I can not set the `white-space: nowrap`, as i want my content to wrap when needed.

#### Reproduction

I created an overlay which is position over the while Document.
Within that, i created an div container which is positioned via absolute coordinates.

Here is an example:
https://stackblitz.com/edit/ngx-scrollbar-2ofhjw?file=src%2Fapp%2Fhome%2Fhome.component.html,src%2Fapp%2Fhome%2Fhome.component.scss
  
I hope you can help me.

#### Environment

- Angular:
- ngx-scrollbar:
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu):  Windows

**Comment by MurhafSousli** [comment]
Fixed in v14
