### ISSUE TITLE
Support for mouse wheel scrolling for x-axis

### ISSUE THREAD

**Issue by Ab-Hanan01** [MurhafSousli/ngx-scrollbar#478]
#### Feature Description

Does it support mouse wheel scrolling for horizontal scrollbar? If not could this feature be easily added and how

#### Use Case

When vertical scrollbar is disabled I want to be able to use mouse wheel for horizontal scrolling.

**Comment by MurhafSousli** [comment]
@ysk3a I agree, this can be confusing, the scrollbar plugin should mimic the native behavior, developers who desire that functionality can write their own code to move the scrollable container horizontally on the mouse wheel but for this plugin I believe it's out of the scope
