### ISSUE TITLE
Scrollbar are not shown on init

### ISSUE THREAD

**Issue by CosmoFruit** [MurhafSousli/ngx-scrollbar#48]
i try to use ng-scrollbar in next case:

```
<div class="scrollable-content">
      <ng-scrollbar #scrollRef>
        <ng-container  *ngFor="let item of (params$ | async)">
          <div class="param">
            {{ item.value }}
          </div>
        </ng-container>
      </ng-scrollbar>
</div>
```

```
 .scrollable-content {
      position: absolute;
      top: 0;
      left: 0;
      right: 0;
      bottom: 0;
    }

```

ngx-scrollbar@1.5.7

not show scrollbar when viewInit
![default](https://user-images.githubusercontent.com/28723724/42106368-7aa988de-7bdc-11e8-80d6-671d61bf94b9.png)

only appears after mouse inside div and scrolEvent

**Comment by MurhafSousli** [comment]
Hi @CosmoFruit can you reproduce it in a [stackblitz](https://stackblitz.com/edit/ngx-scrollbar)?
