### ISSUE TITLE
"Sticky Table Column" not working

### ISSUE THREAD

**Issue by devandreassimmeth** [MurhafSousli/ngx-scrollbar#485]
I have problem on combining the Scrollbar with a Bootstrap table. The code of the table is the following:

HTML:
```
<ng-scrollbar
  [autoHeightDisabled]="false"
  track="all"
  style="max-height: 300px"
>
  <div class="table-responsive mb-2">
    <table class="table align-items-center mb-0">
      <thead>
        <tr>
          <th
            class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7 ps-2 sticky-left"
            scope="col"
          >
            Date
          </th>
          <th
            class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7 ps-2"
            scope="col"
            *ngFor="let index of indices"
          >
            {{ index.name }}
          </th>
        </tr>
      </thead>
      <tbody>
        <tr *ngFor="let date of dates">
          <td class="align-middle sticky-left">
            <span class="text-sm font-weight-bold opacity-9">{{
              datePipe.transform(date.toDate(), 'MM/dd/yyyy')
            }}</span>
          </td>
          <td
            class="align-middle"
            *ngFor="let index of indices"
          >
            <span class="text-sm font-weight-bold opacity-9">{{
              getIndexValue(date, index.values) || '-'
            }}</span>
          </td>
        </tr>
      </tbody>
    </table>
  </div>
</ng-scrollbar>
```

CSS:
```
.sticky-left {
  position: sticky;
  left: 0;
  z-index: 1;
  background-color: #fff;
}
```

What does the code do?
It is a simple table that displays dates in the first column. The other columns are (price-)indices, where you have a value for every date given. So the different index-values are connected to the date in the first column. That's why I want to have it sticky. When I remove the <ng-scrollbar> tag, it works how it should. But with the tag, the sticky-effect does not work anymore. Is there a solution for this?

**Comment by devandreassimmeth** [comment]
Okay, I attached an [example-project](https://stackblitz.com/edit/stackblitz-starters-1swjjj?file=src%2Fapp%2Fapp.component.ts) for reproduction.

The table is both times the same. In the first table, both stickies (table header and first column) are working. In the second table, that lies in the <ng-scrollbar> tag, the sticky of the first column is no longer working.

**Comment by MurhafSousli** [comment]
The problem is with the container and the position sticky, Here you a fixed [stackblitz](https://stackblitz.com/edit/stackblitz-starters-dbwcxw?file=src%2Fapp%2Fapp.component.html,src%2Fapp%2Fexample-table%2Fexample-table.component.html,src%2Fapp%2Fexample-table%2Fexample-table.component.scss)

**Comment by devandreassimmeth** [comment]
Very nice, thank you very much for helping out! :)
