### ISSUE TITLE
scrollbar for canvas is not working in mobile device

### ISSUE THREAD

**Issue by likhita-naik** [MurhafSousli/ngx-scrollbar#486]
#### Reproduction

Use StackBlitz to reproduce your issue: https://stackblitz.com/edit/ngx-scrollbar

Steps to reproduce:
1. 
2. 
 
 
#### Expected Behavior

What behavior were you expecting to see?
I have implemented the ngx-scrollbar for canvas. It is working fine in desktop.but that canvas itself is not scroll able  in mobile device.
Sliding of scrollbar not works in mobile device but at least that canvas component must be scroll able . Its happening only for canvas element.

#### Actual Behavior

What behavior did you actually see?
I have implemented the ngx-scrollbar for canvas. It is working fine in desktop.but that canvas itself is not scroll able mobile device

#### Environment

- Angular:
- ngx-scrollbar:
- Browser(s):
- Operating System (e.g. Windows, macOS, Ubuntu):

**Comment by MurhafSousli** [comment]
Please add stackblitz reproduction?
