### ISSUE TITLE
How to programmatically initialize ngx-scroll bar

### ISSUE THREAD

**Issue by Dobermaxx99** [MurhafSousli/ngx-scrollbar#487]
I'm trying to programmatically initialize ngx-scroll bar to use this on a 3rd party app.

Here's my code:

![image-20230606-085406](https://github.com/MurhafSousli/ngx-scrollbar/assets/2335879/9bcda03b-c2a6-4359-83c1-9ae97b3384c5)

However, I encountered an error: Cannot read properties of undefined (reading 'setAsViewport')

![image-20230606-085418](https://github.com/MurhafSousli/ngx-scrollbar/assets/2335879/edc7af63-d407-4fcc-817a-e3fdbe494239)

Currently using ~9.0.2 because we are on Angular 13

**Comment by MurhafSousli** [comment]
You can't
