### ISSUE TITLE
Memory leak when using in SSR

### ISSUE THREAD

**Issue by walec51** [MurhafSousli/ngx-scrollbar#488]
#### Reproduction

Use ngx-scrollbar in an app using Angular Universal. Request a page that uses it 100x of times .
 
#### Expected Behavior

Node process memory usage staying constant level - this is how it look in our app after we just removed ngx-srollbar and changed nothing else:

![image-20230609-101420](https://github.com/MurhafSousli/ngx-scrollbar/assets/738484/3a616b62-21c3-4ff7-bc94-56ecdfad0f16)

#### Actual Behavior

This is how memory usage looked before removing ngx-scrollbar

![image-20230609-100705](https://github.com/MurhafSousli/ngx-scrollbar/assets/738484/375f83eb-7dfd-4fe8-ab60-0e68ddcbd844)

#### Environment

- Angular: 14
- ngx-scrollbar: leatest
- Browser(s): N/A
- Operating System (e.g. Windows, macOS, Ubuntu): reproducible on all

**Comment by walec51** [comment]
This is how we used your component:

```
  <ng-scrollbar
      class="kfb-scrollbar"
      [autoHeightDisabled]="false"
      [visibility]="always"
      [track]="vertical">
    <!-- content -->
  </ng-scrollbar>
```

I don't think that tweeking your components configuration to side step the problem is a valid solution.

**Comment by MurhafSousli** [comment]
So do you mean the plugin is not cleaning up the resources it used after it's removed?

**Comment by MurhafSousli** [comment]
Closing...

**Comment by walec51** [comment]
yes, I think your component is not not cleaning up the resources

most common causes for this are:

- create subscriptions to observable which do not have something like `takeUntil(this.destroyed$)` which will end the subscription when the component is destroyed
- adding variables with unique names to global objects like `window`
- creating circular dependencies in objects
