### ISSUE TITLE
WithConfig no more present on version >= 13

### ISSUE THREAD

**Issue by meriturva** [MurhafSousli/ngx-scrollbar#498]
See here:

https://github.com/MurhafSousli/ngx-scrollbar/wiki/global-options#update-in-version-720-you-can-use-withconfig-function-to-set-the-global-config

`withConfig` is not more present on v. 13.x

Thanks.

**Comment by MurhafSousli** [comment]
Thanks for notifying, forgot to update the docs and add the deprecation note in the changelog
