### ISSUE TITLE
ERROR TypeError: Object(...) is not a function!

### ISSUE THREAD

**Issue by ShrinivasKattimani** [MurhafSousli/ngx-scrollbar#50]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report
- [ ] feature request
- [ ] question
```

### OS and Version?
Windows 10

### Browser and Version
chrome 67.0.3396.99

### Versions
Angular CLI: 1.6.5
Node: 8.9.4
OS: win32 x64
Angular: 5.2.11
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cli: 1.6.5
@angular-devkit/build-optimizer: 0.0.42
@angular-devkit/core: 0.0.29
@angular-devkit/schematics: 0.0.52
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.9.5
@schematics/angular: 0.1.17
typescript: 2.5.3
webpack: 3.10.0

### Repro steps
1. installed the package via npm
"ngx-scrollbar": "^2.0.4"

2. injected ngx-scroll in app.module.ts
import { ScrollbarModule } from 'ngx-scrollbar';
@NgModule({
  imports: [
    ScrollbarModule,
  ],
})

3. Consumed ngx-scroll in a component
```
<ng-scrollbar style="height:100px;">
    <table class="table table-hover">
    <tbody>
        <ng-container *ngIf="data.lists?.length===0">Data not available</ng-container>
        <tr *ngFor="let item of data.lists">
        <td>{{item.key}}</td>
        <td class="text-right">{{item.value}}</td>
        </tr>
    </tbody>
    </table>
</ng-scrollbar>
```

### The log given by the failure
ERROR TypeError: Object(...) is not a function
    at eval (ngx-scrollbar.js:51)
    at ZoneDelegate.invoke (zone.js:388)
    at Zone.run (zone.js:138)
    at NgZone.runOutsideAngular (core.js:4708)
    at ScrollbarComponent.ngAfterViewInit (ngx-scrollbar.js:42)
    at callProviderLifecycles (core.js:12748)
    at callElementProvidersLifecycles (core.js:12715)
    at callLifecycleHooksChildrenFirst (core.js:12698)
    at checkAndUpdateView (core.js:13853)
    at callViewAction (core.js:14195)

### Desired functionality
N/A

### Mention any other details that might be useful
N/A

**Comment by MurhafSousli** [comment]
Can you reproduce it in this [stackblitz](https://stackblitz.com/edit/ngx-scrollbar)?

**Comment by osmanraifgunes** [comment]
I had this exact same error.
