### ISSUE TITLE
Input binding does not work for many properties

### ISSUE THREAD

**Issue by Butterblume654** [MurhafSousli/ngx-scrollbar#503]
#### What are you trying to do?

I'm switching from perfect scrollbar to ngx scrollbar. Before I already had a facade for perfect scrollbar, so that I now only have one place to change. But it seems that the properties of ng-scroller are only accessible when used as attributes. 

But I want to use variables to set e.g. autoHeightDisabled instead of hardcode its value to either true or fase. Same for appearance and some other properties. I always get "Can't bind to 'appearance' since it isn't a known property of 'ng-scrollbar'".

#### What troubleshooting steps have you tried?

I tried to use:
<ng-scrollbar [appearance]="appearance"></ng-scrollbar>
<ng-scrollbar [attr.appearance]="appearance" ></ng-scrollbar>

I also tried many different versions of ngx-scrollbar.

#### Reproduction

Steps to reproduce:
1. Just try to use property or attribute binding to bind the value dynamically.
  
#### Environment

- Angular:15.1.0
- ngx-scrollbar: 13.0.1
- Operating System (e.g. Windows, macOS, Ubuntu): debian

#### EDIT

It works when I disable strictTemplates in my tsconfig. But I think it should also work with strictTemplates.

**Comment by MurhafSousli** [comment]
It works fine with `strictTemplates` on, but you have to use `ScrollbarAppearance` as the variable type!

https://github.com/MurhafSousli/ngx-scrollbar/blob/c265c3c9f9889d0c9231f121db1faf12ac114419/projects/ngx-scrollbar/src/lib/ng-scrollbar.model.ts#L3-L7

This will get the same behavior with Material like in mat-card `<mat-card [appearance]="appearance"></mat-card>`

**Comment by Butterblume654** [comment]
Hey, thanks. But this is not working. Also the other input properties like reachedOffset, autoHeightDisabled or autoWidthDisabled do not work.

They are accepting a primitive number or boolean/string type. And they do not work either.

**Comment by MurhafSousli** [comment]
Those were fixed in v12.0.1, check the [changelog](https://github.com/MurhafSousli/ngx-scrollbar/blob/master/CHANGELOG.md#1201)

**Comment by Butterblume654** [comment]
That's strange. But okay, thanks for your help anyway. I appreciate it.

Until I'm able to update to angular 16 I access NgScrollbar with ViewChild and set then my props.
