### ISSUE TITLE
Type error on ng-scrollbar.d.ts when doing npm run

### ISSUE THREAD

**Issue by Ash66hub** [MurhafSousli/ngx-scrollbar#509]
![image](https://github.com/MurhafSousli/ngx-scrollbar/assets/61526075/50b1d6ab-2ba2-4f63-9163-5d4e7bbf09d4)

#### What are you trying to do?

Upgrade to version 13.0.1 of ngx-scrollbar

#### What troubleshooting steps have you tried?

Tried installing v10.0.1 of ngx-scrollbar, which seems to work fine

#### Reproduction

1.  npm i ngx-scrollbar@13.0.1
2.  npm run
  
#### Environment

- Angular: 15
- ngx-scrollbar: 13.0.1
- Browser(s): -na- 
- Operating System (e.g. Windows, macOS, Ubuntu):  Windows

**Comment by Billyhelm** [comment]
I also had this same issue trying to run v12.0.0 on angular 15. 

Environment

- Angular: 15
- ngx-scrollbar: 12.0.0
- Browser(s): -na-
- Operating System (e.g. Windows, macOS, Ubuntu): Windows

Fixed by installing v10.0.1

**Comment by MurhafSousli** [comment]
I believe v11.0.0 should work fine with Angular 15! [see the changelog](https://github.com/MurhafSousli/ngx-scrollbar/blob/master/CHANGELOG.md)
