### ISSUE TITLE
Detect scroll position

### ISSUE THREAD

**Issue by OlgaMatosova** [MurhafSousli/ngx-scrollbar#51]
Hi
I line your library, it is cool and simple

- [ ] question
How can I detect position of scroll? I need detect if already end of scroll or 70% of height was scrolled.

### Versions
"ngx-scrollbar": "^2.1.0"

### Desired functionality
If it dosn't exist how soon you can add it?

Than you for any help

**Comment by MurhafSousli** [comment]
Hi @OlgaMatosova thanks!

You can use the output `scrollState` to get the scroll event

```html
<ng-scrollbar (scrollState)="onScroll($event)"></ng-scrollbar>
```
To calculate the percentage, look for it on stackoverflow you will find plenty of answers.

**Comment by lexsalg** [comment]
I can not use the aforementioned event

< ng-scrollbar  (scrollState) = " onScroll ($ event) " > </ ng-scrollbar >

**Comment by MurhafSousli** [comment]
@lexsalg See the [breaking changes](https://github.com/MurhafSousli/ngx-scrollbar/blob/master/CHANGELOG.md#breaking-changes)

**Comment by 1997Buhuti** [comment]
(scrollState)="onScroll($event)" scrollState didn't work for me also any solutions? how to detect the current position of scrollbar.

**Comment by MurhafSousli** [comment]
@1997Buhuti That output was deprecated long time ago, here is how to use the scroll event https://github.com/MurhafSousli/ngx-scrollbar/wiki/scroll-event
