### ISSUE TITLE
`inline-block` scroll content hack causing issues with `relative` positioned content

### ISSUE THREAD

**Issue by hakimio** [MurhafSousli/ngx-scrollbar#510]
#### Reproduction

**Reproduction project attached to this issue.**
[ngx-scrollbar-swiper.zip](https://github.com/MurhafSousli/ngx-scrollbar/files/12093564/ngx-scrollbar-swiper.zip)

Steps to reproduce:
1. Place swiperjs `<swiper>` element inside `<ng-scrollbar>`
2. 

 
#### Expected Behavior

Swiper content would look the same like when placed inside a `overflow: auto` block element.

#### Actual Behavior

`ng-scrollbar` causes swiper slides to be a lot wider than they are supposed to be.

#### Additional Info

Changing `ng-scroll-content` display from `inline-block` to `block` fixes the issue.

#### Environment

- Angular: 16.1.5
- ngx-scrollbar: 13.0.2
- Browser(s): Chrome 114
- Operating System: Windows 10

**Comment by MurhafSousli** [comment]
Please use the stackblitz for reproduction!

**Comment by hakimio** [comment]
Swiper library doesn't work in stackblitz, that's why I attached the reproduction to the issue.

**Comment by MurhafSousli** [comment]
As I remember the `inline-block` was necessary to make horizontal scroll work properly. with display block it would force fitting parent width.

Your fix should stay at the project level

**Comment by hakimio** [comment]
- horizontal scrollbar works fine even when scroll content is using `display: block`. [The margin/padding issue](https://github.com/MurhafSousli/ngx-scrollbar/blob/b3d1421c0fe20e04709cd69329d5faa8d6ee17aa/projects/ngx-scrollbar-demo/src/app/example5/example5.component.scss#L23) is a problem with the example number 5 itself, not the library. The example should be fixed instead of applying a hack to the library to fix the example.
- Most people are using default option: `track: vertical` and correct vertical behavior should be prioritized. If, for some reason, you still want to keep the inline-block hack, you could only apply it when `track` is set to `horizontal` or `all`, not `vertical`.

**Comment by MurhafSousli** [comment]
@hakimio If `width: fit-content` was applied on `ng-scroll-content` element would it also cause the same issue? could you try it?

**Comment by hakimio** [comment]
Yes, it causes the same issue.
Anyway, what kind of issue exactly are you trying to address with those kind of workarounds/hacks?

**Comment by MurhafSousli** [comment]
> Yes, it causes the same issue. Anyway, what kind of issue exactly are you trying to address with those kind of workarounds/hacks?

The content layer is observed for size change using the `ResizerObserver` if it didn't fit the width of its content, the scrollbar won't be notified to update

**Comment by MurhafSousli** [comment]
@hakimio I will tackle this by adding `width: fit-content` only when the viewport is horizontally scrollable

**Comment by hakimio** [comment]
Sounds good. Thank you.

**Comment by MurhafSousli** [comment]
@hakimio Could you try if it works fine with the slider if you remove `width: fit-content` and set `position: absolute` on the `.ng-scroll-content` ?

**Comment by hakimio** [comment]
No, but you can just test it yourself as well. I have provided CodeSandbox reproduction above.

**Comment by MurhafSousli** [comment]
> No, but you can just test it yourself as well. I have provided CodeSandbox reproduction above.

Oh, forgot about that, lol

**Comment by MurhafSousli** [comment]
Fixed in v14
