### ISSUE TITLE
when dynamic data added inside ngx-scrollbar height is not detected.

### ISSUE THREAD

**Issue by rachurinaresh** [MurhafSousli/ngx-scrollbar#514]
#### Reproduction

Steps to reproduce:
1.  Add content dynamically inside the ngx-scrollbar.
2. Observe the scrollbar. The content is overflowed but the scroll bar is not showing.
 
 
#### Expected Behavior

What behavior were you expecting to see?
When we add data dynamically inside the <ngx-scrollbar></<ngx-scrollbar> the content height should be detected and should display the scrollbar if it is overflow.

#### Actual Behavior

What behavior did you actually see?
The content is overflowed but the scroll bar is not showing.

Note: **I used style height: 100% for the .ng-scroll-content class.**

**Comment by MurhafSousli** [comment]
Please add a reproduction if you want me to look into it

**Comment by fxck** [comment]
We are experiencing a similar problem, strangely enough, it only happens when you use one of the `reached` events - remove them and everything works fine. Will try to provide a repro over the weekend.

**Comment by jasonrhythmsystems** [comment]
For those who are experiencing similar issues make sure that you are adding a "single" child div directly under the "scrollViewport" element. I was experiencing this issue and realized I was doing an ngFor under my scrollViewport that had some fancy expansion code that was in turn making the scrollbar height not calculate properly. Adding a single child div between the scrollViewport and the ngFor elements fixed this issue.

This is already documented in the Integration > Basic Usage section of the Wiki.

**Comment by xsegrity** [comment]
For those who are experiencing similar issues make sure that you are adding a "single" child div directly under the "scrollViewport" element. I was experiencing this issue and realized I was doing an ngFor under my scrollViewport that had some fancy expansion code that was in turn making the scrollbar height not calculate properly. Adding a single child div between the scrollViewport and the ngFor elements fixed this issue.

This is already documented in the Integration > Basic Usage section of the Wiki.

**Comment by DaniilVysotskiy** [comment]
@xsegrity thanks, man, saved my work day, wasted on searching the root-cause of that strange behavior - could never get auto calculated scrollHeight for any angular construction within div[scrollView] wrapper.

@MurhafSousli may be it will be better, if the front and main article **Usage** will contain the full info about correct and proper usage of ng-scrollbar for dynamic content?
