### ISSUE TITLE
 Infinite scroll functionality

### ISSUE THREAD

**Issue by GerardoTovar** [MurhafSousli/ngx-scrollbar#515]
#### Feature Description

is there a way to enable this behavior of this css property
[overflow-anchor](https://developer.mozilla.org/en-US/docs/Web/CSS/overflow-anchor)

#### Use Case
Most of the chats when you scroll up and reach the top. This loads more messages and the scroll does not move, it stays at the same height of the view

I thought about using ngx-infinite-scroll but currently it doesn't work in angular 16

A temporary fix was to add an id to chat messages and when loading new messages quickly do a scrollIntoView. but this makes a little flicker

I found a closed issue from 2020 asking for this functionality #306 

Thank you very much for your time

**Comment by hakimio** [comment]
Can't you just use [custom scrollViewport](https://github.com/MurhafSousli/ngx-scrollbar/wiki/usage#:~:text=If%20you%20need%20to%20get%20hold%20of%20the%20scrollable%20element%20of%20the%20component%2C%20you%20can%20add%20a%20child%20element%20and%20then%20assign%20it%20with%20scrollViewport%20directive) for this?

**Comment by MurhafSousli** [comment]
Infinite scroll is outside the scope of the plugin, but you can apply the behavior on the viewport using CSS

Another way is using `updated` output, whenever content size change, call scroll to bottom

```html
<ng-scrollbar #scrollbarRef="ngScrollbar"
              (afterUpdate)="scrollbarRef.scrollTo({ bottom: 0, duration: 200 })">
   ...
</ng-scrollbar>
```
