### ISSUE TITLE
updated event firing twice

### ISSUE THREAD

**Issue by Ash66hub** [MurhafSousli/ngx-scrollbar#517]
#### What are you trying to do?

```
@ViewChild(NgScrollbar) scrollable: NgScrollbar;
ngAfterViewInit() {
    this.scrollable.updated.pipe(takeUntil(this.destroyed$)).subscribe(() => { 
        // This is firing twice
    }
}
```

  
#### Environment

- Angular: 15
- ngx-scrollbar: 10.0.1
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Windows

**Comment by Ash66hub** [comment]
As a workaround, I've added `throttleTime(200) ` for now

**Comment by MurhafSousli** [comment]
Sure, it may update multiple time as long the scrollbar gets updated hence the name `updated`. in the new version, will improve how the update works with a reason parameter.
