### ISSUE TITLE
Incorrect behavior of fixed element inside scrolling table

### ISSUE THREAD

**Issue by volodymyrmilovanov2022** [MurhafSousli/ngx-scrollbar#518]
#### Reproduction

Use StackBlitz to reproduce your issue: https://stackblitz.com/edit/ngx-scrollbar

I have a table in my app with horizontal scrollbar. Also I have an "action" item on each row - for example "DELETE", which becomes visible on hovering the row in table. I want my action item allways be in the right corner, is row scrolled to the end, or not.
I set it's positioning to fixed.

 
#### Expected Behavior

Action item always stays at right edge of table view.

#### Actual Behavior

When scroling table to the right, action item scrolls  to the right too.
![image](https://github.com/MurhafSousli/ngx-scrollbar/assets/112403119/89d3946c-3247-454b-9234-8582172fa0fc)
![image](https://github.com/MurhafSousli/ngx-scrollbar/assets/112403119/58ad9534-6c54-4a78-95a8-88992228a1e8)

If i replace ng-scrollbar with simple div which has overflow-x: auto, everything works right.
I'm attaching two stackblitzes to display this behavior.
[Native](https://stackblitz.com/edit/stackblitz-starters-5dfvbk )
[ngx-scrollbar](https://stackblitz.com/edit/stackblitz-starters-neur9z)
#### Environment

- Angular: 16.2.5
- ngx-scrollbar: 13.0.3
- Browser(s):Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Windows

**Comment by MurhafSousli** [comment]
Just wrap the table in a div with `scrollViewport` directive, here is a [fixed stackblitz](https://stackblitz.com/edit/stackblitz-starters-ze4pqk?file=src%2Fapp%2Fapp.component.html,src%2Fapp%2Fapp.component.scss,src%2Fapp%2Fapp.component.ts)

```html
<ng-scrollbar track="horizontal" [autoHeightDisabled]="false">
  <div scrollViewport>
    <table mat-table [dataSource]="dataSource"> ... </table>
  </div>
</ng-scrollbar>
```

**Comment by micobarac** [comment]
It doesn't work with the latest v14.0 version: 

[StackBlitz Example](https://stackblitz.com/edit/u99fpk?file=src%2Fapp%2Fapp.component.html)

**Comment by MurhafSousli** [comment]
@micobarac in the stackblitz you sent, its actually working!

Keep in mind there are some [breaking changes ](https://github.com/MurhafSousli/ngx-scrollbar/blob/master/CHANGELOG.md).

`track` became `orientation`

```html
<ng-scrollbar orientation="horizontal">
  <table style="white-space: nowrap" mat-table [dataSource]="dataSource">
    ...
  </table>
</ng-scrollbar>
```

Here is a [fixed stackblitz](url)

**Comment by micobarac** [comment]
Can you send the working url, this one is not good?

**Comment by micobarac** [comment]
The Stackblitz url is not formatted ok.  I corrected my example, but, still not working.

**Comment by MurhafSousli** [comment]
Because you missed a semi comma 

![image](https://github.com/MurhafSousli/ngx-scrollbar/assets/8130692/d9c08155-5bdd-4147-9ec2-360141053741)


Here is a fixed one https://stackblitz.com/edit/u99fpk-bitehw?file=src%2Fapp%2Fapp.component.scss
