### ISSUE TITLE
Does not work in angular material

### ISSUE THREAD

**Issue by nvv3801756** [MurhafSousli/ngx-scrollbar#52]
When used in mat-tabs elements, it does not work. There is a way to endure through lazy but not work trackx and tracky (expected to work as overflow).
`
<mat-tab-group>
  <mat-tab label="First">
    <ng-scrollbar>
      <p>a</p>
       ....
    </ng-scrollbar>
  </mat-tab>
  <mat-tab label="Second">
    <ng-template matTabContent>
      <component></component>
    </ng-template>
  </mat-tab>
</mat-tab-group>
`

**Comment by MurhafSousli** [comment]
Please fill the issue template properly and try to reproduce it in a [stackblitz](https://stackblitz.com/edit/ngx-scrollbar)

**Comment by ViieeS** [comment]
@MurhafSousli Hi! I have the same problem with `mat-tab` and `ngx-scrollbar`.

Here is minimal reproduction of the bug behaviour: https://stackblitz.com/edit/angular-csbgkz

Try to open Long tab, with ng-scrollbar its content has zero height.

**Comment by sujeetjaiswara** [comment]
Same issue i am getting

**Comment by sujeetjaiswara** [comment]
Automatically scroll to bottom ngx-scrollbar not working

**Comment by MurhafSousli** [comment]
@ViieeS upgrade to latest version here is a [fixed stackblitz ](https://stackblitz.com/edit/angular-csbgkz-e7qnxd?file=app%2Ftab-group-dynamic-height-example.html)

I added a better way by wrapping the material tab component with the scrollbar component
