### ISSUE TITLE
Updated event link is broken

### ISSUE THREAD

**Issue by dmmishchenko** [MurhafSousli/ngx-scrollbar#520]
#### Documentation Feedback

Provide a brief summary of what you would like to see changed in our 
documentation at https://github.com/MurhafSousli/ngx-scrollbar/wiki.

Feel free to provide any suggestions of content or examples you’d like us to include.

## Description: 
When i click "Updated event" link in panel or navigate directly via link: https://github.com/MurhafSousli/ngx-scrollbar/wiki/updated-event i'm getting error: "You do not have permission to update this wiki."

## Expected result: 
Navigation to "Updated event" page

## Image:
<img width="1457" alt="Screenshot 2023-10-12 at 09 06 32" src="https://github.com/MurhafSousli/ngx-scrollbar/assets/51910160/87033df2-7128-4715-a266-7d211905fd33">

**Comment by MurhafSousli** [comment]
Whoops, it is fixed now!

**Comment by dmmishchenko** [comment]
@MurhafSousli thanks mate!
