### ISSUE TITLE
change direction to rtl or ltr

### ISSUE THREAD

**Issue by omaraalia93** [MurhafSousli/ngx-scrollbar#525]
how to change direction to RTL or LTR  of the scrollbar when i change language without  reload the document.

**Comment by MurhafSousli** [comment]
The scrollbar will automatically change direction when you apply the attribute `dir="rtl"` to either html tag or body tag.

You can also change position using `<ng-scrollbar position="invertY">`

**Comment by omaraalia93** [comment]
it didn't worked as expected when i changed the dir attribute on html and body am not sure why.

i fixed it by setting dir attribute on the main <ng-scrollbar>  element .

i have <ng-scrollbar> as a parent for the main router outlet.  when i changed this one the inner <ng-scrollbar>s  is fixed also.

**Comment by omaraalia93** [comment]
It didn't work as expected when I changed the 'dir' attribute on the HTML and body. I'm not sure why.

I fixed it by setting the 'dir' attribute on the main 'ng-scrollbar' element. I have 'ng-scrollbar' as the parent for the main router outlet. When I made this change, the inner 'ng-scrollbars' were also fixed.

**Comment by MurhafSousli** [comment]
@xidedix It is working in the demo, as you can see I use the dir directive from the CDK `BidiModule` , maybe you can try the same

https://github.com/MurhafSousli/ngx-scrollbar/blob/b3d1421c0fe20e04709cd69329d5faa8d6ee17aa/projects/ngx-scrollbar-demo/src/app/example-x/example-x.component.html#L28-L44
