### ISSUE TITLE
Introduce droppedTop and droppedBottom, ... output events

### ISSUE THREAD

**Issue by mlc-mlapis** [MurhafSousli/ngx-scrollbar#527]
#### Feature Description

Having the opposite events (**droppedTop**, **droppedBottom**, **droppedStart**, and **droppedEnd**) to already existing **reached**... events would be excellent.

#### Use Case

When creating helper buttons to allow one-click actions to move to the top, bottom, start, and end scrolling positions, you need to know when to hide/show them. The reached events are helpful when you want to avoid showing them in the edge positions. But you'd like to show them again when the scroller is not in those edge positions. In such a case, the new dropped events would be perfect. Of course, including the new **droppedOffset** property.

**Comment by MurhafSousli** [comment]
@mlc-mlapis Its now available in v14 beta 7, feedback is appreciated!
