### ISSUE TITLE
need help for styling (global options)

### ISSUE THREAD

**Issue by pliersch** [MurhafSousli/ngx-scrollbar#528]
Found no example how to set a class (viewClass, trackClass or thumbClass) as global option. I'm unimaginative. Please help me!

**Comment by DhayananthP** [comment]
https://github.com/MurhafSousli/ngx-scrollbar/wiki/global-options Have you tried this?

**Comment by MurhafSousli** [comment]
Here is an example 

https://github.com/MurhafSousli/ngx-scrollbar/blob/b3d1421c0fe20e04709cd69329d5faa8d6ee17aa/projects/ngx-scrollbar-demo/src/app/example3/example3.component.html#L4-L7

and here is the usage


https://github.com/MurhafSousli/ngx-scrollbar/blob/b3d1421c0fe20e04709cd69329d5faa8d6ee17aa/projects/ngx-scrollbar-demo/src/app/example3/example3.component.scss#L17-L24

Visit the files to see exactly how they are used!

**Comment by DhayananthP** [comment]
@MurhafSousli I think @pliersch is trying apply styles for ng scrollbar used multiple times in his application. I faced similar scenario and I did something like this,
In main.scss,
ng-scrollbar.custom-class {
// styles for track and thumb
}
In component,
<ng-scrollbar class="custom-class" > </ng-scrollbar>
Does this help?

**Comment by MurhafSousli** [comment]
Yes, there are more than one way to write styles, the demo app is a live example of that

**Comment by pliersch** [comment]
Hi,
sorry, i forgot the ticket. Yes, i wanted help how i can set the global css once. How i have set these 3 classes as global option? 
Yes, i mean here (https://github.com/MurhafSousli/ngx-scrollbar/wiki/global-options))
Current i set the css every time again.
FooComponent
`<ng-scrollbar class="light-grey-scrollbar">`
BarComponent
`<ng-scrollbar class="light-grey-scrollbar">`
