### ISSUE TITLE
scrollbar disappearing on Firefox/Safari when reaching bottom/end

### ISSUE THREAD

**Issue by gasparsantillan** [MurhafSousli/ngx-scrollbar#529]
#### Reproduction

Steps to reproduce:
1.  go to https://ngx-scrollbar.netlify.app/
2.  scroll to the very bottom of the content
3.  Refresh page
 
 
#### Expected Behavior

Scrollbar remains at the same position and is visible

#### Actual Behavior

Scrollbar is not visible anymore
[screen-recorder-fri-nov-03-2023-15-36-02.webm](https://github.com/MurhafSousli/ngx-scrollbar/assets/137271177/42fe15ca-14a2-4a15-8cfc-f3c13798b5c3)

#### Environment

- Angular: 15.0.1
- ngx-scrollbar: 9.0.3
- Browser(s): Firefox/Safari
- Operating System: Windows 11

**Comment by MurhafSousli** [comment]
Fixed in v14
