### ISSUE TITLE
NPM Marks Module as Deprecated

### ISSUE THREAD

**Issue by gpresland** [MurhafSousli/ngx-scrollbar#53]
NPM shows the package as deprecated here:
https://www.npmjs.com/package/ngx-scrollbar

However, this GitHub has no such disclaimer.

Is the NPM deprecated message valid?

**Comment by MurhafSousli** [comment]
The package is not, only the last beta version has a problem so I deprecated, you should use v2.1.0

**Comment by gpresland** [comment]
Yes, following the README and doing `npm install ngx-scrollbar --save` shows the following in the console:
```
npm WARN deprecated ngx-scrollbar@2.2.0-beta.0: This beta version is buggy, do not use it!
```

I would imagine a lot of people simply following the README wouldn't notice the message in the console and would attempt to use the buggy beta version.

**Comment by MurhafSousli** [comment]
Ah, usually the beta versions are not install unless you specifiy `@2.2.0-beta.0`
