### ISSUE TITLE
reachedBottom output broke scrollbar layout inside mat-select

### ISSUE THREAD

**Issue by VladislavKhlystun** [MurhafSousli/ngx-scrollbar#531]
#### What are you trying to do?

Trying to use `ng-scrollbar` inside `mat-select` and detect scrolling to the end. After adding `(reachedBottom)` directive, viewport height starting to be with `height: 0` and you don't see the options inside and can't scroll. When deleting `(reachedBottom)` directive, problem disappears. 

#### Reproduction
[Stackblitz example](https://stackblitz.com/edit/stackblitz-starters-xes3um?description=An%20angular-cli%20project%20based%20on%20@angular/animations,%20@angular/common,%20@angular/compiler,%20@angular/core,%20@angular/forms,%20@angular/platform-browser,%20@angular/platform-browser-dynamic,%20@angular/router,%20core-js,%20rxjs,%20tslib%20and%20zone.js&file=src%2Fmain.ts,src%2Ftest%2Ftest.component.ts,src%2Ftest%2Ftest.component.html,src%2Fglobal_styles.css,tsconfig.json,src%2Findex.html&title=Angular%20Starter)

  
#### Environment

- Angular: 16 or higher
- ngx-scrollbar: 13.0.3

Maybe anyone have some thoughts how to fix it? Or something done wrong in the reproduction

**Comment by MurhafSousli** [comment]
Fixed in v14
