### ISSUE TITLE
SmoothScrollModule has been removed but the wiki page is not updated.

### ISSUE THREAD

**Issue by guoapeng** [MurhafSousli/ngx-scrollbar#535]
#### Documentation Feedback

the module SmoothScrollModule has been removed as [changelog]([ngx-scrollbar](https://github.com/MurhafSousli/ngx-scrollbar/tree/b3d1421c0fe20e04709cd69329d5faa8d6ee17aa)
/CHANGELOG.md) mentioned.

> - `SmoothScrollModule` has been removed, you can import `SmoothScroll` directive directly instead!

but [the wiki page](https://github.com/MurhafSousli/ngx-scrollbar/wiki/smooth-scroll) on the usage of SmoothScroll is not updated, which is causing confusion. could you please update the document accordingly.
![image](https://github.com/MurhafSousli/ngx-scrollbar/assets/5491418/9122a8ba-cd51-4d7a-a8e9-38e60b8df553)

**Comment by MurhafSousli** [comment]
Thank you very much! I updated the wiki.
