### ISSUE TITLE
Issue in ngx-scrollbar with mat-select of angular-material

### ISSUE THREAD

**Issue by vartikaagrawal411** [MurhafSousli/ngx-scrollbar#537]
#### Reproduction
I need to use ngx scrollbar inside mat select component. mat select get adjusted according to content given on top or bottom.
So, I am giving 
max-height like this
![image](https://github.com/angular/components/assets/149461813/3cf29e3c-0119-4bd0-8fb3-e2acd0f22833)
and autoHeightDisabled= false  ,
![image](https://github.com/angular/components/assets/149461813/6df3edd6-cc1a-4d51-a1bc-c95bbc2514b3)

but, mat select dropdown is not adjusting it's position on top,  and is getting clipped
![image](https://github.com/angular/components/assets/149461813/5cc21532-3db5-4dde-9714-9a4be8cea7d1)

Without using ngx-scrollbar mat-select is working as expected.

Use StackBlitz to reproduce your issue:  https://stackblitz.com/edit/ngx-scrollbar-jpa7wb?file=src%2Fapp%2Fscroll-event-example%2Fscroll-event-example.html,src%2Fapp%2Fscroll-event-example%2Fscroll-event-example.module.ts,src%2Fapp%2Fscroll-event-example%2Fscroll-event-example.scss,src%2Fapp%2Fapp.component.html,src%2Fapp%2Fapp.component.css

Steps to reproduce:
1. Go to Scroll-event section
2. see the behavior in given dropdown
 
 
#### Expected Behavior

mat select dropdown should adjust itself on top so that content don't get clipped

#### Actual Behavior

mat select dropdown is not getting adjusted on top and is getting clipped

#### Environment

- Angular: 16.1.5
- ngx-scrollbar: 13.0.2
- Browser(s): 
- Operating System (e.g. Windows, macOS, Ubuntu):

**Comment by MurhafSousli** [comment]
The `MatSelect` component cannot maintain the scroll position since its scrollable viewport has changed.

Here is a workaround that uses the `opened` output to manually scroll to the selected item, but it isn't ideal since there is a tiny delay from the opened output [stackblitz](https://stackblitz.com/edit/ngx-scrollbar-yxbhti?file=src%2Fapp%2Fscroll-event-example%2Fscroll-event-example.html,src%2Fapp%2Fscroll-event-example%2Fscroll-event-example.ts)

Maybe you can find a solution with a faster event like combining click event with selected output and scroll to element position asap

**Comment by MurhafSousli** [comment]
I am working on an refactor the uses the same original viewport but its still under development.

**Comment by vartikaagrawal411** [comment]
Hi, Thanks for your suggestion but the workaround you have mentioned will probably not applicable in my case.

 The issue is not related to the scroll behavior change on click of dropdown. The ideal behavior is the dropdown options overlay to open with proper position so that the content is visible in the view port. (Current behavior is dropdown options overlay is opening on the **_lower side_**  of the box, and due to this options are getting trimmed/not visible. Ideally it would have auto adjusted and came on the **_upper side_**  of the box)

_Issue_
![image](https://github.com/MurhafSousli/ngx-scrollbar/assets/149461813/0daf5f17-2300-4746-847b-e88a4e6dc3f3)

_Expected_

![image](https://github.com/MurhafSousli/ngx-scrollbar/assets/149461813/9b8ebf1b-4a23-4562-aef1-27dc0b9ce0d3)

**Comment by MurhafSousli** [comment]
In the stackblitz it open as expected! it open at the upper side when there is not enough space at the bottom.

I am not sure if I understood your issue, could you add two select controls next to each other and show the difference

**Comment by vartikaagrawal411** [comment]
yes I have added both expected and current behavior dropdowns in scroll event page.. one with [autoHeightDisabled]="false" and one without it.. please check it now

**Comment by MurhafSousli** [comment]
Now I see it, yea so the mat-select decides where the panel should go, and initially when autoHeight is enabled it won't detect its height. why is auto-height needed in your use case?

**Comment by vartikaagrawal411** [comment]
Incase I don't give [autoHeightDisabled]="false", I need to specify height to my ngx scrollbar.. Without it my mat-select come as blank. I need to get data in mat-select from an Api, now data can be 1 or 16 so I don't want to give specific height to my scrollbar as it will create extra space in it. This is the reason I am using [autoHeightDisabled]="false" without height. I have made some changes in stackblitz.. you can see the difference between the three form fields.

**Comment by MurhafSousli** [comment]
This will be fixed in the next version

**Comment by skinet2009** [comment]
@MurhafSousli 
Please tell me when the new version is planned to be released?

**Comment by MurhafSousli** [comment]
> @MurhafSousli Please tell me when the new version is planned to be released?

Its almost done, needs to update the documentation and release, either by the end of this weekend or next week. I will ping you here.

**Comment by skinet2009** [comment]
@MurhafSousli 
Please tell me, will there be support for the solution for Angular 16?

**Comment by MurhafSousli** [comment]
I am not sure, try it out!

**Comment by skinet2009** [comment]
> I am not sure, try it out!
> 
> Add the following in your package.json
> 
> ```
>  "overrides": {
>     "ngx-scrollbar": {
>         "@angular/common": "^16.0.0",
>         "@angular/core": "^16.0.0",
>         "@angular/cdk": "^16.0.0"
>      }
>   }
> ```

Unfortunately, Angular does not support using libraries with a higher version of Angular.
Can't you apply the solution to fix this bug for ngx-scrollbar version 13?

**Comment by MurhafSousli** [comment]
No, its not possible.
