### ISSUE TITLE
Scrollbar doesn't work with max-height

### ISSUE THREAD

**Issue by rbehun** [MurhafSousli/ngx-scrollbar#54]
### Bug Report or Feature Request (mark with an `x`)
```
- [X ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] question
```

### OS and Version?
> Ubuntu 16.04 

### Versions
Angular CLI: 6.0.8
Node: 8.11.2
OS: linux x64
Angular: 6.0.5

### Repro steps
1. Create the container with some max-height css value. 
2. Scrollbar doesn't appear. 

### Desired functionality
It should work with max-height property. Probably the same story with max-width.

**Comment by MurhafSousli** [comment]
That's how the browser works, whatever works with the native scroll div should work with this plugin.
