### ISSUE TITLE
Move incorrectly in case of the content full of link

### ISSUE THREAD

**Issue by linhkk3214** [MurhafSousli/ngx-scrollbar#544]
#### Reproduction

https://stackblitz.com/edit/ngx-scrollbar-5fhagk?file=src%2Fapp%2Frouting.module.ts,src%2Fapp%2Fhome%2Fhome.component.html,src%2Fapp%2Fhome%2Fhome.component.ts,src%2Fapp%2Fhome%2Fhome.component.scss

Steps to reproduce:
1. Setting up the scrollable content with full of links (with style "width: 100%; display: block")
2. Dragging the thumb to scroll
 
 
#### Expected Behavior

The thumb can move correctly

#### Actual Behavior

The thumb moves a bit (also have a link at the mouse pointer)

#### Environment

- Angular:
- ngx-scrollbar: v13
- Browser(s): Edge
- Operating System (e.g. Windows, macOS, Ubuntu): Windows

**Comment by MurhafSousli** [comment]
In v13, you can use `<ng-scrollbar pointerEventsMethod="scrollbar">` [fixed stackblitz](https://stackblitz.com/edit/ngx-scrollbar-3derat?file=src%2Fapp%2Frouting.module.ts,src%2Fapp%2Fhome%2Fhome.component.html,src%2Fapp%2Fhome%2Fhome.component.ts,src%2Fapp%2Fhome%2Fhome.component.scss)

In v14 (currently in beta), it will work out of the box.

**Comment by linhkk3214** [comment]
It works. Thanks.
