### ISSUE TITLE
Import error in Node Module

### ISSUE THREAD

**Issue by JahzanA-Visma** [MurhafSousli/ngx-scrollbar#556]
#### What are you trying to do?

During npm start

#### What troubleshooting steps have you tried?

What are you seeing that does not match your expectations? 

#### Reproduction

Steps to reproduce:
1. Install the latest beta version
2. Npm Start the project
  
#### Environment

- Angular: 17.1.0
- ngx-scrollbar: 14.0.0-beta.5
- Browser(s): Chrome
- Operating System - Windows

**Comment by MurhafSousli** [comment]
What is the error?
