### ISSUE TITLE
ERROR TypeError: Animation.currentTime setter: Value being assigned is not a finite floating-point value.

### ISSUE THREAD

**Issue by PSeilheimer** [MurhafSousli/ngx-scrollbar#558]
I am using the Core UI Pro Admin Template in a very simple application and tried to implement ngx-scrollbar.

What are you trying to do?

I want ngx-scrollbar to be the scrollbar used by my sidebar-nav. Nothing fancy, i just dig the design.
```
<ng-scrollbar>
      <c-sidebar-nav [navItems]="navItems" dropdownMode="close"></c-sidebar-nav>
</ng-scrollbar>
```

What are you seeing that does not match your expectations? 

Thats the funny thing. The scrollbar workd perfectly but for one frame right after loading a page or refreshing, i get a weird icon and the error ERROR TypeError: Animation.currentTime setter: Value being assigned is not a finite floating-point value.
I am not doing anything with animation and the error goes away when i stop using the scrollbar.

Any idea why that is? 

Thanks from a Junior Dev :)

  
#### Environment

- Angular: 17.2.2
- ngx-scrollbar: 14.0.0-beta.0
- Browser(s): Firefox
- Operating System: Windows 11

**Comment by MurhafSousli** [comment]
Hi @PSeilheimer the best way is to reproduce the issue in a stackblitz so I can look at it.

I would also recommend upgrading to beta.5

**Comment by MurhafSousli** [comment]
If we can't reproduce the issue we cannot do anything about it
