### ISSUE TITLE
Dragging scrollbar on phone doesn't work 

### ISSUE THREAD

**Issue by sisasam** [MurhafSousli/ngx-scrollbar#561]
#### Reproduction

Been looking around on the test website on my phone and noticed that i cant seem to drag the scrollbar with my fingers.
Reproducible on IPhone 12
 
#### Expected Behavior

I would have expected to be able to use my fingers to drag the scrollbar to the desired position.

#### Actual Behavior

I could not seem to be able to drag the scrollbar with my fingers. 
I could scroll but selecting the scroll bar to drag it was impossible. 

#### Environment

- Browser(s): Chrome, Safari
- Operating System (e.g. Windows, macOS, Ubuntu): iOS 17.4

**Comment by MurhafSousli** [comment]
Which version are you using?

**Comment by sisasam** [comment]
I was just running your Examples on your demo pagehttps://ngx-scrollbar-next.netlify.app/#/Also here are Browser verions:Safari: 17.4Chrome: 122.6261.89On 18. Mar 2024, at 03:14, Murhaf Sousli ***@***.***> wrote:﻿
Which version are you using?

**Comment by MurhafSousli** [comment]
I deployed a new version and tried it on iphone safari browser and it worked, please try again!

**Comment by sisasam** [comment]
I have now tried it again and it was an improvement. 
I seem to get it to work even though the hitbox still seems to be a little narrow. 
I still had some problems hitting the scrollbar. 
Thanks very much though.

**Comment by MurhafSousli** [comment]
@sisasam I know, you can increase the thickness of the scrollbar but I think that's the way it is, scrollbar are not meant to be dragged over mobile devices
