### ISSUE TITLE
keyboard scrollable 

### ISSUE THREAD

**Issue by deeptikoneclick** [MurhafSousli/ngx-scrollbar#563]
how can I make it scroll with the keyboard up- down keys?
<ng-scrollbar
      class="custom_scroll_suggetion"
      barClass="scrollbar"
      customview="true"
      #scrollable
      track="vertical"
      pointerEventsMethod="scrollbar"
      [position]="native"
      [autoHeightDisabled]="false"
      tabindex="0"
    >
    this is my existing code

**Comment by deeptikoneclick** [comment]
I'm using 10.0.1 version

**Comment by deeptikoneclick** [comment]
when i click on keyboard up down arrow key, it is not working properly

**Comment by MurhafSousli** [comment]
Keyboard seem to work properly in v14, try to upgrade if there is an issue let me know.. closing this for now
