### ISSUE TITLE
Integration with Handsontable

### ISSUE THREAD

**Issue by dfmmalaw** [MurhafSousli/ngx-scrollbar#570]
Is there any way to use ngx-scrollbar with [handsontable](https://github.com/handsontable/handsontable)?

I tried like this

`<ng-scrollbar externalViewport=".ht_master" externalContentWrapper=".wtHolder" asyncDetection>
            <hot-table [hotId]="id" [settings]="hotSettings" licenseKey='non-commercial-and-evaluation'>
            </hot-table>
          </ng-scrollbar>`

But it's not working and hot-table has 0 px height.
Please suggest how I can replace the scrollbar inside hot-table with ngx-scrollbar.

Thank you!

**Comment by MurhafSousli** [comment]
I cannot access their stackblitz, can you make a stackblitz reproduction that I can have a look at?

**Comment by dfmmalaw** [comment]
@MurhafSousli I tried your code, but it didn't work. It didn't render the hot-table.

https://stackblitz.com/edit/handsontable-angular?file=app%2Fapp.component.ts

**Comment by MurhafSousli** [comment]
@dfmmalaw  You sent a reproduction with Angular 5, I need a reproduction with Angular 17

**Comment by MurhafSousli** [comment]
I reproduce it for you, here is a working stackblitz https://stackblitz.com/edit/stackblitz-starters-ehhvhk

In my opinion, Handsontable is not well implemented. it seems to use old techniques. but maybe you can work on overriding the table CSS  to enhance the appearance.
