### ISSUE TITLE
Issues after upgrading to 14

### ISSUE THREAD

**Issue by Sergiobop** [MurhafSousli/ngx-scrollbar#571]
I will open some issues im facing while trying to upgrade to 14.

#### Reproduction

https://stackblitz.com/edit/ngx-scrollbar-al31ak?file=src%2Fmain.scss

Steps to reproduce:
1. Im trying to make a example with CDK Virtual Scroll
2. The problem is, i need both horizontal and vertical scrolling. Only vertical is working
 
 I can still scroll horizontally, but the vertical scrollbar is stuck in the middle, and the horizontal scrollbar is not displaying:
 
<img width="469" alt="Captura de pantalla 2024-04-01 a las 21 49 09" src="https://github.com/MurhafSousli/ngx-scrollbar/assets/73531831/e6b99c4d-c2d9-4083-a360-9034849dfe84">

Scrolling to the "right" in the horizontal axis:
<img width="465" alt="Captura de pantalla 2024-04-01 a las 21 49 24" src="https://github.com/MurhafSousli/ngx-scrollbar/assets/73531831/32f02b86-f720-4293-bbcf-30b1d3914bb6">

**Comment by MurhafSousli** [comment]
The virtual scroll component is designed to scroll in one direction, and this plugin utilizes its spacer element that is being using internally for calculation stuff and it isn't designed to fit the width. in short you should not be able to scroll horizontally when you are using virtual scroll.

**Comment by Sergiobop** [comment]
Hi, thank you for your response @MurhafSousli 

I understand what you are saying, but the thing is, this worked fine in 13 and i need the same behaviour:
https://stackblitz.com/edit/ngx-scrollbar-fxwnb2?file=src%2Fmain.ts

<img width="616" alt="Captura de pantalla 2024-04-02 a las 9 08 15" src="https://github.com/MurhafSousli/ngx-scrollbar/assets/73531831/1c0bb578-072d-4fdc-82c2-c66b4522338c">

**Comment by MurhafSousli** [comment]
In v13 we were using `scrollHeight` and `scrollWidth` of the viewport, but that had many down sides in calculation, now we use content wrapper dimension.

Anyway, I figured out a workaround by just making the spacer element width equal to the content wrapper.

```ts
  ngAfterViewInit(): void {

    setTimeout(() => {
      const contentWrapper: HTMLElement = document.querySelector('.cdk-virtual-scroll-content-wrapper');
      const spacer: HTMLElement = document.querySelector('.cdk-virtual-scroll-spacer');
  
      spacer.style.width = `${contentWrapper.clientWidth}px`;
    });
  }
```
Maybe you can find a better hook to update the width when your content virtual scroll content changes.

Here is an [update stackblitz](https://stackblitz.com/edit/ngx-scrollbar-dernxq?file=src%2Fmain.scss,src%2Fmain.ts,tsconfig.json)

**Comment by Sergiobop** [comment]
You are the best @MurhafSousli . Thank you for all your work, i'm using some of your packages and you are one of the better open source maintainers i've ever meet.

If that works internally would be neat

Thanks again
