### ISSUE TITLE
Content Security Policy violation for script-src

### ISSUE THREAD

**Issue by Smarthard** [MurhafSousli/ngx-scrollbar#572]
#### What are you trying to do?

I'm using ngx-scrollbar for my web-extenstion pet-project. It works as intended until I try to actually build and pack it into browser extension:

<img width="662" alt="Снимок экрана 2024-04-08 в 07 39 08" src="https://github.com/MurhafSousli/ngx-scrollbar/assets/24275139/fae3e479-76c3-4885-937f-cf3f7acb9ee1">

As you could see whenever it's loaded as extension I receive this CSP warning with message about failing to load remote script which refers to `https://flackr.github.io/scroll-timeline/dist/scroll-timeline.js`.

#### What troubleshooting steps have you tried?

It fixes with no issues if I update my extension's `manifest.json` CSP rules with something like:

```json
    "content_security_policy": "script-src 'self' https://flackr.github.io"
```

...but in fact I don't really want to do it, because remote code is severely dangerous thing to leave. And it will cause review issues if I actually try to release it to stores like AMO or CWS.

Could we somehow pack this code into ngx-scrollbar package please?

#### Reproduction

Stackblitz example won't really help here because you couldn't reproduce this issue there (you need this code to be loaded as web extension). But if you need it I would create reproduction repository with instructions

#### Environment

- Angular: 17
- ngx-scrollbar: 14
- Browser(s): Firefox 124
- Operating System (e.g. Windows, macOS, Ubuntu): any

**Comment by MurhafSousli** [comment]
I tried to pack the polyfill, but it didn't work with me. it seems that it only work when loaded via script element. what you can do is host the script on your own server or use a trusted CDN.

This is the polyfill repo https://github.com/flackr/scroll-timeline

```ts
import { ApplicationConfig } from '@angular/core';
import { provideScrollbarOptions } from 'ngx-scrollbar';

export const appConfig: ApplicationConfig = {
  providers: [
    provideScrollbarPolyfill(LINK_TO_POLYFILL)
  ]
};
```

If you think you can make the polypill work internally and lazy load it using `import()` I would appreciate a PR.

**Comment by Smarthard** [comment]
@MurhafSousli thank you for the quick response! I'll try to dig into it and create a PR when it's done

**Comment by Smarthard** [comment]
I was able to add that script into ngx-scrollbar repository and made it running here: https://github.com/Smarthard/ngx-scrollbar/commit/6505bab62928307e0e3813c6482cbd8bb7fe9762

However I still need to figure a couple of things:

- Test case from `scrollbar-manager.spec.ts` is failing ([in line #39](https://github.com/Smarthard/ngx-scrollbar/blob/master/projects/ngx-scrollbar/src/lib/tests/scrollbar-manager.spec.ts#L39))
- I'd prefer `flackr/scroll-timeline` to be a part of `package.json` dependecies list but it's not shipping yet with compiled `dist` folder (https://github.com/flackr/scroll-timeline/issues/57)

**Comment by MurhafSousli** [comment]
You won't have problems running it locally, the problem is with shipping it with the package using `ng-packagr`.  we can ship it as an assets in the package like styles / themes... etc. user will still have to link the script when importing the library manually, but I think that's ok.

**Comment by Smarthard** [comment]
> we can ship it as an asset in the package like styles / themes...

Yep, that's how I did it. But I didn't need to load it manually. Am I missing something?

**Comment by MurhafSousli** [comment]
Ok, try and we can see the result. it also better not to load /activate it when browser support it natively like chrome

**Comment by Coffee-Tea** [comment]
Hi, @Smarthard let me ask how things are going on with the issue? Any success after this https://github.com/MurhafSousli/ngx-scrollbar/issues/572#issuecomment-2043527782?

Thanks!
