### ISSUE TITLE
cdkVirtualScrollViewport got dependency of @angular/material/select

### ISSUE THREAD

**Issue by TekVanDo** [MurhafSousli/ngx-scrollbar#573]
#### Reproduction

Use StackBlitz to reproduce your issue: https://stackblitz.com/edit/stackblitz-starters-aqrbus?file=src%2Fmain.ts

If use cdkVirtualScrollViewport  withot installed @angular/material/select dependency it is throw an error

`ERROR in ./node_modules/ngx-scrollbar/fesm2022/ngx-scrollbar-utils.mjs 3:0-53
Module not found: Error: Can't resolve '@angular/material/select' in 'C:\projects\ep-ui\node_modules\ngx-scrollbar\fesm2022'
`
 
 
#### Environment

- Angular: 17
- ngx-scrollbar: 14

**Comment by MurhafSousli** [comment]
Hmmm, seems like we need to split it into different packages.

By the time this is fixed, you can use the following code  https://stackblitz.com/edit/stackblitz-starters-zp7r7x?file=src%2Fmain.ts
