### ISSUE TITLE
Rename of the track input in v14 not documented

### ISSUE THREAD

**Issue by PauAbellaMolina** [MurhafSousli/ngx-scrollbar#575]
#### Documentation Feedback

Reading through the [changelog](https://github.com/MurhafSousli/ngx-scrollbar/blob/master/CHANGELOG.md) and the [v14 usage page](https://github.com/MurhafSousli/ngx-scrollbar/wiki/usage) I didn't find any reference to the rename made to the _track_ input.
In v14 it seems to be called _orientation_.

I suggest changing _[track]_ to _[orientation]_ [here](https://github.com/MurhafSousli/ngx-scrollbar/wiki/usage#ngscrollbar-api) and pointing out the change on the changelog.

**Comment by PauAbellaMolina** [comment]
It is correctly documented on the v14 global options page btw.
[See here](https://github.com/MurhafSousli/ngx-scrollbar/wiki/global-options#ngscrollbaroptions-api)

**Comment by MurhafSousli** [comment]
@PauAbellaMolina  Thanks for pointing this out, I updated the wiki for now
