### ISSUE TITLE
Typo on ViewportAdapter contentWidth() getter comment/explanation

### ISSUE THREAD

**Issue by PauAbellaMolina** [MurhafSousli/ngx-scrollbar#576]
#### Documentation Feedback

Not sure if this is a documentation related issue but I found a copy paste typo on projects/ngx-scrollbar/src/lib/viewport/viewport-adapter.ts

![image](https://github.com/MurhafSousli/ngx-scrollbar/assets/62839680/228b9d3f-2a66-49ed-9bb6-1a21e049ee2b)

Line 46 should be /** Content width, falls back to scroll **_width_** */

**Comment by MurhafSousli** [comment]
Good point, need to fix the comments!

**Comment by PauAbellaMolina** [comment]
Also found this [here](https://github.com/MurhafSousli/ngx-scrollbar/blob/c0ea0d93b73575ae95ab7fd6cade410e8c1ca767/projects/ngx-scrollbar/src/lib/ng-scrollbar-core.ts#L204), should be _native_

![image](https://github.com/MurhafSousli/ngx-scrollbar/assets/62839680/86c917b6-0176-42ba-93cc-cb5fa9225747)
