### ISSUE TITLE
Is it possible to manage a horizontal scroll with the mouse wheel?

### ISSUE THREAD

**Issue by AdrianAgui** [MurhafSousli/ngx-scrollbar#579]
#### What are you trying to do?

I need to implement a horizontal scroll on the ngx-scrollbar component with the mouse wheel

#### What troubleshooting steps have you tried?

I tried a workaround, when I am hover the html element i keypress shift key so that then the mouse wheel should scroll in the x-axis (shift + wheel scrolls in horizontal way). 
But it doesn't work although in theory shift key is pressed with the last workaround while I manually do scroll with mouse wheel.

Also, I read the docs but I didn't seen anything for cover this functionality.

#### Environment

- Angular:
- ngx-scrollbar (v12.0.1)
- Chrome / Edge
- Windows

**Comment by MurhafSousli** [comment]
No, but you can easily accomplish this with the following code

```ts
this.scrollbar.viewport.nativeElement.addEventListener('wheel', (event) => {
  event.preventDefault();
  this.scrollbar.viewport.scrollXTo(this.scrollbar.viewport.scrollLeft + event.deltaY);
});
```

Here is a [stackblitz](https://stackblitz.com/edit/ngx-scrollbar-s5a7p8?file=src%2Fmain.ts)
