### ISSUE TITLE
always is not assignable to visibility in html after upgrade to 14.

### ISSUE THREAD

**Issue by mobile-xl** [MurhafSousli/ngx-scrollbar#580]
After update 14 my in-HTML code causes an error making me unable to serve/build my angular application

`<ng-scrollbar id="inner-scrollbar" visibility="always" #scrollable track="vertical">
 ...
</ng-scrollbar>`

`Type '"always"' is not assignable to type 'ScrollbarVi...

<ng-scrollbar id="inner-scrollbar" **_visibility_**="always" #scrollable track="vertical">`

#### What are you trying to do?

I have nested scrollbars to display a table. The horizontal includes the table headers while the vertical does not. 
  
#### Environment

- Angular: 17.3.4
- ngx-scrollbar: 14.0.0
- Browser(s): any
- Operating System (e.g. Windows, macOS, Ubuntu):  Windows

**Comment by MurhafSousli** [comment]
There are some breaking changes, have a look at the [changelog](https://github.com/MurhafSousli/ngx-scrollbar/blob/master/CHANGELOG.md#breaking-changes-4).

The visibility option `always` was renamed to `visible`
