### ISSUE TITLE
Scrollbar thinks viewport width is same as content on some cases so there is no scroll

### ISSUE THREAD

**Issue by PauAbellaMolina** [MurhafSousli/ngx-scrollbar#583]
#### Reproduction

See here: https://stackblitz.com/edit/ngx-scrollbar-h46srq?file=src%2Fmain.ts

Steps to reproduce:
1. Have a parent component render a child one which has an ng-scrollbar with content that exceeds the viewport.
2. Add :host { display: grid; } to the parent component.
3. You will see how the scrollbar extends to the full width of the content inside of it, so no scroll and elements exceed viewport.
 
 
#### Expected Behavior

Ng-scrollbar making it's contents scrollable so it doesn't exceed viewport boundaries.

#### Actual Behavior

When a parent component has host { display: grid; } and a child component which contains the ng-scrollbar doesn't, ng-scrollbar turns as wide as it's content so it exceeds viewport boundaries and doesn't make it's content scrollable (as expected since nothing technically exceeds the scrollbar and so nothing needs to be scrollable).

Scrollbar sets the viewport width variables to the same value as content width and these are not getting updated when resizing the viewport.

<img width="836" alt="Screenshot 2024-04-22 at 18 01 33" src="https://github.com/MurhafSousli/ngx-scrollbar/assets/62839680/258fa294-60b2-401e-9b79-0d547c0f3a95">

#### Environment

- Angular: 17.3.1
- ngx-scrollbar: 14.1.0
- Browser(s): Arc Browser / Stackblitz integrated browser (both Chromium in the end I think)
- Operating System: macOS

**Comment by MurhafSousli** [comment]
The scrollbar viewport is designed to behave same as a native element would, you should find out the proper styles that makes grid child not exceed the parent width.

**Comment by PauAbellaMolina** [comment]
You are right, it is behaving as a native element would. I thought this was not the intended behaviour since this happened after updating to v14.
