### ISSUE TITLE
Integration failed with primeng if appendTo="body"

### ISSUE THREAD

**Issue by Kamma31** [MurhafSousli/ngx-scrollbar#584]
#### Reproduction

Steps to reproduce:
1. Use ng-scrollbar integration with primeng component (ex: dropdown, multiselect)
2. Add attribute appendTo="body" to primeng component
 
 
#### Expected Behavior

What behavior were you expecting to see?
Expect to have the same result with or without appendTo attribute

#### Actual Behavior

What behavior did you actually see?

ng-scrollbar doesn't work when  appendTo="body"

#### Environment

- Angular: ^17.3.5
- ngx-scrollbar: ^14.1.0
- primeng: ^17.14.1
- Browser(s): Tested on Chrome, Firefox
- Operating System (e.g. Windows, macOS, Ubuntu): Tested on Windows

**Comment by MurhafSousli** [comment]
Closing as inactive, feel free to reopen when you have reproduction!
