### ISSUE TITLE
Make ng-scrollbar work with mat-dialog

### ISSUE THREAD

**Issue by Sergiobop** [MurhafSousli/ngx-scrollbar#587]
#### Reproduction

https://stackblitz.com/edit/ngx-scrollbar-ctpzbo

Steps to reproduce:
1. Use the ng-scrollbar within a mat-dialog with scrollable content (Example taken from angular material docs)
2. The scrollbar is still the default even with the mat-dialog-content is scrollable
 
 
#### Expected Behavior

My custom and beautiful ng-scrollbar displaying in the mat-dialog

#### Actual Behavior

The package does not work in mat dialogs with scrollable content.

#### Environment

- Angular: 17
- ngx-scrollbar: 14

**Comment by MurhafSousli** [comment]
Here you go https://stackblitz.com/edit/ngx-scrollbar-tkzscf

**Comment by Sergiobop** [comment]
Thanks @MurhafSousli 

Do you think this one is going to change the workaround? https://github.com/angular/components/pull/28963

Maybe we should add this to the Wiki

**Comment by MurhafSousli** [comment]
Not sure what you mean, which is this one and which is the workaround!
