### ISSUE TITLE
Uncaught TypeError: Animation.currentTime setter: Value being assigned is not a finite floating-point value

### ISSUE THREAD

**Issue by jpike88** [MurhafSousli/ngx-scrollbar#590]
Error on Firefox, on latest angular dependencies.

I updated using this approach, using npm-check-updates tool:

`ncu "/^@angular[/|-].*$/" --target @next -u && npm I`

Aside from the error, seems like the library works fine otherwise

Error contents below:

Uncaught TypeError: Animation.currentTime setter: Value being assigned is not a finite floating-point value.
    ct proxy-animation.js:481
    mt proxy-animation.js:669
    xe scroll-timeline-base.js:44
    Ie scroll-timeline-base.js:237
    Angular 13
    Ie scroll-timeline-base.js:232
    e scroll-timeline-base.js:287
    Re scroll-timeline-base.js:285
    ScrollTimeline scroll-timeline-base.js:394
    startPolyfill ngx-scrollbar.mjs:725
    _ThumbAdapter ngx-scrollbar.mjs:692
    Angular 26
        runEffect
        watcher
        run
        run
        flushQueue
        flush
        invoke
        onInvoke
        invoke
        run
        flush
        scheduleEffect
        invokeTask
        runTask
        drainMicroTaskQueue
        promise callback*nativeScheduleMicroTask
        scheduleMicroTask
        scheduleTask
        scheduleTask
        scheduleMicroTask
        patchQueueMicrotask
        name
        scheduleEffect
        schedule
        watcher
        consumerMarkedDirty
proxy-animation.js:481
    ct proxy-animation.js:481
    mt proxy-animation.js:669
    xe scroll-timeline-base.js:44
    Ie scroll-timeline-base.js:237
    Angular 13
    Ie scroll-timeline-base.js:232
    e scroll-timeline-base.js:287
    (Async: ResizeObserverCallback)
    Re scroll-timeline-base.js:285
    ScrollTimeline scroll-timeline-base.js:394
    startPolyfill ngx-scrollbar.mjs:725
    _ThumbAdapter ngx-scrollbar.mjs:692

<img width="768" alt="Screenshot 2024-05-06 at 12 15 25 PM" src="https://github.com/MurhafSousli/ngx-scrollbar/assets/9585787/381c9219-1ef4-494b-a81c-b232ab28212a">

**Comment by MurhafSousli** [comment]
Please add a stackblitz reproduction https://stackblitz.com/edit/ngx-scrollbar

**Comment by kukjevov** [comment]
Here is reproduction.

> `git clone https://github.com/kukjevov/ng-universal-demo`
> `cd ng-universal-demo`
> `git checkout scrollbar/2.0`
> `npm install`
> `npm start`
> open url in *Firefox* (126, 127) `http://localhost:8888`

And there you go, there is an error in console.

Hope this helps

**Comment by MurhafSousli** [comment]
There is an authentication page, I cannot access!

**Comment by kukjevov** [comment]
Hello.

To access page you enter credentials `admin` `admin`.
There no unofficial build system we are using Angular CLI. And we are using your provide function `provideScrollbarPolyfill('assets/scroll-timeline-polyfill.js'),` to provide polyfill locally.

**Comment by kukjevov** [comment]
Hello.

This is even more interesting than i thought. Mentioned error also occurred on your own demo, so you dont really need reproduction. 

https://ngx-scrollbar.netlify.app/#/

Yesterday i came to your demo and wondered why it is not working. Then i opened it in chrome and it was working. What is even more interesting, today i opened firefox and everything is working and there is no error in console. Have no clue what happened.
