### ISSUE TITLE
"Integrate with CDK Drag and Drop" stackblitz app doesn't work

### ISSUE THREAD

**Issue by dmmishchenko** [MurhafSousli/ngx-scrollbar#592]
#### Documentation Feedback

Steps to reproduce: 

1. Go to integrate section in Docs https://github.com/MurhafSousli/ngx-scrollbar/wiki/Integration-(legacy)#integrate-with-cdk-drag-and-drop
2. Click "Demo: https://stackblitz.com/edit/ngx-scrollbar-cdk-drag-drop"
3. See error in application window: 
> Error in src/styles.scss
> Error: ENOENT: No such file or directory., '/dev/null'

**Comment by MurhafSousli** [comment]
This error occurs with older stackblitz using older Angular versions, which is irrelevant to the scrollbar

**Comment by dmmishchenko** [comment]
How I can help you to fix this? Maybe I can create a new stackblitz example?

**Comment by MurhafSousli** [comment]
A new stackblitz reproduction with angular 17 or 18 should be work fine

**Comment by MurhafSousli** [comment]
Closing as inactive, feel free to reopen when you have reproduction!
