### ISSUE TITLE
Impossible to detect scroll position change

### ISSUE THREAD

**Issue by FarhadMGN** [MurhafSousli/ngx-scrollbar#593]
#### Reproduction

Trying to handle change position like this - https://github.com/MurhafSousli/ngx-scrollbar/wiki/scroll-event

@ViewChild(NgScrollbar) scrollbarRef: NgScrollbar;

in afterViewInit:
this.scrollbarRef.scrolled.pipe().subscribe((pos) => console.log(pos));

 
 
#### Expected Behavior
It works

#### Actual Behavior
Got the error -  Property 'scrolled' does not exist on type 'NgScrollbar'

How can i do it?
I use "ngx-scrollbar": "14.1.0"

**Comment by MurhafSousli** [comment]
This is old documentation for v13. in v14 and above, you should get a reference of the nativeElement then use the scroll event listener `fromEvent(scrollbarRef.viewport.nativeElement, 'scroll').pipe()`.
