### ISSUE TITLE
scrollTimelinePolyfill is causing errors

### ISSUE THREAD

**Issue by Sergiobop** [MurhafSousli/ngx-scrollbar#594]
#### Expected Behavior

No errors

#### Actual Behavior

I'm using Sentry, and my error log is full of TypeErrors caused by the polyfill. I don't know if we can do something to avoid them.

I will paste some errors:

1 TypeError setNativeCurrentTime(scroll-timeline/src/proxy-animation)
```
TypeError
Animation.currentTime setter: Value being assigned is not a finite floating-point value.
```
Sentry points at line 480: setNativeCurrentTime at line 480:42 of https://flackr.github.io/scroll-timeline/src/proxy-animation.js
```
timeline.currentTime &&
timeline.currentTime.value == (playbackRate < 0 ? 0 : 100);
const delta = atScrollTimelineBoundary ? (playbackRate < 0 ? 0.001 : -0.001) : 0;
details.animation.currentTime = time + delta; // This one
```

2 TypeError The provided value is non-finite (same line, details.animation.currentTime = time + delta;)
```
The provided value is non-finite
``` 

#### Environment

- Angular: 17
- ngx-scrollbar: 14.1

Looks like other people have the problem too:
https://github.com/flackr/scroll-timeline/issues/254#issuecomment-2095226901

**Comment by MurhafSousli** [comment]
The demo works fine in FireFox? you guys must have been running it in different environment, please add a reproduction or more info because I cannot reproduce it

**Comment by MurhafSousli** [comment]
I am not familiar with Sentry, but I guess I get the idea, you need to find an option in Sentry to ignore this file. the polyfill is pure JS, and has no types and these kind of systems will always complain about typo stuff. The polyfill is outside our control.
