### ISSUE TITLE
SSR with CDK Virtual Scroll: ResizeObserver is not defined error thrown

### ISSUE THREAD

**Issue by kanehjeong** [MurhafSousli/ngx-scrollbar#603]
This happened when upgrading to ngx-scrollbar 15 and swapping out the `scrollViewport` for the `externalViewport` with the `cdkVirtualScrollViewport` as mentioned in this integration [docs here](https://github.com/MurhafSousli/ngx-scrollbar/wiki/Integration). This is assumed to be because ResizeObserver is being used somewhere without properly handling a case where the scroll is rendered server side.

Everything works fine once it is hydrated through CSR on the browser, so it's really just a minor inconvenience with the error logging.

#### Reproduction

Couldn't easily add @angular/ssr in the StackBlitz, but I've uploaded a screen shot of the code here.

<img width="400" alt="Screenshot 2024-06-06 at 2 31 07 AM" src="https://github.com/MurhafSousli/ngx-scrollbar/assets/3455022/10a80fff-cb3c-4d12-bc82-e4094e8a2c54">
<img width="994" alt="Screenshot 2024-06-06 at 2 31 42 AM" src="https://github.com/MurhafSousli/ngx-scrollbar/assets/3455022/9087668c-f879-416d-b561-3be26b969f45"> 
 
#### Expected Behavior

What behavior were you expecting to see?
No error when loading ng-scrollbar with cdk virtual scroll on the server using angular ssr

#### Actual Behavior

What behavior did you actually see?
An error in the server side console logs.  

#### Environment

- Angular: 18.0.1
- ngx-scrollbar: 15.0.0
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): macOS and Windows

**Comment by MurhafSousli** [comment]
The demo app is built with SSR, I don't get this error, could you tell if there is a difference between the demo app SSR and the SSR you use in your app? https://ngx-scrollbar.netlify.app/#/material

**Comment by MurhafSousli** [comment]
I just publish a beta release  15.0.1-beta.0, could you try if this fixes the issue?

**Comment by kanehjeong** [comment]
@MurhafSousli Tested 15.0.1-beta.0 and it works great 👍.
