### ISSUE TITLE
Style variables do not work

### ISSUE THREAD

**Issue by iMogs370** [MurhafSousli/ngx-scrollbar#606]
Here are my styles provided in styles.scss:
:root {
--scrollbar-thumb-color: rgba(255, 0, 0, 0.2) !important;
  --scrollbar-track-color: red;
}

Element:
<ng-scrollbar [orientation]="'vertical'" [visibility]="'native'">
![global](https://github.com/MurhafSousli/ngx-scrollbar/assets/90991324/ad6d81d6-cac6-4e9b-a952-d9801a066944)

 
 
#### Expected Behavior

What behavior were you expecting to see?
Track color to go red, thumb to go redish as set in the variables

#### Actual Behavior

What behavior did you actually see?
When inspecting the css in the chrome inspector, the global variables are stricken out and the vars on the element are being used. The scrollbar is in it's default settings/colors.

#### Environment

- Angular: 18
- ngx-scrollbar: latest
- Browser(s): chrome
- Operating System (e.g. Windows, macOS, Ubuntu):  windows

**Comment by MurhafSousli** [comment]
For the time being, you should use the element selector to override the CSS variables, we still need to improve it #591
