### ISSUE TITLE
RTL Mode Not Work

### ISSUE THREAD

**Issue by ct-dixit** [MurhafSousli/ngx-scrollbar#608]
#### Reproduction

Use StackBlitz to reproduce your issue: https://stackblitz.com/edit/ngx-scrollbar

Steps to reproduce:
1. https://stackblitz.com/edit/ngx-scrollbar-c9h1du?file=src%2Fmain.ts

I have added the RTL mode direction in the ng-scrollbar but this not working
`<ng-scrollbar buttons [dir]="'rtl'">`

also, check the attachment stack blitz link.

![Screenshot 2024-06-13 124105](https://github.com/MurhafSousli/ngx-scrollbar/assets/106728438/c143515c-43b3-4a85-bfba-b365e9e134db)

#### Environment

- Angular: 18
- ngx-scrollbar: 15.0.0
- Browser(s):chrome
- Operating System (e.g. Windows, macOS, Ubuntu): window

**Comment by MurhafSousli** [comment]
This is not the way it works, you have two options:

- To make a webpage RTL, add the attribute to the html file `<html dir="rtl">`
- Or use `BidiModule` from Angular CDK as in this stackblitz  https://stackblitz.com/edit/ngx-scrollbar-trksk4?file=src%2Fmain.ts,src%2Findex.html
