### ISSUE TITLE
Ngx-scrollbar - After scrolling down and reaching to last mat-row in mat-table, a thick line appears

### ISSUE THREAD

**Issue by niteshbadaiu** [MurhafSousli/ngx-scrollbar#609]
I am using mat-table inside ng-scrollbar.
![line](https://github.com/MurhafSousli/ngx-scrollbar/assets/97160939/26cba2ff-d351-4934-8926-2a36d364fa4f)
 After scrolling down and reaching to last mat-row i am getting a thick dark line . This is not happening with other componets. How can i remove this?

**Comment by MurhafSousli** [comment]
You need to reproduce the issue in a stackblitz

**Comment by niteshbadaiu** [comment]
Thank you for the response.
I have done the above. I have added a comment with a link to a minimal
angular app on stackblitz. Please check it

**Comment by MurhafSousli** [comment]
I don't know the exact reason. maybe you won't get this in this extra space at the bottom with the latest version of ngx-scrollbar.

A quick fix for this in ngx-scrollbar v13 is

```css
table {
  display: inline-table;
} 
```

Here is a [fixed stackblitz](https://stackblitz.com/edit/minimal-angular-dbcgyf?file=src%2Fapp%2Fapp.component.html,src%2Fapp%2Fapp.component.css)

**Comment by niteshbadaiu** [comment]
Thank you very much sir

**Comment by niteshbadaiu** [comment]
Thanks, I'll check it out.
