### ISSUE TITLE
Best way to update scrollbar with dynamic content

### ISSUE THREAD

**Issue by incode4it** [MurhafSousli/ngx-scrollbar#61]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [x] question
```

### Versions
Angular CLI: 6.0.8

Is there a way to automatically update the scrollbar with dynamic content or what is the best way to do this? 
stackblitz: https://stackblitz.com/edit/angular-enxwyr?file=src%2Fapp%2Fapp.component.ts
The problem is that the X scrollbar does not appear on content change.

**Comment by MurhafSousli** [comment]
Hi @incode4it It should detect changes automatically using the **MutationObserver**.

To set the text dynamically you can use `[innerHtml]="text"`  or `[innerText]="text"` or `[contentText]="text"` but not `{{text}}`

https://stackblitz.com/edit/angular-ssdwnu?file=src%2Fapp%2Fapp.component.html
