### ISSUE TITLE
 WeakRef is not defined

### ISSUE THREAD

**Issue by veneliniliev** [MurhafSousli/ngx-scrollbar#610]
#### Reproduction

When using an older browser, an error "WeakRef is not defined" occurs in flackr/scroll-timeline.

Steps to reproduce:

1. Open the application in a browser that does not support WeakRef (e.g., Chrome before 109).
2. Try to perform basic functions within the application.
3. Observe the console for errors.
 
#### Expected Behavior

The application should function correctly without any errors, regardless of the browser being used.

#### Actual Behavior

When using an older browser, the following error appears in the console:

`Uncaught ReferenceError: WeakRef is not defined`

#### Environment

- Angular: 17.0.5
- ngx-scrollbar: 14.1.1
- Browser(s): Chrome 109 (This is the latest available version of Chrome for Windows 7)
- Operating System (e.g. Windows, macOS, Ubuntu):  Windows 7

**Comment by MurhafSousli** [comment]
Here we cannot do anything about it, you should specify the browser version and the error on their repository.

Or use the older version of ngx-scrollbar@13
