### ISSUE TITLE
help: Can I extend the scroll area to beyond the boundaries of the external viewport?

### ISSUE THREAD

**Issue by lucas-softr** [MurhafSousli/ngx-scrollbar#612]
#### What are you trying to do?

I want to allow users to scroll my content while their pointers are positioned in an area larger than the scrollable element. For example:

![image](https://github.com/MurhafSousli/ngx-scrollbar/assets/152630018/95632591-54a6-4cb2-bdd8-6e8a5f863ec8)

#### What troubleshooting steps have you tried?

I tried using the external viewport/content directives as described on the [wiki advanced usage](https://github.com/MurhafSousli/ngx-scrollbar/wiki/usage#advanced-usage-select-a-custom-viewport-element).

#### Reproduction

StackBlitz with reproduction: https://stackblitz.com/edit/ngx-scrollbar-kn9vpj?file=src%2Fmain.ts

(Sorry for the terrible design 😂)
  
#### Environment

- Angular: 18
- ngx-scrollbar: 15
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): MacOS

**Comment by MurhafSousli** [comment]
We don't have this feature, the scrollbars are designed to mimic the default scrollbar behavior. when you select an external viewport the scrollbars are attached inside the viewport and will be limited to its boundaries.

But maybe you can try sticky position to achieve that https://stackblitz.com/edit/ngx-scrollbar-qhoazq?file=src%2Fmain.ts

**Comment by lucas-softr** [comment]
Using sticky position was very clever, thanks for the effort! But I'd still need to position the scrollbar in a different place and this feels like a workaround.

I will close the issue since this is out of scope for this library, thanks.
