### ISSUE TITLE
When applying externalViewport directive, scrollbar ref with @ViewChild decorator gets undefined

### ISSUE THREAD

**Issue by Dozorengel** [MurhafSousli/ngx-scrollbar#614]
#### Reproduction

Steps to reproduce:
1. Apply externalViewport directive to <ng-scrollbar>
2. Use @ViewChild to get <ng-scrollbar> reference
 
 
#### Expected Behavior

In ngAfterViewInit hook there is a reference with actual value

#### Actual Behavior

In ngAfterViewInit hook there is a reference with undefined

#### Environment

- Angular: 18.0.4
- ngx-scrollbar: 15.0.1
- Browser(s): Edge 126.0
- Operating System (e.g. Windows, macOS, Ubuntu): MacOS Sonoma 14.5

**Comment by MurhafSousli** [comment]
Add reproduction please https://stackblitz.com/edit/ngx-scrollbar
