### ISSUE TITLE
Why has been Padding removed in version 15?

### ISSUE THREAD

**Issue by montella1507** [MurhafSousli/ngx-scrollbar#616]
#### Feature Description
--scrollbar-padding is really important features to provide easier way to "pick thumb". Is it possible to port it to version 15 as well?

**Comment by MurhafSousli** [comment]
It was not removed!

**Comment by montella1507** [comment]
It does not work in version 15. it is not in the documentation and i cant see that i source code used.

**Comment by montella1507** [comment]
Scrollbar offset works differentlyi think. 

Padding was triggering HOVER, scrollbar offset does not.

**Comment by MurhafSousli** [comment]
> It does not work in version 15. it is not in the documentation and i cant see that i source code used.

It is mentioned here https://github.com/MurhafSousli/ngx-scrollbar/wiki/styling

After v15, the scrollbar wrapper is positioned using absolute positioning instead of padding. is there a use case why you want to trigger hovering effect when hovering over the empty area?

**Comment by montella1507** [comment]
Yes. 
User experience. Do not hide so much space but make it easy to use. Check video of v15 - custom modified

https://github.com/MurhafSousli/ngx-scrollbar/assets/10418323/c8a26b54-e458-42e3-ba76-e5cf4d2497c7

**Comment by MurhafSousli** [comment]
Ok, I will add this as an option.

**Comment by MurhafSousli** [comment]
You can now have that hover effect by using the new option `<ng-scrollbar hoverOffset> ... </ng-scrollbar>`

**Comment by montella1507** [comment]
Thanks Will try.
