### ISSUE TITLE
Issue with ngx-scrollbar and Autosize Textarea

### ISSUE THREAD

**Issue by JayAhn2** [MurhafSousli/ngx-scrollbar#617]
#### Reproduction

Use StackBlitz to reproduce the issue: https://stackblitz.com/edit/6x7kqx

1. Open this StackBlitz project.
2. Write a long text into the textarea that exceeds 300px in height, causing the vertical scrollbar in the ng-scrollbar tag to appear.

3. Scroll to the middle of the text and try to type something in the middle of the textarea.

### Move to scroll to the middle
<img width="382" alt="image" src="https://github.com/MurhafSousli/ngx-scrollbar/assets/25868002/c4a39220-9cdf-4f75-ba43-6dca7605f95c">

### Type somthing
<img width="380" alt="image" src="https://github.com/MurhafSousli/ngx-scrollbar/assets/25868002/918f3a4d-61da-4cbe-9338-457e4eb10af3">
 
#### Expected Behavior
When typing in the middle of the textarea, the vertical scrollbar should remain in its current position unless the text cursor (caret) is moved out of the visible area.

#### Actual Behavior
When typing in the middle of the textarea, the vertical scrollbar automatically moves to the top, causing the text view to jump unexpectedly. This behavior disrupts the user experience as the scrollbar should not move as long as the text cursor is within the visible area.

#### Environment

- Angular: 18.x.x
- ngx-scrollbar: 15.0.1
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): macOS

**Comment by MurhafSousli** [comment]
The actual behavior is the native expected behavior, try removing the scrollbar and use `overflow: auto` on a div instead, you will get the same behavior.

**Comment by JayAhn2** [comment]
You are right. It happens not only with ngx-scrollbar but also with `overflow: auto`.

I think it is not quite desirable behavior as normally scrollbar isn't moved to anywhere as far as text cursor is positioned within the scrolled view...

If you don't mind, do you have any idea to avoid this issue?

Many thanks!

**Comment by JayAhn2** [comment]
@MurhafSousli Seems I found the bug issue related to cdkTextareaAutosize

https://github.com/angular/components/issues/23834

Thanks!
