### ISSUE TITLE
The scrollbar is not working correctly with angular material tabs

### ISSUE THREAD

**Issue by incode4it** [MurhafSousli/ngx-scrollbar#62]
### Bug Report or Feature Request (mark with an `x`)
```
- [X] bug report -> please search issues before submitting
- [ ] feature request
- [X] question
```

### Versions
Angular CLI: 6.2.3
Node: 10.10.0
OS: linux x64
Angular: 6.1.8

### Repro steps
The scrollbar does not appear if it is inside a material tab except for the first one.
Even after updating the scrollbar, the scrollbar thumb is not working correctly, cannot drag down.
[stackblitz reproduction](https://stackblitz.com/edit/angular-pakb7l?file=app%2Ftab-group-basic-example.html) 

![ezgif com-crop](https://user-images.githubusercontent.com/29798240/45967198-eb671080-c035-11e8-9f23-5101b33c45c9.gif)

**Comment by MurhafSousli** [comment]
I tired your stackblitz and could not reproduce, the scrollbar are working!

**Comment by incode4it** [comment]
> I tired your stackblitz and could not reproduce, the scroll bars are working!

![ezgif com-crop](https://user-images.githubusercontent.com/29798240/45967128-afcc4680-c035-11e8-9505-8b2ec7e8c9eb.gif)

**Comment by MurhafSousli** [comment]
Dup of #48
