### ISSUE TITLE
Demo site is broken

### ISSUE THREAD

**Issue by dmmishchenko** [MurhafSousli/ngx-scrollbar#629]
#### Documentation Feedback

Seems like https://ngx-scrollbar.netlify.com/ is broken.

1. Go to: https://www.npmjs.com/package/ngx-scrollbar
2. Click on: Homepage
3. Get: Site Not Found Looks like you've followed a broken link or entered a URL that doesn't exist on Netlify.

**Comment by MurhafSousli** [comment]
Netlify changed the URL https://ngx-scrollbar.netlify.app/, need to update it in package.json as well
