### ISSUE TITLE
In IE10 +, scroll functionality is not working

### ISSUE THREAD

**Issue by ArunSiddu** [MurhafSousli/ngx-scrollbar#63]
### Auto scroll functionality is not working in IE browser
```
- [Scroll functionality is not working in IE10+ ] bug report -> please search issues before submitting
- [While dragging an element inside the scrollbar content, it should Auto scroll accordingly] feature request
- [In other browser it is working fine, do we need to add any poly fills for IE ? ] question
```

### OS and Version

Windows 10
Browser IE11

**Comment by MurhafSousli** [comment]
The plugin works properly on IE11.

The plugin uses `MutationObserver` so if the IE version does not support it, you can try a polyfill, check this [sa](https://stackoverflow.com/questions/13941417/availability-of-mutationobservers-in-internet-explorer)
