### ISSUE TITLE
Angular v16 integration

### ISSUE THREAD

**Issue by pawan-atl** [MurhafSousli/ngx-scrollbar#636]
Hi 

I have injected `ngx-scrollbar` npm into my angular v16 project and imported the `NgScrollbarModule` within the app.module.ts.

I did wrap my div section within the `<ng-scrollbar>` but nothing happens. 

Do I need to include the js/css manually into my angular.json? Any working example would be very helpful.

Thanks
Pawan

**Comment by MurhafSousli** [comment]
You have to use an earlier version for Angular 16, check the changelog.

**Comment by pawan-atl** [comment]
Thank you. will try and send update accordingly.

**Comment by pawan-atl** [comment]
Both 14x and 13x throws compile time error:-

`./node_modules/ngx-scrollbar/fesm2022/ngx-scrollbar-smooth-scroll.mjs:189:24-28 - Error: export 'take' (imported as 'take') was not found in 'rxjs' (possible exports: ArgumentOutOfRangeError, AsyncSubject, BehaviorSubject, ConnectableObservable, EMPTY, EmptyError, GroupedObservable, NEVER, Notification, NotificationKind, ObjectUnsubscribedError, Observable, ReplaySubject, Scheduler, Subject, Subscriber, Subscription, TimeoutError, UnsubscriptionError, VirtualAction, VirtualTimeScheduler, animationFrame, animationFrameScheduler, asap, asapScheduler, async, asyncScheduler, bindCallback, bindNodeCallback, combineLatest, concat, config, defer, empty, forkJoin, from, fromEvent, fromEventPattern, generate, identity, iif, interval, isObservable, merge, never, noop, observable, of, onErrorResumeNext, pairs, partition, pipe, queue, queueScheduler, race, range, scheduled, throwError, timer, using, zip)`

**Comment by MurhafSousli** [comment]
Make sure you have rxjs v7, here an example of Angular 16 with ngx-scrollbar@13 https://stackblitz.com/edit/ngx-scrollbar-v13?file=package.json
