### ISSUE TITLE
Alignment options for SmoothScrollToOptions 

### ISSUE THREAD

**Issue by Smarthard** [MurhafSousli/ngx-scrollbar#637]
#### Feature Description

I think it would be great if ngx-scrollbar could provide out-of-the-box solution for alignment of element user want to scroll into.

#### Use Case

```ts
ngxScrollbar.scrollToElement('#target', { align: 'middle' })
// also maybe: right, left, top, bottom
// probably combination of the above
```

In this case scrollbar will scroll to the middle of available scrollable container near the target element.

**Comment by MurhafSousli** [comment]
@Smarthard in v16, you can use all the options that `scrollTo` function has. and added a boolean option `center` to scroll to the center of a target element.
