### ISSUE TITLE
Angular 15 which ngx-scrollbar version is support?

### ISSUE THREAD

**Issue by NaveenKumar24** [MurhafSousli/ngx-scrollbar#639]
#### Reproduction

Use StackBlitz to reproduce your issue: https://stackblitz.com/edit/ngx-scrollbar

Steps to reproduce:
1. 
2. 
 
 
#### Expected Behavior

What behavior were you expecting to see?

#### Actual Behavior

What behavior did you actually see?

#### Environment

- Angular:
- ngx-scrollbar:
- Browser(s):
- Operating System (e.g. Windows, macOS, Ubuntu):

**Comment by MurhafSousli** [comment]
No support, use v11.0.0, maybe v12.0.1 https://github.com/MurhafSousli/ngx-scrollbar/blob/master/CHANGELOG.md#1100
