### ISSUE TITLE
No code sample for scroll events

### ISSUE THREAD

**Issue by sharathdaniel** [MurhafSousli/ngx-scrollbar#640]
#### Documentation Feedback

I don't see any code sample for scroll events like top reached, bottom reached etc. Even the stackblitz example is not having anything.

How would someone understand to implement these events without even a mention in the documentation.

EDIT: Is this the [link](https://github.com/MurhafSousli/ngx-scrollbar/wiki/Reached-Events) to events documentation? I had to expand the pages menu in the sidebar, This can be missed way easily. Also where is the doc for dropped events?

IMO the below section in the Wiki home page should have links.
![image](https://github.com/user-attachments/assets/ba1b38ec-1cbe-43cd-8195-8cd768826e03)

**Comment by MurhafSousli** [comment]
No, that link is for the older version (v13), but it is almost the same usage. I will add guide for the reached / dropped events soon.

**Comment by MurhafSousli** [comment]
Added [Reached & Dropped Events docs](https://github.com/MurhafSousli/ngx-scrollbar/wiki/Reached-&-Dropped-Events)

**Comment by sharathdaniel** [comment]
@MurhafSousli Is this correct or did you meant NgScrollReached? (in the import statement)

![image](https://github.com/user-attachments/assets/298c39e7-3497-44ef-a711-083bad5c7097)

**Comment by MurhafSousli** [comment]
Yea, need to correct it

**Comment by sharathdaniel** [comment]
@MurhafSousli Sorry to bother you again. The below entire line is missing from the documentation of events. Its present in the legacy events example.

`import { NgScrollReached, NgScrollDropped } from 'ngx-scrollbar/reached-event';`

**Comment by MurhafSousli** [comment]
Added the imports lines
