### ISSUE TITLE
How can I have a horizontal scrollbar both above AND below

### ISSUE THREAD

**Issue by augiegardner** [MurhafSousli/ngx-scrollbar#647]
Want to have two scrollbars, one above, one below, when available for X scrolling.

Documentation shows orientation position which can show scrollbar above.

Does not show how to show 2 scrollbars.

**Comment by MurhafSousli** [comment]
It's unclear what you're asking for! orientation can be `auto`, `vertical` or `horizontal`, just treat it has a normal scrollable div element. provide a reproduction to your issue so I can look into. https://stackblitz.com/edit/ngx-scrollbar
