### ISSUE TITLE
Update to angular v7

### ISSUE THREAD

**Issue by talhajunaidd** [MurhafSousli/ngx-scrollbar#65]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x ] feature request
- [ ] question
```

### OS and Version?

Windows 10

### Versions

7.0.2

### Repro steps

After upgrading to angular v7 I'm facing following warning in the log

```
npm WARN ngx-scrollbar@2.2.0 requires a peer of @angular/common@^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN ngx-scrollbar@2.2.0 requires a peer of @angular/core@^6.0.0 but none is installed. You must install peer dependencies yourself.
```

**Comment by MurhafSousli** [comment]
This is just a warning because of peer dependencies versions, but the module works fine on Angular 7
