### ISSUE TITLE
Disable/ Suppress the scroll bar during runtime

### ISSUE THREAD

**Issue by starsibi** [MurhafSousli/ngx-scrollbar#658]
#### Feature Description

Disabling or suppressing the scrollbar during runtime in an Angular application involves dynamically controlling the scrollbar’s interaction based on certain conditions or user actions. This feature is useful when you want to temporarily prevent users from scrolling through content, perhaps during a loading state or when displaying a modal dialog.

Key Points:
Dynamic Control: You can enable or disable the scrollbar interaction at any point during the application’s runtime.
User Interaction: The feature typically involves toggling a boolean property that controls whether the scrollbar is active or suppressed.
Implementation: This is achieved using the disableInteraction property of the ngx-scrollbar component, which can be bound to a variable in your component’s class.
Use Cases: Common scenarios include preventing scrolling while data is being fetched, during animations, or when a modal or overlay is active.

**Comment by MurhafSousli** [comment]
There is the `disableInteraction` option with the scrollbar controls, but it doesn't disable scrolling with the wheel. because the scroll is native functionality. you can disable scrolling by toggling to `overflow: hidden`  on the viewport
