### ISSUE TITLE
BUG ngx-scrollbar 16.0.0 The scroll stays at the very top and does not move when scrolling on safari

### ISSUE THREAD

**Issue by ZMizgalski** [MurhafSousli/ngx-scrollbar#663]
#### Reproduction

https://stackblitz.com/edit/stackblitz-starters-ww4be4

Steps to reproduce:
1. Try to scroll on safari and then on chrome

#### Expected Behavior

The scroll should move down as you move items on chrome everything works but on safari it does not

#### Actual Behavior

What behavior did you actually see?

The scroll stays at the very top and does not move when scrolling only on safari

#### Environment

- Angular: 18.2.5
- ngx-scrollbar: 16.0.0
- Browser(s): 

Safari: Version 18.0 (20619.1.26.31.6)
CHrome: Version 129.0.6668.60

- Operating System (e.g. Windows, macOS, Ubuntu): MacOS 18

**Comment by MurhafSousli** [comment]
Was it working in v15?

**Comment by ZMizgalski** [comment]
I am currently using 15.1.3 and its working

**Comment by MurhafSousli** [comment]
Currently I don't have an access to a macbook, do you see any errors in the console

**Comment by ZMizgalski** [comment]
<img width="689" alt="" src="https://github.com/user-attachments/assets/58b557c8-e33e-4789-bf10-39b65d2ebc97">

**Comment by MurhafSousli** [comment]
It's possible that your browser is not allowing loading the script from the source link. try to load the polyfill locally, see [polyfill guide](https://github.com/MurhafSousli/ngx-scrollbar/blob/master/projects/ngx-scrollbar/docs/Scroll-timeline-polyfill.md)

**Comment by ZMizgalski** [comment]
I've added polyfill to stackblitz and on the ios simulator and regular safari it works fine but in the local project the same behaviour as before. Scroll is at the very bottom.

<img width="651" alt="" src="https://github.com/user-attachments/assets/2f2a645c-1842-4156-baff-17fa28ac4ed1">

**Comment by MurhafSousli** [comment]
Search in the issue section for the error you're getting, this issue was resolved https://github.com/MurhafSousli/ngx-scrollbar/issues/624
