### ISSUE TITLE
Missing documentation for replacement of "track" by "orientation"

### ISSUE THREAD

**Issue by Blafasel3** [MurhafSousli/ngx-scrollbar#665]
In the release notes for release 14, I could not find any hint that the input property 'track' was renamed to 'orientation' (breaking change). I had to go inside the code in order to find the replacement.

Just found this
https://github.com/MurhafSousli/ngx-scrollbar/pull/577/files#diff-06572a96a58dc510037d5efa622f9bec8519bc1beab13c9f251e97e657a9d4edL111

Should appear in the release notes -> https://github.com/MurhafSousli/ngx-scrollbar/releases/tag/v14.0.0-beta.1

**Comment by Blafasel3** [comment]
Also I cannot find any info for `pointerEventsMethod`, `verticalScrolled`. We also used `?scrollbar.viewport.scrollHeight`
and I'm not sure what to replace it with.

**Comment by MurhafSousli** [comment]
You're right, usually I write the release note after updating the changelog, I have no idea how I didn't add that there. I updated the release note for that version

**Comment by Blafasel3** [comment]
Thx for the quick update! I also wanted to mention that in general this library is extremely well documented. Considering the big refactoring you did in version 14 it is no wonder some little parts slipped thru!

**Comment by MurhafSousli** [comment]
Thanks! I am glad it helps
