### ISSUE TITLE
ERROR in node_modules/ngx-scrollbar/lib/scrollbar.component.d.t

### ISSUE THREAD

**Issue by waguirre** [MurhafSousli/ngx-scrollbar#67]
### Bug Report or Feature Request (mark with an `x`)
```
- [ x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] question
```

### OS and Version?

Windows 10

### Versions

![image](https://user-images.githubusercontent.com/2904511/47661888-e8e16480-db67-11e8-9471-55b2210b09b8.png)

### Mention any other details that might be useful

![image](https://user-images.githubusercontent.com/2904511/47661910-f3036300-db67-11e8-9698-2846ca590f68.png)

**Comment by MurhafSousli** [comment]
You need to install `@angular/cdk`, see the [changelog](https://github.com/MurhafSousli/ngx-scrollbar/blob/master/CHANGELOG.md)
