### ISSUE TITLE
ngx scrollbar does not work in angular material sidenav

### ISSUE THREAD

**Issue by Jonibigoud** [MurhafSousli/ngx-scrollbar#68]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] question
```

### OS and Version?
Windows 10 x64

### Versions

@angular/animations7.0.1
@angular/cdk7.0.2
@angular/common7.0.1
@angular/compiler7.0.1
@angular/core7.0.1
@angular/forms7.0.1
@angular/material7.0.2
@angular/platform-browser7.0.1
@angular/platform-browser-dynamic7.0.1
@angular/router7.0.1
core-js2.5.7
ngx-scrollbar2.3.0
rxjs6.3.3
zone.js0.8.26

### Repro steps

https://stackblitz.com/edit/angular-teziry

### The log given by the failure

no error in log

### Desired functionality

Would like to be able to use ngx scrollbar into a angular material sidenav/drawer or drawer-container.
ngx scrollbar won-t work either into a material sidenav/drawer or into a material sidenav container. It looks as if there was a problem with "height" even if set in stylesheet...

**Comment by MurhafSousli** [comment]
This isn't a bug, it is about CSS. check how it used in this [app](https://murhafsousli.github.io/ngx-sharebuttons/) with mat-sidenav

Check the app code: [nav-menu file](https://github.com/MurhafSousli/ngx-sharebuttons/blob/master/projects/demo/src/app/shared/nav-menu/nav-menu.component.html), [mat-sidenav file](https://github.com/MurhafSousli/ngx-sharebuttons/blob/master/projects/demo/src/app/app.component.html)

[Fixed Stackblitz](https://stackblitz.com/edit/angular-mmyab1?file=src%2Fapp%2Fapp.component.scss)

**Comment by Jonibigoud** [comment]
Thanks a lot.
