### ISSUE TITLE
Horizontal scrolling alone is not possible

### ISSUE THREAD

**Issue by Nekronik** [MurhafSousli/ngx-scrollbar#72]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] question
```

### OS and Version?

Any

### Versions

Angular CLI: 7.0.2
Node: 10.12.0
OS: linux x64
Angular: 7.0.0
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, platform-server, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.10.2
@angular-devkit/build-angular     0.10.2
@angular-devkit/build-optimizer   0.10.2
@angular-devkit/build-webpack     0.10.2
@angular-devkit/core              0.7.5
@angular-devkit/schematics        0.7.5
@angular/cdk                      7.0.2
@angular/cli                      7.0.2
@ngtools/webpack                  7.0.2
@schematics/angular               0.7.5
@schematics/update                0.10.2
rxjs                              6.3.3
typescript                        3.1.3
webpack                           4.19.1

### Repro steps

When content is provided to scrollbar component it renders with height 0.
(Remove height style from ng-scrollbar component in stackblitz)

### Desired functionality

A way to make the scrollbar component scroll horizontally where the height of the view equals the height of the content.
Content should be able to expand the scrollbar component and max-height could be used as the limiting factor to decide if it should have a scrollbar or not.

### Mention any other details that might be useful

Absolute positioning does not affect parent's height

**Comment by MurhafSousli** [comment]
@Nekronik fixed in v3.1.0
