### ISSUE TITLE
Breaks on resize

### ISSUE THREAD

**Issue by ErraticFox** [MurhafSousli/ngx-scrollbar#81]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] question
```

### OS and Version?

Windows 10
### Versions

Unable to as I've reproduced in StackBlitz

### Repro steps

https://stackblitz.com/edit/angular-material2-issue-mqhr8u

This seems to happen around the width of 950px

### Desired functionality

On smaller screen sizes, the scrollbar seems to break (revert to vanilla looks) and not change back when resizing again. Though in the StackBlitz template, it might already break when you first load in. You'll have to enlarge the preview window, refresh the preview window and then you'll see it loads properly, though if you shrink the preview window, it reverts back to original state. Console does not show any errors, so I'm unsure what's causing this.

### Mention any other details that might be useful

I've linked StackBlitz demo above.

**Comment by MurhafSousli** [comment]
Fixed in v3.1.3

**Comment by ErraticFox** [comment]
Wow, incredibly fast fix and I really appreciate that as I continued to work with it hoping for a hotfix haha. As I tried using `ngx-perfect-scrollbar` but I found yours much more simple to use but also way more defined and robust, in my opinion. 😄

**Comment by ErraticFox** [comment]
P.S. would it be possible to change the class `ng-scrollbar-view` to have `overflow` set to `hidden`? This wouldn't matter for mobile, but if someone is using a small screen size on desktop, you can see the vanilla scrollbar sticking out about a quarter. For now, I've just overwritten the class in my app though it'd be nice for it to be supported. ❤️
