### ISSUE TITLE
Missing ScrollingModule, supportsScrollBehavior, supportsScrollBehavior, ScrollingModule warnings.

### ISSUE THREAD

**Issue by rzabila** [MurhafSousli/ngx-scrollbar#85]
### Bug Report or Feature Request (mark with an `x`)
- [ x ] bug report
- [ ] feature request
- [ ] question

### OS and Version?
> Windows 10

### Versions
Angular CLI: 6.0.8
Node: 9.10.0
OS: win32 x64
Angular: 5.2.11

### Repro steps
1. npm i -S ngx-scrollbar @angular/cdk
2. ng serve --ssl true --port 3000 --host 0.0.0.0 --live-reload false

### The log given by the failure
WARNING in ./node_modules/ngx-scrollbar/fesm5/ngx-scrollbar.js
279:30-45 "export 'ScrollingModule' was not found in '@angular/cdk/scrolling'

WARNING in ./node_modules/ngx-scrollbar/fesm5/ngx-scrollbar.js
29:12-34 "export 'supportsScrollBehavior' was not found in '@angular/cdk/platform'

WARNING in ./node_modules/ngx-scrollbar/fesm5/ngx-scrollbar.js
49:16-38 "export 'supportsScrollBehavior' was not found in '@angular/cdk/platform'

WARNING in ./node_modules/ngx-scrollbar/fesm5/ngx-scrollbar.js
948:24-39 "export 'ScrollingModule' was not found in '@angular/cdk/scrolling'

### Desired functionality
Would be great to fix this issue.

**Comment by MurhafSousli** [comment]
Install angular cdk `npm i -S @angular/cdk@7.0.3`

**Comment by rzabila** [comment]
@MurhafSousli there is problem when user can't update cdk/angular version.

**Comment by MurhafSousli** [comment]
Stick to the older version if you cannot update!
