### ISSUE TITLE
Content goes out of the container when scroll bar is not present

### ISSUE THREAD

**Issue by rooby** [MurhafSousli/ngx-scrollbar#86]
### Bug Report or Feature Request (mark with an `x`)
```
- [ x ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] question
```

### OS and Version?
Windows server 2012 R2
Chrome 69

### Versions
node v8.12.0
npm v6.4.1
Angular 6.0.3

### Repro steps
Demo: https://stackblitz.com/edit/angular-685xeg

I have a content area where the content is in collapsible divs, so when all the divs are collapsed there is no vertical overflow, so the scroll bar is not visible. Then when I expand the divs the scrollbar appears.

When the scrollbar is hidden, all the content moves to the right and goes out of the container and when the scrollbar is visible it looks like it should.

I notice that .ng-scrollbar-container has right 17px and the div inside it (.ng-scrollbar-view) has width calc(100% + 17px).
.ng-scrollbar-container also has left 0 on it though, so the right 17px does nothing, so the width is going outside the container.

If I remove that left 0 and the right 17px works but then that affects the left side of the content, because it moves the whole content across.

### The log given by the failure
There is no error message, it's a visual bug.

### Desired functionality
The content should stay in the same place, within the content wrapper, both when the scroll bar is visible and invisible.

My intent is that my content wrapper div is 100% wide and my content div has a 20 pixel gutter (margin or padding, whatever works) and the scroll bar is inside that 20 pixel gutter.

**Comment by rooby** [comment]
Seems like if there was a right padding of 17 pixels when the scrollbar is hidden and not when the scrollbar is visible.

**Comment by Jonibigoud** [comment]
Same problem with angular 7.0.3. 
My content wrapper is made of angular material button toggle menus and sometimes material expansion panels.
Had to go back to ngx-scrollbar@2.3.0 to make it work properly.

**Comment by nreynis** [comment]
Adding this to the global stylesheet fix the issue for me:

```css
.ng-scrollbar-view{
  overflow-y: scroll !important;
}
```

**Comment by MurhafSousli** [comment]
@nreynis I need a reproduction to see the issue

**Comment by rooby** [comment]
I have added a demo here: https://stackblitz.com/edit/angular-685xeg

Angular 7.

You can see that the content goes outside the grey div while there is no scrollbar. Then click the button to show more content so that a scrollbar appears and the content squeezes over to the left to accommodate the scrollbar.

If you replace the ng-scrollbar element with a regular div, then the content no longer flows outside the grey div.

**Comment by MurhafSousli** [comment]
@rooby it is the `ScrollbarModule` changed to `NgScrollbarModule` and `ScrollbarComponent` name changed to `NgScrollbar`

**Comment by MurhafSousli** [comment]
It should be fixed now, please try `v3.2.0`

**Comment by nreynis** [comment]
@MurhafSousli , IMHO the situation is worse than before.
Now when I toggle content I get this:
- **hide some content**: the content is cropped (content expand) for a whole second before being reflowed back to the correct width (content shrink)
- **show more content**: the native scrollbar appear for a whole second (content shrinked) before being replaced (content expand back)

The content jumps all around two times and you've got to much reflow/repaint.
I'd rather stick with `v3.1.3` and my workaround.

**Comment by MurhafSousli** [comment]
@nreynis  The repro for this issue is fixed, if you have an issue please open a new issue with a reproduction
