### ISSUE TITLE
Content goes out of the container when scroll bar is not present, native scrollbar visible

### ISSUE THREAD

**Issue by nreynis** [MurhafSousli/ngx-scrollbar#88]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] question
```

### OS and Version?
Windows server 2012 R2
Windows 10
Chrome 69
Firefox 63,
Edge

### Versions
node v8.12.0
node v10.12.0
npm v6.4.1
npm v6.4.2
Angular 6.0.3
Angular 7.0.3
ngx-scrollbar 3.1.3
ngx-scrollbar 3.2.0

### Repro steps
**ngx-scrollbar 3.1.3**
Content is being cropped when scrollbar is not present.
Toggles the node in demo:
https://angular-ngx-scrollbar-crop-bug-1.stackblitz.io
https://stackblitz.com/edit/angular-ngx-scrollbar-crop-bug-1

**ngx-scrollbar 3.2.0**
Content is being cropped when scrollbar is not present for a whole second before being reflowed back to the correct width.
When adding content the native scrollbar appear for a whole second (content shrinked) before being replaced.
Toggles the node in demo:
https://angular-ngx-scrollbar-crop-bug-2.stackblitz.io
https://stackblitz.com/edit/angular-ngx-scrollbar-crop-bug-2

### Mention any other details that might be useful
Related issue:
https://github.com/MurhafSousli/ngx-scrollbar/issues/86

Proposed fix:
Adding:
```
.ng-scrollbar-view{
  overflow-y: scroll !important;
}
```
This way the native scrollbar is always there: you don't have to do tricky thing to account for it's possible absence. Also you trigger less reflow which is better from the UX perspective.

https://angular-ngx-scrollbar-crop-bug-3-proposed-fix.stackblitz.io
https://stackblitz.com/edit/angular-ngx-scrollbar-crop-bug-3-proposed-fix

**Comment by MurhafSousli** [comment]
Thanks for the feedback @nreynis, using `overflow-y: scroll` is a good idea.
fixed in 3.2.1, [fixed stackblitz](https://stackblitz.com/edit/angular-ngx-scrollbar-crop-bug-2-cet62m)
