### ISSUE TITLE
Easing issues

### ISSUE THREAD

**Issue by adrienlamotte** [MurhafSousli/ngx-scrollbar#90]
### Bug Report or Feature Request (mark with an `x`)
```
- [x ] bug report
- [ ] feature request
- [ ] question
```

### OS and Version?
ALL

### Versions
Angular 7
ngx-scrollbar 3.2.1 (latest)

### Repro steps
https://stackblitz.com/edit/angular-ngx-scrollbar-crop-bug-2-elsge6

### Desired functionality
Hello !
As you can see on the stackblitz, I try to use the smoothscroll but : 
- I set a duration of 5000ms, and the animation seems to be executed in ~3000ms
- The duration of the scrollToBottom is fastest, ~2000ms, and the animation seems to be cut before the end.

Is used the default easing function, but it is the same when trying the others (inOutQuintic, ...).

Do you have any clue ?

Thank you for your work and your help :-)

**Comment by MurhafSousli** [comment]
Hmmm! maybe because the increment value is `20` https://github.com/MurhafSousli/ngx-scrollbar/blob/master/projects/ngx-scrollbar/src/smooth-scroll/smooth-scroll.ts#L102

**Comment by adrienlamotte** [comment]
I just made a PR : https://github.com/MurhafSousli/ngx-scrollbar/pull/91 :-)

**Comment by MurhafSousli** [comment]
Thanks!
