### ISSUE TITLE
Add support for max-height

### ISSUE THREAD

**Issue by 93Alliance** [MurhafSousli/ngx-scrollbar#92]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] question
```

### Mention any other details that might be useful

ngx-perfect-scrollbar support to set `max-height`

**Comment by MurhafSousli** [comment]
You can set the max-height to `ng-scrollbar` just like any other HTML element!

**Comment by 93Alliance** [comment]
It will not work

**Comment by MurhafSousli** [comment]
@93Alliance here is it https://stackblitz.com/edit/ngx-scrollbar-zhmtzu?file=src/app/home/home.component.scss

**Comment by 93Alliance** [comment]
I can't do that
```
<div style=" margin: 2em;">

	<ng-scrollbar #scrollable
                thumbClass="custom-scrollbars"
                [disableOnBreakpoints]="false">

		<div style="padding: 1em;" [innerHTML]="text"></div>
    
	</ng-scrollbar>
  
<div>
```
```
ng-scrollbar {
  max-height: 200px;
}
```

**Comment by 93Alliance** [comment]
I want to implement a scrollbar trigger based on the content size reaching the specified value

**Comment by 93Alliance** [comment]
Now I have to fix the height of the container

**Comment by 93Alliance** [comment]
The height of the parent container changes with the height of the content, and the scroll bar is triggered when the parent container height is greater than 300px.

Because the content can change.

eg.

```
<div style="max-height: 300px;">
	<ng-scrollbar #scrollable
                thumbClass="custom-scrollbars"
                [disableOnBreakpoints]="false">

		<div style="padding: 1em;" [innerHTML]="text"></div>
    
	</ng-scrollbar>
<div>
```

**Comment by MurhafSousli** [comment]
So what is the problem? it should work, please reproduce the issue in that stackblitz and show me how it does not work

**Comment by 93Alliance** [comment]
The above code will not work.You may try it.

**Comment by jonathanblancor** [comment]
I think I know what @93Alliance is referring to. @MurhafSousli in your example, https://stackblitz.com/edit/ngx-scrollbar-zhmtzu?file=src/app/home/home.component.scss, if the content is less than the pre-defined height, then there is empty space between that element that has content and the next element (please see attached picture). 
![image](https://user-images.githubusercontent.com/13365903/57651728-002fee80-759c-11e9-9de9-7ef8b2fee903.png)

However, if ngx-scrollbar were to support 'max-height', instead of just working with 'height', then that space that's in the picture would not be there because of how max-height works.

You can see a cool project which works with max-height: http://manos.malihu.gr/jquery-custom-content-scroller/ (not angular project though).

**Comment by MurhafSousli** [comment]
Hi @jonathanblancor thanks for explaining!

This scrollbar component should behave as a normal div.

For example: if you the height of a normal div is not set, it will not become scrollable and the native scrollbar will never appear.

You can simply change the height of the scrollbar component, you can use `height: auto` and `max-height` but that would not make the div scrollable, if you check the source code you will find that only when the native scrollbar are working, the custom scrollbars appears as an overlay and the native scrollbar are hidden.

So if you can make a div scrollable when `height: auto` then it should work the same way with NgScrollbar.

**jquery custom content scroller** works differently, this library is a custom overlay-scrollbars with native scrolling mechanism.

I don't think there is a feature missing in a 
If you know a solution, please give me PR

**Comment by adrienlamotte** [comment]
@MurhafSousli Hello !
I'm struggeling with the same problem. Here is a stackblitz reproducing it : https://stackblitz.com/edit/ngx-scrollbar-fcedc2?embed=1&file=src/app/home/home.component.scss

> So if you can make a div scrollable when `height: auto` then it should work the same way with NgScrollbar.

As you can see it works with the native scrollbar (with `height: auto`), but with the exact same structure the scrollbar doesn't shows up.

My use case is a modal window witch can't have a fixed height.

Thanks !

**Comment by vytautas-pranskunas-** [comment]
Why this is closed?
