### ISSUE TITLE
Not AutoUpdating

### ISSUE THREAD

**Issue by edgargaza** [MurhafSousli/ngx-scrollbar#94]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] question
```

### OS and Version?

Windows 10

### Versions

Angular CLI: 6.2.7
ngx-perfect-scrollbar: 6.4.1

### Repro steps

Just modify the height that makes the parent div overflow, the scrollbar won't resize/disappear if it stops overflowing.

### Desired functionality

The handle should resize/appear if the overflow area resizes as well, and if there's no overflow anymore, it should disappear.

### Mention any other details that might be useful

Here's a gyazo:
[GIF](https://gyazo.com/56dfdc0a058e03dfaa53b12e54515e91)

**Comment by MurhafSousli** [comment]
This is not `ngx-perfect-scrollbar` repo, if your issue is with this plugin, please add a [repro stackblitz](https://stackblitz.com/edit/ngx-scrollbar)

**Comment by CodeCrusha** [comment]
Same problem for me for ngx-scrollbar (I guess he ment the same).

Just implemented it via <ng-scrollbar></ng-scrollbar> and modify the height of the browser-window. The scrollbar will not automatically appear/disappear even with autoUpdate="true"

**Comment by MurhafSousli** [comment]
@CodeCrusha I don't see anything wrong with the repro? what is the problem with the height?

**Comment by MurhafSousli** [comment]
@edgargaza The autoUpdate works when the content changes, but not when the styles changes because there is no such event in the browser, but you can easily trigger an update manually from the template like:

```html
<ng-scrollbar #scrollable 
              class="scrollable-div"
              (mouseenter)="scrollable.update()"
              (mouseleave)="scrollable.update()">

  <div style="padding: 1em;" [innerHTML]="text"></div>
    
</ng-scrollbar>
```
here is a [fixed stackblitz](https://stackblitz.com/edit/ngx-scrollbar-scyj76?file=src%2Fapp%2Fhome%2Fhome.component.html)
