### ISSUE TITLE
onscroll event

### ISSUE THREAD

**Issue by WenjiCui** [MurhafSousli/ngx-scrollbar#97]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ X ] feature request
- [ ] question
```

### Desired functionality
Hi, I have a simple request but cannot find the solution in the documentation. There should be an onscroll event fired whenever user scroll. I tried <ng-scrollbar (onscroll)="functionName"></ng-scrollbar> but it's not working.Thanks.

**Comment by MurhafSousli** [comment]
Hi @WenjiCui You can do that

```ts
@ViewChild(NgScrollbar) scrollRef: NgScrollbar;

this.scrollRef.scrollable.elementScrolled().subscribe(e => console.log(e))
```

It was mentioned in the [changelog](https://github.com/MurhafSousli/ngx-scrollbar/blob/master/CHANGELOG.md#breaking-changes)

**Comment by TejashreeD** [comment]
This solution does not work for angular 9. Any suggestions plz.

**Comment by MurhafSousli** [comment]
@TejashreeD that solution was for an older version, for the scroll event see the docs https://github.com/MurhafSousli/ngx-scrollbar/wiki/Scroll-Event

**Comment by TejashreeD** [comment]
@MurhafSousli Not working for me. 👎
