### ISSUE TITLE
Native scrollbars are not showing when custom scrollbar is disabled

### ISSUE THREAD

**Issue by ruizmarc** [MurhafSousli/ngx-scrollbar#99]
### Bug Report or Feature Request (mark with an `x`)
```
- [x ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] question
```

### OS and Version?

Mac OS Mojave 10.14.2 and (Safari 12.0.2 and  Chrome 70.0.3538.110). 

### Versions

Angular 7.1.0, ngx-scrollbar 3.3.0

### Repro steps

Set disabled param to true, properly deactivates the custom scrollbar, but it doesn't show native scrollbars.

### The log given by the failure

It happening in any of the projects we have. In fact, it also happens in your demo. Here you have an screenshot taken with Chrome. Scrollbar is disabled but no native scrollbars are appearing. 

<img width="501" alt="screenshot 2018-12-08 at 09 57 22" src="https://user-images.githubusercontent.com/5717082/49689043-f9262100-facf-11e8-9c96-7426cc3a9cba.png">

### Desired functionality

 I would expect to disable the custom scrollbar, but show native scrollbars instead.

**Comment by MurhafSousli** [comment]
Usually, user chooses either the custom scrollbars or the native ones! What is your use case?

**Comment by ruizmarc** [comment]
Thanks for doing it! ☺️

**Comment by ruizmarc** [comment]
Hi, I'm sorry to come back with this @MurhafSousli , but I've tested it in version 3.3.3, but I'm getting the same problem. When disabled is true, the custom scrollbar dissapears, but the native ones are not showing.
 In fact, in your demo page and in your stackblitz it is also happening. (MacOS with Safari 12 and Chrome 70)
